### ISSUE TITLE
Cannot build in clean repository

### ISSUE THREAD

**Issue by johnperry-math** [alire-project/alire#1002]
After cloning the repository, I try this per the instructions:

    gprbuild -j0 -P alr_env

...and get this:

    alr.gpr:1:06: imported project file "aaa" not found
    alr.gpr:2:06: imported project file "ada_toml" not found
    alr.gpr:5:06: imported project file "ajunitgen" not found
    alr.gpr:6:06: imported project file "semantic_versioning" not found
    alr.gpr:7:06: imported project file "simple_logging" not found
    alr.gpr:8:06: imported project file "uri" not found
    alr.gpr:9:06: imported project file "xml_ez_out" not found
    alire.gpr:1:06: imported project file "aaa" not found
    alire.gpr:1:06: imported by "/path/hidden/alire/alire.gpr"
    alire.gpr:1:06: imported by "/path/hidden/alire/alr.gpr"

...with lots more.

Of course it can't find it; I'm trying to build the thing. Can someone tell me what's wrong?

**Comment by Fabien-Chouteau** [comment]
Hi @johnperry-math,

You need to clone recursively `git clone --recursive git@github.com:alire-project/alire.git`

**Comment by johnperry-math** [comment]
Ah, geez, not my best moment. The README even says that! Sorry for the noise.

**Comment by Lucretia** [comment]
It doesn't. It says:

```
Follow these steps:Follow these steps:

    Clone the repository: git clone --recurse-submodules https://github.com/alire-project/alire.git
```

**Comment by Fabien-Chouteau** [comment]
Those two switches have the same effect.
