### ISSUE TITLE
Warning breaks evaluation of `printenv` output

### ISSUE THREAD

**Issue by treiher** [alire-project/alire#1005]
Since last night, `alr printenv` shows a warning, which prevents evaluating its output directly with `eval $(alr printenv)`:

```
eval: line 2: syntax error near unexpected token `('
```

The output of `alr printenv` is:

```
warn: Loading release from /home/reiher/.config/alire/indexes/community/repo/index/in/ini_files/ini_files-10.0.0.toml
licenses
licenses
Array of license in manifest is deprecated. License should be a single string containing a valid SPDX expression (https://spdx.org/licenses/)
export ALIRE="True"
export ...
```

The issue seems to be caused by some addition to the Alire index.

**Comment by mosteo** [comment]
Uuups. Going to fix it right away, thanks for the ping. Meanwhile, running with `-q` should work around the problem.

**Comment by mosteo** [comment]
Fixed in https://github.com/alire-project/alire-index/pull/506

**Comment by treiher** [comment]
Thank you for your prompt action.
