### ISSUE TITLE
Clarification on 'available' field semantics

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#101]
The requisites in the available field used to be a boolean tree, e.g.:
 
```(compiler = GNAT_2018) and (Word_Size = 64)```

In the current index description page, an example is given for a single condition. Since these conditions are case-based, ORs within a category are solved.

I tried to give a couple of conditions to see what happens:

```
[general.available.'case(distribution)']
      'debian|ubuntu' = true
      '...' = false
[general.available.'case(os)']
      'linux' = true
      '...' = false
```

Either of those, if alone, is correctly parsed. Using both simultaneously gives an error of "invalid case expression".

So, my questions:
- Should we allow multiple conditions? I'd say yes, seems quite possible they may arise.
  - If yes, should we allow OR across categories (e.g. compiler = foo or distribution = bar)? I'd say, no, unless a clear need is shown (seems less likely to be needed)
    - If no, could we simply allow several conditions, as in my test above, and say that they are ANDed?

**Comment by mosteo** [comment]
Pinging @pmderodat for your opinion on this one.

**Comment by pmderodat** [comment]
On one hand, as you said, for now we don’t see a real use case for ORed conditions. On the other hand, ANDed conditions can already be easily expressed with the current syntax:
```toml
[general.available.'case(distribution)']
    [general.available.'case(distribution)'.'debian|ubuntu'.'case(os)']
        linux = true
        '...' = false
    '...' = false
```

So I would be tempted to reserve the extension you suggest to ORed conditions, should the need arise in the future. I we need something more complex than that (I really hope not!), I guess we’ll need to fall back to a custom parser for availability expressions…

**Comment by mosteo** [comment]
Ah, I hadn't realized that cases could be nested. I agree that OR is unlikely to be needed, so we can cross that bridge when/if we arrive at it.
