### ISSUE TITLE
bitbucket not supported

### ISSUE THREAD

**Issue by RajaSrinivasan** [alire-project/alire#1011]
I have a project on bitbucket. https://ToprLLC@bitbucket.org/ToprLLC/passwords.git

When I tried to publish I got issues:

% alr publish https://ToprLLC@bitbucket.org/ToprLLC/passwords.git  9f1e8fed74c7d792ba3a204dbd106a3ec8dc0a5a

Publishing assistant: step 1 of 6: Verify origin URL
✓ Origin is of supported kind: GIT
error: Could not complete the publishing assistant:
error:    Origin is hosted on unknown site: ToprLLC@bitbucket.org

**Comment by mosteo** [comment]
It seems we're improperly obtaining the domain. Thanks for the report.
