### ISSUE TITLE
Bash autocomplete for alr

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#102]
Nice to have down the road

**Comment by pmderodat** [comment]
It would be very nice, indeed! I think however that it’s the job of the command-line parsing engine to provide this feature: ideally, `alr` would only provide data about the various options and their arguments and the engine would provide automatic completion for them.

FYI, I haven’t had time to spend on this, but I wanted to add this feature to `GNATCOLL.Opt_Parse` (https://github.com/AdaCore/gnatcoll-core/blob/master/src/gnatcoll-opt_parse.ads).
