### ISSUE TITLE
Release source tarball does not include submodules

### ISSUE THREAD

**Issue by JeremyGrosser** [alire-project/alire#1022]
The source code tarballs at https://github.com/alire-project/alire/releases cannot be built without the sources for the git submodules in the deps directory, but these sources are not included in the tarball. As the releases also exclude the .git directory, there is no way to populate the deps directory based only on the content of a release tarball.

I'm trying to package Alire for Alpine Linux and it would be much easier if the release tarballs had the deps directory populated. Ideally a release tarball should be buildable on any system with a working gprbuild and gnat. My current workaround is to download hardcoded commit hashes from github, which is ugly and tedious to maintain. I don't believe this would be accepted into the Alpine aports repository as-is.

https://github.com/JeremyGrosser/aports/commit/46fdfc38ba89e1d30a92d4dd458d1d4ca5314985

**Comment by mosteo** [comment]
These tarballs are automatically generated by GitHub. I guess in the worst case we could generate an additional set containing dependencies.

However, isn't some simple way for you to work from the git commit of the release? So you can git clone that with submodules and work from there. (I don't really know how the Alpine packaging process works.)

**Comment by JeremyGrosser** [comment]
Most OS packaging systems prefer to use source tarballs rather than depend on an external site like github that may change or go offline. If a source tarball is unavailable, Alpine supports building "snapshot" tarballs from git, but this is discouraged. I was hoping we could just make the source tarball usable.

**Comment by mosteo** [comment]
OK, understood.

**Comment by JeremyGrosser** [comment]
Oops, thought this had already been merged.
