### ISSUE TITLE
Document other operators besides ^ and ~ for dependencies

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#103]
After d843501896e203feec07ce3670b8b0e2907d1c09, all usual operators beside the caret/tilde are available for dependencies, even in unicode form:

foo = ">=1.2"
foo = "≥1.2"
foo = "/=3.1"
foo = "≠3.1"

I forgot to add this to the format spec, where caret and tilde are explained.

**Comment by pmderodat** [comment]
I can’t say I’m fond of using non-ASCII syntax for code. ^^’ It’s just too easy to have similar-but-not-the-same glyphs or accept some Unicode string for one glyph but not another form…

In any case, it would be also worth documenting in `semantic_versionning` that it expects its input to be UTF-8 strings.

**Comment by mosteo** [comment]
We can restrict it to ascii only. Since Ada code can contain unicode identifiers I thought it nice to have it, but it's a matter of switching a boolean parameter in calls to `Semantic_Versioning`.
