### ISSUE TITLE
Alire adds extra references to my configuration file

### ISSUE THREAD

**Issue by Joebeazelman** [alire-project/alire#1033]
I am working on a small Ada program which imports another Ada application as a library. I initialized my empty project using Alire and downloaded the Application's repository as a submodule and modified my GPR file to:

```
with "config/hal_builder_config.gpr";

project Hal_Builder extends "svd2ada/svd2ada.gpr" is
end Hal_Builder;
```

When I build the project, Alire mysteriously added the following project dependencies in my configuration file which won't compile:

```
--  Configuration for hal_builder generated by Alire
with "utilada_base.gpr";
with "utilada_conf.gpr";
with "utilada_core.gpr";
with "utilada_sys.gpr";
abstract project hal_builder_Config is
   Crate_Version := "0.0.0";

end hal_builder_Config;

```

Why are these lines added?

**Comment by Fabien-Chouteau** [comment]
Hello @Joebeazelman,

These come from one of your dependencies. What do you have in alire.toml?

**Comment by Joebeazelman** [comment]
I resolved my issue. I am not certain, but I believe I imported **utilada** library using **alr with utilada**.   I erroneously  thought I had to let my project know about it by adding a **with utilada** in **hal_builder.gpr** and it resulted in the error messages I got. 

I am still getting my head around the build system. I read the Gnat documents on document importing and it was hard to digest and very confusing. It kept changing examples as it progressed through a topic instead of building upon the previous one. Someone on gitter pointed me to the AdaCore docs version and it's much better written, but I still don't understand where dependencies are stored and how the compiler knows about them with and without Alire.

Slightly off topic, I am writing a utility that leverages svd2ada to automatically or semiautomatically generate HAL crates for MCUs based on their SVD files based on your gracious [instructions in AdaBlog.](https://blog.adacore.com/starting-micro-controller-ada-drivers-in-the-alire-ecosystem) The goal is to get a chance to explore all the sharp edges of Ada and see how bad I get cut. I will share it after I've made a bit of progress on it.

**Comment by mosteo** [comment]
When you create a crate with alire, you end with two project files:

    my_crate.gpr --> config/my_crate_config.gpr

The first one, in the root of your project, is generated once and can be tweaked manually if needed. But it contains a

    with "config/my_crate_config.gpr"

and this file inside `config/` is regenerated by Alire often so you shouldn't edit it by hand.

Dependencies in your `alire.toml` (added manually or via `alr with`) are withed in the autogenerated `config/` project file, so you don't have to also add them manually to your root project file.

**Comment by Fabien-Chouteau** [comment]
> Slightly off topic, I am writing a utility that leverages svd2ada to automatically or semiautomatically generate HAL crates for MCUs based on their SVD files based on your gracious [instructions in AdaBlog.](https://blog.adacore.com/starting-micro-controller-ada-drivers-in-the-alire-ecosystem) The goal is to get a chance to explore all the sharp edges of Ada and see how bad I get cut. I will share it after I've made a bit of progress on it.

That's a great project!

We should split svd2ada into a library on one hand and a tool that uses this library on the other hand, but honestly I don't think we will have the bandwidth to make it happen.

**Comment by Joebeazelman** [comment]
Yes. Originally, I wanted to link to Svd2Ada as a library, but extending it as an application is working well enough for my purposes. It already implements the basic infrastructure I need, so I'm just going to extend the application rather than incorporate it as a library. I suspect building it as a library is just a matter of excluding the main entry along with some changes in the settings. No?

**Comment by Fabien-Chouteau** [comment]
> I suspect building it as a library is just a matter of excluding the main entry along with some changes in the settings. No?

Yes that will work. I was thinking about a making clean clear library with proper API and documentation.

**Comment by Joebeazelman** [comment]
> > I suspect building it as a library is just a matter of excluding the main entry along with some changes in the settings. No?
> 
> 
> 
> Yes that will work. I was thinking about a making clean clear library with proper API and documentation.

The main svd2ada crams in command-line handling, svd processing and xml parsing subprocedures into one massive procedure. They're very useful for reuse, but their invisible outside the scope of the procedure, so I liberated them into independent packages. _Vive la résistance!_

Next step is to add the ability to specify a single file or a directory of SVDs for processing. I will need to find the names of the devices along with their associated general device family name. Wish me luck!

**Comment by Fabien-Chouteau** [comment]
@Joebeazelman keep me updated that sounds very interesting!
