### ISSUE TITLE
Multiple dependencies on a single project

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#104]
In the old index, we could specify any combination of dependencies, e.g., several for the same package:
`ada_toml >= 1.0 and ada_toml /= 1.5.3`

Right now, the syntax specifies a single string for a project:
`ada_toml = "^1.0"`

Although caret/tilde operators cover the most typical cases, it is common to have the ability to specify several conditions for a dependency. In other packagers this can be done with a list of ANDed deps (rust, comma separated) (and sometimes ORed too, opam).

Straightforward possibilities is to do like Rust:
`ada_toml = "^1.0,/=1.5.3"`
of use an array:
`ada_toml = ["^1.0" , "/=1.5.3"`]
and consider these ANDed.

@pmderodat, I believe you had ideas about this :-)

**Comment by pmderodat** [comment]
Thanks for raising this oversight in the TOML transition. :-) I have the feeling we need both ORed and ANDed constraints for versions. For instance, on one hand it would be useful to express “within major 1.0 AND not 1.5.3” (i.e. your example) but also “within major 2.0 OR 1.5.3” (for instance when requiring a bug fix that done for the 2.0 release and then that was backported to the 1.5 release branch).

What about using AND semantics inside a version set string (`"^1.0,/=1.5.3"` as you suggest above) while using OR semantics for arrays (`["^2.0", "1.5.3"]`). I don’t think we need more than disjunctions of conjuctions, so having only strings (conjunctions) or arrays of strings (disjunctions of conjuctions) seems enough.

Thoughts?

**Comment by mosteo** [comment]
It's subtle, which may be confusing at first, but it's simple. Works for me. Otherwise we should come with a  more general parser which is probably overkill.
