### ISSUE TITLE
`alr config` return wrong build profile when override is in manifest

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#1040]
Having e.g.

```
[build-profiles]
"*" = validation
```

will properly apply the validation profile (verifiable inspecting `config/crate_config.gpr`), but `alr config` will show

`last_build_profile=DEVELOPMENT`

Put another way, it seems that the configuration stored is only for the switch used with `alr build`.

**Comment by Fabien-Chouteau** [comment]
Indeed the `last_build_profile` is only used to keep track of the `alr build`  switches.
This information is intended to be internal/hidden and is used to re-generate the config GPR when the uses changes switches on the command line.

I am not sure why you tag this as a bug here.

**Comment by mosteo** [comment]
I thought that it could be problematic if the manifest specifies a build mode which doesn't match the one stored in the config. Maybe some regeneration could be skipped or so. My expectation was that the config value would always match that of the last build, no matter how it was specified.

As you know this area better, if this is proper please go ahead and close this issue.

**Comment by Fabien-Chouteau** [comment]
> I thought that it could be problematic if the manifest specifies a build mode which doesn't match the one stored in the config. Maybe some regeneration could be skipped or so.

I might be possible indeed.I would have to look into this because I don't remember.

> My expectation was that the config value would always match that of the last build, no matter how it was specified.
> 
> As you know this area better, if this is proper please go ahead and close this issue.

The way I see it we can:
 - Change the name of this config value
 - Change its behavior to always contain the last build profile used.
