### ISSUE TITLE
`alr init --lib` skel package should be pure/preelaborable

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#1041]
Else we lose the opportunity for more preelaborable libraries

**Comment by Fabien-Chouteau** [comment]
On the other hand newcomers might get stuck on a strange error message...

**Comment by mosteo** [comment]
I see your point. I don't really know what is better, as preelaborable packages can help in reducing elaboration circularities.

Perhaps also adding some comment that it is perfectly OK to remove it when circumstances demand it?

**Comment by Fabien-Chouteau** [comment]
Getting back to this. I still think it's not a good idea for beginners, and experts will know when to use Preepaborate. So I would close this issue.

**Comment by mosteo** [comment]
Understood.
