### ISSUE TITLE
Several actions and some with condition.

### ISSUE THREAD

**Issue by Blady-Com** [alire-project/alire#1063]
(Edited: the conditions were obviously misplaced, that don't change the relevance of the answer)
For our example crate, let have two post-fetch actions cmd_A and cmd_B, this gives:

```
[[actions]]
type = "post-fetch"
command = ["cmd_A", "-p1"]

[[actions]]
type = "post-fetch"
command = ["cmd_B", "-p2"]
```
But cmd_A takes -p1 on Linux and --p1 on macOS, so I might write:

```
[[actions.'case(os)'.linux]]
type = "post-fetch"
command = ["cmd_A", "-p1"]

[[actions.'case(os)'.macos]]
type = "post-fetch"
command = ["cmd_A", "--p1"]

[[actions]]
type = "post-fetch"
command = ["cmd_B", "-p2"]
```

But I get an error:
```
error:    action #1:
error:    forbidden extra entries: case(os)
```

How to get several actions and some with condition?

**Comment by mosteo** [comment]
You have uncovered a bug in our loader. The proper actual syntax for a conditional action is:

```
[[actions.'case(os)'.linux]]
type = "post-fetch"
command = ["make"]
```

But indeed as you discovered this precludes using also unconditional actions at the same time.

The workaround at this time would be to make all actions conditional, repeating these common to all scenarios. I will look into fixing this although I'm fearing it will be tricky without breaking back-compatibility.

**Comment by Blady-Com** [comment]
Thanks for you relevant answer (I edited my original post, the conditions were obviously misplaced, that don't change the relevance of the answer).
