### ISSUE TITLE
Select a temporary toolchain for a specific crate.

### ISSUE THREAD

**Issue by Blady-Com** [alire-project/alire#1064]
I have 2 toolchains GNAT CE 2020 and GNAT CE 2021.
I usually work with GNAT 2021 in my PATH:
```
% alr version
APPLICATION
alr version:               1.2.0
...
tool #1 gnat:              gnat_external=2021.0.0
tool #2 gprbuild:          gprbuild=2021.0.0
```
LibGPR dependance for GnatCOLL_Python3 needs GNAT 2020, so I put only GNAT 2020 in my PATH but I got this error:
```
% alr get gnatcoll_python3               
ⓘ Deploying gnatcoll_python3=21.0.0...                                   
  -#O=#  #    #                                                                
error: Not installed: gprbuild=2021.0.0
error: alr encountered an unexpected error, re-run with -d for details.
```
I may change my toolchain with:
```
% alr toolchain --select
```
But the toolchain is changed in my global settings, would'nt be convenient to be able to select a toolchain only for a specific crate when fetching this crate, maybe:
`% alr get gnatcoll_python3 --local-toolchain`
What is your feedback?

**Comment by mosteo** [comment]
You can already do that with `alr toolchain --select --local`, which will store in the local crate configuration your preferred toolchain.

Of course this won't work with a "still unfetched" crate if you're using `alr get`, but it should work for working crates already existing or being created through `alr init`.

One thing you can try is to retrieve the crate without dependencies (`alr get --only`), enter the deployment folder, configure the compiler with `--local`, and then do an `alr update` to complete dependencies.

Please let me know if that works, and reopen the issue if necessary.

**Comment by Blady-Com** [comment]
Great :-) that's fine. Surely worth including it in the FAQ if any.
