### ISSUE TITLE
Badge is broken

### ISSUE THREAD

**Issue by pjljvandelaar** [alire-project/alire#1066]
Dear Alire Developers,

I would like to promote my crates using the alire badge.
However, on https://alire.ada.dev/crates/dependency_graph_extractor.html I see 
![image](https://user-images.githubusercontent.com/18348654/174736556-cf104f3c-4996-4bf1-b0c1-a559e156282c.png)

I have no clue why the badge image is not available.

Is this a bug?

Greetings,
   Pierre

**Comment by mosteo** [comment]
I'm seeing the badge properly now:

![image](https://user-images.githubusercontent.com/264377/174743012-bf8a8a57-f2b0-4991-937e-b347bc3a5486.png)

Maybe it was a transitory problem?

**Comment by pjljvandelaar** [comment]
You are right: everything is fine now...

I hope this transitory problem doesn't occur every day when the database is updated ....

**Comment by mosteo** [comment]
It shouldn't, as the website is updated atomically once the new version is committed. At least that's my expectation on how GitHub sites work.

**Comment by pjljvandelaar** [comment]
I will close the issue, and only reopern when this transitory problem happens more often!

**Comment by Fabien-Chouteau** [comment]
The badges are provided by an external service (img.shields.io), potentially an issue on their side.
