### ISSUE TITLE
gnat_aarch64_elf toolchain?

### ISSUE THREAD

**Issue by robdaemon** [alire-project/alire#1075]
There is a gnat_arm_elf build in the Alire index, it would be great to have a gnat_aarch64_elf version available too.

**Comment by robdaemon** [comment]
With AdaCore's recent comments about the EOL for GNAT Community and them contributing to Alire, I wasn't sure where this request belonged. If this is the wrong place, I apologize in advance. Thanks!

**Comment by systems-praxis** [comment]
Yes, would be nice to target Raspberry Pi 3 bare-metal.

**Comment by Fabien-Chouteau** [comment]
Hello @robdaemon and @systems-praxis,

At this point we do not plan to support more targets than what was in GNAT Community.
