### ISSUE TITLE
`lvgl_ada_examples` fails to build

### ISSUE THREAD

**Issue by rocher** [alire-project/alire#1081]
When I try `alr get lvgl_examples` with:
- `alr` 1.2.0
- `gprbuild` 22.0.1
- `gnat_native` 11.2.4
- OS Ubuntu 22.04
I always get this error message
```
. . . 
make: Leaving directory '/home/ada/lvgl_ada_examples_0.1.0_8267a841/alire/cache/dependencies/sdlada_2.5.4_7981bbd6/build/gnat'
ⓘ Deploying lvgl_ada_simulator=0.1.1...
############################################...##100.0%
error: Configuration variable 'lvgl_ada.density_per_inch not set and has no default value.
```

**Comment by Fabien-Chouteau** [comment]
@rocher it should be fixed in https://github.com/alire-project/alire-index/pull/579

There were some issues in dependencies versions.

**Comment by rocher** [comment]
Hi @Fabien-Chouteau

I've just tried `alr get lvgl_ada` ,  `lvgl_ada_examples` and `lvgl_ada_simulator` and all of them fail to build with the same error message: `error: Configuration variable 'lvgl_ada.density_per_inch not set and has no default value.`.
I've made a "clean" `alr get` removing all previous revisions. Using the same environment as reported before.

**Comment by Fabien-Chouteau** [comment]
@rocher the change is not merged yet.
Also you will have to update your index when the change is merged: `alr index --update-all`

**Comment by rocher** [comment]
Ahh! Ok, thanks for the info @Fabien-Chouteau
