### ISSUE TITLE
alr publish refuses to build if a crate with same name/version exists in the loaded index

### ISSUE THREAD

**Issue by stcarrez** [alire-project/alire#1083]
I have a local index where I populate several project crates before publishing widely.
```
alr index
# NAME      URL                                                         PATH                                              
1 community git+https://github.com/alire-project/alire-index#stable-1.2 /home/ciceron/.config/alire/indexes/community/repo
2 local     file:///src/awa/alire-index-local                           /src/awa/alire-index-local
```
At some time in the publish process, it is necessary to re-publish to fix issues but when you do so, you'll get the error:
```
alr publish
✓ Local repository is clean.
error: Target release elada=1.8.4 already exist in a loaded index
```
and I have to remove the crate from my local repository to be able to run the command.

The `-f` (force) option does nothing.
May be Alire should:

* honor the `-f` option and ignore that error,
* don't report an error if the crate+version is found in a local repository

**Comment by stcarrez** [comment]
I've managed to hack alire and make the `-f` option being taken into account.

It works like a charm :-)

**Comment by mosteo** [comment]
Thanks for the report, Stephane. Probably in this case we should check that the release doesn't exist taking into account only the community index. This is not a trivial change though with our current loading infrastructure.

As for making this an overridable error with `--force`, it can certainly be an interim solution.

**Comment by stcarrez** [comment]
The `--force` option works for that purpose so there is no need to keep this opened.
