### ISSUE TITLE
Platform-independent index loading

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#109]
The old index, despite the apparent plain Ada syntax, was designed to preserve conditional expressions and case statements as-is when loaded into memory. This way, the full index information was preserved until the point where it needed to be resolved for a particular platform (in essence, for resolution of dependencies).

Although this made data structures a bit more complex and memory intensive, it enabled several features/advantages:
- Complete information could be presented to the user (e.g., difference between `alr show` and `alr show --native`)
- When checking out a release for modification, the full information can be preserved in the exported toml file, so the import-export-import cycle is complete, also raising developer awareness of any platform-specific issues.
- When a project is unavailable, the user can ascertain the reason from `alr` output without having to go to the index files (see example below).
- A hypothetical future tool that managed the index in a platform-independent way would have all the information available. This may be needed for the future web interface, for example.

Example output from old index:
```
$ bin/alr show whitakers_words                              
whitakers_words=2017.9.10: William Whitaker's WORDS, a Latin dictionary
Origin: commit 27be95b8a06d7b22c0600c824cf929ab43efcf25 from https://github.com/mk270/whitakers-words.git
Available when: (not (Compiler < Gnat_Fsf_7_3_Or_Newer or Compiler = Gnat_Fsf_7_3_Or_Newer))
```
and currently:
```
whitakers_words=2017.9.10: William Whitaker's WORDS, a Latin dictionary
Origin: commit 27be95b8a06d7b22c0600c824cf929ab43efcf25 from https://github.com/mk270/whitakers-words.git
Available when: False
```

This affects both dependency expressions (that resolve to dependencies) and requisites expressions (that resolve to a boolean).

@pmderodat, this one is my fault because I should have realized from your first patches that you were evaluating the index during loading, and raised the issue sooner. So I would like to tackle it (also I guess I will have an easier time with alr internals).

My idea is not going back to the full boolean expressions, but simply keep the current index case statements during loading. I can simplify/adapt the old structures to the new index syntax at the same time.

Related to #101, depending on what we do about that.

**Comment by pmderodat** [comment]
Hello Alex,

> * When checking out a release for modification, the full information can be preserved in the exported toml file, so the import-export-import cycle is complete, also raising developer awareness of any platform-specific issues.

I don’t understand this: what’s checking out a release for modification? I guess I’ll understand the rest after your answer. :-)

I agree it would be nice to recover this feature. The TOML loader creates its own internal data structure (`Package_Type`, in `Decode_TOML_Package`) and then evaluates it to Alire’s releases types (in `Decode_TOML_Package_As_Releases`).

`Package_Type` contains expressions, i.e. before the evaluation using environment constants, so preserving expressions when creating releases seems doable. Simplifying/adapting the current data structures seems very worthwhile: actually during the development of TOML indexes, I intially tried to produce full expressions, but lost my way in the middle of the generic instantiation nest, and ended up evaluating the expressions myself. I don’t know if reducing complexity there will be doable or the best option, but it’s certainly worth a try. :-)

**Comment by mosteo** [comment]
With the "check out for modification" I mean that if you do an `alr get <project>` with the intent of working in a new release of <project>, the <project>/alire/<project>.toml file contains the same info as the one in the index. But, more generally, the point is that when getting a release you're not getting partial information.

I'll ping you if I get lost in your loading code.
