### ISSUE TITLE
Upgrade MSYS in Windows

### ISSUE THREAD

**Issue by rbatllet** [alire-project/alire#1090]
Is there any command to upgrade MSYS in Windows to the current version which is 20220603?

**Comment by Fabien-Chouteau** [comment]
Hello @rbatllet ,

Right now there are two options:
 - Open an msys2 shell in the Alire msys2 installation `C:\Users\<USER_NAME>\.cache\alire\msys64`  and update from there: `pacman -Syu`
 - Set a new version of msys2 installer in your Alire user configuration (see https://alire.ada.dev/docs/#built-ins-list), delete the current msys2 installation (`C:\Users\<USER_NAME>\.cache\alire\msys64`), and run Alire again to install the new one.
