### ISSUE TITLE
`host-arch` accepts wrongful `bits-64` enum value

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#1093]
See e.g. https://github.com/alire-project/alire-index/blob/038cf57a09a676a59825f93ef2d0056171ed7977/index/gn/gnat_native/gnat_native-12.1.2.toml#L17

Haven't dug yet to see whether this affects all enum types in expressions or only `host-arch`, and why.

**Comment by Fabien-Chouteau** [comment]
It's for all expressions, I thought it was on purpose to allow backwards compatibility.

**Comment by Fabien-Chouteau** [comment]
https://github.com/alire-project/alire/blob/cce020a5078c6158f0c20b12807270b7c32858eb/src/alire/alire-conditional_trees-toml_load.adb#L68

**Comment by mosteo** [comment]
Oh right... This would be caught by `alr publish` and in our server side tests.
