### ISSUE TITLE
alr seems to convert an absolute path to a relative one

### ISSUE THREAD

**Issue by dkm** [alire-project/alire#1100]
Using:
```
$ alr -d pin click  --use ~/something/git/ada-embedded/click/
```
ends up as:

```
[[pins]]
click = { path='../../../../../../../mnt/something/dkm/git/ada-embedded/click' }
```
With `~/something` being a symlink:
```
/home/dkm/something -> /mnt/something/dkm//
```

Not sure this is really expected behavior, but feel free to close it if it is.

This means that if I want to be able to move the directory, I have to manually change the path to an absolute one.

**Comment by mosteo** [comment]
Yes, pins are transformed to relative paths as in general they are more portable.

For your use case, if an absolute path is better, you can edit the manifest by hand and that won't be modified by alr.
