### ISSUE TITLE
Available gnat_external no longer printed by alr toolchain

### ISSUE THREAD

**Issue by onox** [alire-project/alire#1101]
After upgrading from cce020a5 to e9f0ee54 the available gnat_external
disappeared from the results printed by `alr toolchain`.

With cce020a5:

```
CRATE         VERSION STATUS    NOTES
gprbuild      21.0.2  Available
gprbuild      22.0.1  Default
gnat_native   11.2.4  Default
gnat_external 11.2.0  Available Detected at /usr/bin/gnat
```

With e9f0ee54:

```
CRATE       VERSION STATUS    NOTES
gprbuild    21.0.2  Available
gprbuild    22.0.1  Default
gnat_native 11.2.4  Default
```

If I try to run `alr toolchain --select gnat_external` I get an error:

```
error: Release within requested version not found: gnat_external*
error: Use --force to override compatibility checks between installed toolchain components
```

But if I then use `alr toolchain --select`, I can select gnat_external in the wizard and get:

```
CRATE         VERSION STATUS    NOTES                    
gprbuild      21.0.2  Available
gprbuild      22.0.1  Available
gnat_native   11.2.4  Available
gnat_external 11.2.0  Default   Detected at /usr/bin/gnat
```

If I select gnat_native again, then gnat_external disappears from the printed lines again.

Subsequently running `alr toolchain --select gnat_external` works (no longer getting an error):

```
ⓘ Requested crate resolved as gnat_external=11.2.0
ⓘ External tool needs no installation: gnat_external=11.2.0
ⓘ gnat_external=11.2.0 set as default in global configuration.
```

**Comment by mosteo** [comment]
Thanks for the report. The problem will be in e47d239c.

**Comment by mosteo** [comment]
Hi @onox, I was able to reproduce the listing issue but not the error. If you have the time to test https://github.com/alire-project/alire/pull/1104 that would be great.
