### ISSUE TITLE
[Feature request] Install Alire using Homebrew on MacOS

### ISSUE THREAD

**Issue by rbatllet** [alire-project/alire#1109]
Is there any possibility in the short term to install Alire via Homebrew on MacOS ? 

This way we wouldn't have to check if there is a new version all the time and it would be easier to update.

**Comment by Fabien-Chouteau** [comment]
Hi @rbatllet 

This is already discussed in #1031, we are all for it but someone has to take the initiative and do it.
Also one of the blocking point is the lack of GNAT in Homebew.

**Comment by rbatllet** [comment]
@Fabien-Chouteau Another option would be that when Alire is executed and there is a higher version, it displays a message indicating to upgrade to that version.

**Comment by Joebeazelman** [comment]
I stumbled upon a GitHub projecr where someone has already created a person tap for installing Alire along with other tools:

https://github.com/rami3l/homebrew-tap

I am willing to work on it.
