### ISSUE TITLE
-gnateE is not available on GNAT 12 light runtimes

### ISSUE THREAD

**Issue by JeremyGrosser** [alire-project/alire#1118]
Alire: HEAD at commit [92ccefb143c2fce78de1cc377a8bcdfed64549d7](https://github.com/alire-project/alire/commit/92ccefb143c2fce78de1cc377a8bcdfed64549d7) 
Toolchain: gnat_arm_elf 12.1.2
Runtime: light-cortex-m0p

Building with a post-1.2 generated project file, `alr build --development` emits the following warning for every Ada source file:
```
warning: extra exception information (-gnateE) was specified
warning: this capability is not available in this configuration
```

I think we need a way for the runtime to exclude incompatible compile switches.

**Comment by mosteo** [comment]
Thanks for the report. And this will affect every crate in the solution, not just the root one. -_-'

**Comment by Fabien-Chouteau** [comment]
I think the only solution at this point is to ne emit the switch. Alire is not aware of targets nor run-times.
