### ISSUE TITLE
Unset configuration variables in CI

### ISSUE THREAD

**Issue by jquorning** [alire-project/alire#1125]
Some crates fail CI with errors like:
`Configuration variable 'cortex_m.core not set and has no default value.`

Should `alr` have a way to auto-initialise these variables for CI?

At the moment the crates failing to configure are:
```
cortex_m
lvgl_ada
lvgl_ada_simulator
lvgl_ada_examples
minisamd51_example
minisamd51_bsp
microbit_examples
microbit_bsp
nrf5x_hal
```

**Comment by Fabien-Chouteau** [comment]
These crates are not meant to be compiled stand-alone. They require configuration values to be set by the depending crates.

Note that there is the same issue when one tries to "alr with" these crates. Which makes them impossible to with from the command line.

One way out would be to make the default value mandatory. I considered this when I first worked on the crate configuration feature. But sometimes there is no good default, and I want users of the crates to know that they have to pick a value.

**Comment by jquorning** [comment]
Oh, I was concerning the Crate Status on the CI site :-) Here we try to build them stand-alone. In normal use case it is fine with no default value, but in CI testing we could provide some arbitrary values to see what problems might show up during building.
I thought about some switch or alire config variable to tell alr to set the crate variables.

**Comment by mosteo** [comment]
For the CI site, we have a way to provide alternate testing via a `test` action. It would be a matter of providing a testing nested crate and invoke it via the action. I'll try to come up with an example when time permits.
