### ISSUE TITLE
Gitpod ada extension deprecated

### ISSUE THREAD

**Issue by TamaMcGlinn** [alire-project/alire#1133]
I think the Ada extension version mentioned in .gitpod.yml needs a bump.

If I open Alire in gitpod, I see under 'problems': user uploaded extensions are deprecated, and if I click on that, it takes me to .gitpod.yml with a strike through the version hash part:

adacore.ada@22.0.5 _:b56gZDvQ5KBm6u34IBzm1g==_

**Comment by mosteo** [comment]
Should be fixed, thanks for the report, Tama.
