### ISSUE TITLE
Feature request: auto generate env gpr

### ISSUE THREAD

**Issue by TamaMcGlinn** [alire-project/alire#1135]
It would be really useful to be able to generate the [projectname]_env.gpr file automatically by running some alr command. Such a gpr file simply hardcodes the relative path to the gpr files being used; if this file is committed to the repository, it means that the receiving side doesn't need alire to compile the project at all; simply using gprbuild will find all the library gpr files.

(at the moment, for instance, it seems not to be possible to have a gitpod workspace with a working language server inside, because we would need the capability in gitpod to set environment variables for the whole editor. alire_env.gpr is the workaround for alire itself, and this feature would make it easy to apply the same workaround for other alire based projects)

I had a bash script that was halfway there, but the problem turned out to be both sticky _and_ hairy, so I gave up. Do you have something like this, or did you write alr_env.gpr by hand?

**Comment by Fabien-Chouteau** [comment]
> Such a gpr file simply hardcodes the relative path to the gpr files being used;

In theory the generated `<CRATE_NAME_config.gpr>` file could use relative paths to projects of dependencies.
But that won't cover all the cases because not all the crates are using the generated `<CRATE_NAME_config.gpr>` file.

> we would need the capability in gitpod to set environment variables for the whole editor

Seems like a strange limitation, are you sure it is not possible?

Can you run the language server with `alr exec`?

> alire_env.gpr is the workaround for alire itself, and this feature would make it easy to apply the same workaround for other alire based projects)

`alr_env.gpr` is an aggregate project written by hand. There are all sorts of issues when using aggregate projects (in particular with cross compilation) and we don't want to use that for Alire crates.

**Comment by TamaMcGlinn** [comment]
I agree it is a strange limitation, but as far as I can see, it's not possible to set environment variables for the whole gitpod editor. [I have opened an issue for that](https://github.com/gitpod-io/gitpod/issues/11928). Resolving that is probably the best option for gitpod.

Running the language server with alr exec is a good idea, but will require modifying the VSCode plugin, and it seems cumbersome to have to maintain and also load into gitpod this modified version.

Another option is to write an additional VSCode plugin, that detects Alire projects and/or projects with more or less than 1 .gpr file and sets environment variables accordingly and then restarts the language server. Basically [nvim-lsp-gpr-selector](https://github.com/TamaMcGlinn/nvim-lsp-gpr-selector/) but for VSCode.

**Comment by mosteo** [comment]
I think this is being worked out in some alternative way, right Tama? I'm closing but feel free to reopen if I'm mistaken.

**Comment by TamaMcGlinn** [comment]
This would be a lot of work, and shouldn't be necessary. Only alire itself should need such a gpr project, and it has already been written. If anyone finds a need for this, or wants to work on it, they can reopen it.
