### ISSUE TITLE
Documentation for Alire Edit is out of date and incomplete

### ISSUE THREAD

**Issue by Joebeazelman** [alire-project/alire#1137]
I was getting a bunch of VS Code error messages when I realized I didn't correctly configure Alire to launch VSCode using the Alr Edit command.  I couldn't remember the instructions so I typed in:

`alr edit --help`

The help summary is "Start GNATstudio with Alire build environment setup".  This is out of date since Alire now supports launching any IDE or editor.  There's also no discussion on how to setup an alternative to GNATStudio such as VSCode.

**Comment by mosteo** [comment]
Completed in #1586
