### ISSUE TITLE
Crates without project-files

### ISSUE THREAD

**Issue by jquorning** [alire-project/alire#1139]
There seems to be some confusion on what to do with crates without project files like `gprbuild`. `alr get --build` handles this but `alr build` and `alr test` expects the default project file `gprbuild.gpr`

Could a solution be to explicitly declare in the manifest that there are no project files with:
`project-files  = []`

`alr get --build`:
```
% alr --no-tty get --build gprbuild ; echo $?
Note: Skipping build step for binary release gprbuild=22.0.1

gprbuild=22.0.1 successfully retrieved and deployed.
There are no dependencies.
0
```
`alr build`:
```
% alr get gprbuild ; cd gprbuild_* ; alr --no-tty build ; echo $?
...
Note: Building gprbuild/gprbuild.gpr...
gprbuild: project file "/Users/jquorning/Alire/gprbuild_22.0.1_b1220e2b/gprbuild.gpr" not found in .::/Users/jquorning/Alire/gprbuild_22.0.1_b1220e2b
ERROR: Command ["gprbuild", "-s", "-j0", "-p", "-P", "/Users/jquorning/Alire/gprbuild_22.0.1_b1220e2b/gprbuild.gpr"] exited with code 4
ERROR: Compilation failed.
1
```
`alr test`:
```
% alr --no-tty test gprbuild --newest ; echo $?
Starting test run alr_test_1660168396 for Macos Bits_64 Distro_Unknown
PASS: 0 FAIL: 0 SKIP: 0 UNAV: 0 UNRS: 0 CURR: 1/1 gprbuild=22.0.1ERROR: Declared project file not found: gprbuild.gpr
	FAILED
PASS: 0 FAIL: 1 SKIP: 0 UNAV: 0 Done
ERROR: Some releases failed to pass testing
1
```

**Comment by Fabien-Chouteau** [comment]
The `gprbuild` crate is a binary crate that is not supposed to be built. We introduced this as an easy way install the toolchain.
`alr build` should print an message explaining that.

**Comment by mosteo** [comment]
Yes, this should be fixed in `alr test` to attempt a different kind of testing or simply skip build for now.

The current way to work around `alr test` would be to add a test action; this overrides the default `alr test` build. This action can be only in the index manifest; it's not necessary to modify the local manifest in the sources.
