### ISSUE TITLE
'alire build' should not inherit GPR_PROJECT_PATH

### ISSUE THREAD

**Issue by stephe-ada-guru** [alire-project/alire#1147]
I'm working on building Emacs ada-mode and dependencies with Alire. Currently, my build setup defines GPR_PROJECT_PATH in the process used for compilation, and it includes the dependencies. However, when building with Alire, it should only find dependencies via alire.toml; otherwise they will be missing in the release.

**Comment by mosteo** [comment]
This has been intended behavior so for local development a user can provide missing dependencies. Currently, with pins and the ability to set/extend the `GPR_PROJECT_PATH` in a working manifest via `[environment]`, what you suggest could be a safer behavior.

This is an important change in behavior, so I'd like to have more feedback first though. @Fabien-Chouteau what do you think?

**Comment by Fabien-Chouteau** [comment]
Yeah I think the intention was to allow to mix Alire deps with other libraries that way. I don't think we should change the behavior. We could add an option to ignore existing `GPR_PROJECT_PATH` but I am not sure it's worth the effort since it can be done with: `$ GPR_PROJECT_PATH= alr build`.

**Comment by stephe-ada-guru** [comment]
My build setup for Alire does include setting GPR_PROJECT_PATH to empty, so I can live with the current behavior, as long as it is documented.
