### ISSUE TITLE
ada.dev website

### ISSUE THREAD

**Issue by nytpu** [alire-project/alire#1157]
(I opened this issue here because I couldn't find any more appropriate spot for it—e.g. the alire.ada.dev site's repo has issues disabled; and AFAIK there's no Alire mailing list. Feel free to redirect me to an alternate place if necessary.)

I [and several other people](https://hackers.town/@theruran/108867660568286447) recently hypothesized the concept of a hip website for Ada. I believe Alire owns the ada.dev domain—which is currently inactive other than the [alire.ada.dev](https://alire.ada.dev) subdomain AFAICT—and ada.dev would be perfect for a site like this. I believe a landing page that introduces Ada in a friendly way and contains resources on getting started would be a huge benefit to the community.

I imagine most newcomers to Ada (myself included when I started learning it) notice the real… lack of quality of sites. Eventually you find your way to the Ada Reference Manual and learn.adacore.com but there's no one good place leading you to them. For example, this snippet from Reddit comment a few months back:
> [The Rust team have] spent an incredible amount of time on polish…Most of Ada looks quite dated by comparison. While learning the language, I slogged through a bunch of websites that looked like they were made while I was still in elementary or middle school. The community shrugs this off, but it makes the language look very dated and out of touch. It was like walking through a virtual ghost town. Seriously, has no-one discovered [Hugo](https://gohugo.io/) at least?

— https://old.reddit.com/r/ada/comments/t5mlt2/rust_advocates_act_as_if_ada_doesnt_exist/hz6ej6c/

It doesn't have to be a large or ambitious site, it really only needs the following things:
- A landing page with “selling points” for the language and links to the other portions of the site
- A quickstart guide on how to install an Ada toolchain—probably just equivalent to the [Alire quickstart](https://alire.ada.dev/docs/#first-steps), although I think breaking it out onto its own page away from the rest of the Alire docs would be a good idea. Maybe also list Linux/BSD repositories that have working GNAT packages like Arch Linux. 
- Links to learning resources such as [learn.adacore.com](https://learn.adacore.com)
- Links to reference materials and documentation such as the Ada Reference Manual and the [Ada WikiBook](https://en.wikibooks.org/wiki/Ada_Programming)
- Possibly links to popular libraries

Here's some good examples to take inspiration from:
- https://fortran-lang.org/
- https://forth-standard.org/
- https://common-lisp.net/
- https://harelang.org/ (A modern language but a bit more minimalist site if that'd be preferred)

I'd be willing to start building this site (or at the very least contribute if someone else would rather take the lead), but I wanted to gauge your interest first.

**Comment by mosteo** [comment]
Yeah, the archaic websites is a sticking point. Just a fact of life I guess. I hope your initiative succeeds! The [Awesome Ada repo](https://github.com/ohenley/awesome-ada) is also a great resource, I expect it's in your radar already.

As for `ada.dev`, it isn't controlled by Alire. WHOIS is private, so your man in this matter is @Fabien-Chouteau.

I will close this now since there's nothing to do from the Alire camp, but feel free to continue discussing here anything you need.

**Comment by Fabien-Chouteau** [comment]
@nytpu AdaCore owns the `ada.dev` domain.

**Comment by onox** [comment]
I would definitely like to help or even lead to put the current archaic websites to rest. It should have a good, interactive, landing page which makes it easy for the user to explore the language a bit and remove any barriers to get started on the 3 major operating systems. It should also promote and have integration with Alire (for basic usage gprbuild is becoming more of an implementation detail). Alire makes it much easier to build and discover other software written in Ada. Instead of linking, integrate the content of the (A)ARM to give it a modern fresh appearance. Keeping the user on a single website as much as possible makes it easier to promote it to friends or colleagues ("Just go to ada.dev and then click...").

I have spent (professionally) several years building SPAs so I'm familiar with the web ecosystem :slightly_smiling_face: I'm done with academic stuff early next week, so I can build some prototypes then.

I think we should aim to make it a bit more fancy and ambitious than the websites of any of the top 10 trending programming languages.

**Comment by reznikmm** [comment]
I've raised a [related question on reddit](https://www.reddit.com/r/ada/comments/wx9zp1/yet_another_ada_web_site/). I wonder how to let the community own such site to avoid situation that we have with getadanow.com. That site had a good shape while ago, but now it's outdated and community can't change/update it.

**Comment by AJ-Ianozi** [comment]
I registered [getada.dev](https://getada.dev) a while ago with the internet to create something similar to [rustup.rs](https://rustup.rs) and in the meantime I’m just pointing it to Alire’s get started page.

I think it’s worth setting up a landing page that’s similar, and ada.dev may be ideal; I can hold off on my efforts if there is already something in the works. I’d also be happy to help.

**Comment by nytpu** [comment]
@Fabien-Chouteau Ah, okay; I jumped to conclusions considering the user of the domain and there being no public whois info.

@AJ-Ianozi This issue is just a hypothetical, if you already have something in the works then that sounds perfect! I'd keep goin' on that.

**Comment by systems-praxis** [comment]
> @nytpu AdaCore owns the `ada.dev` domain.

@Fabien-Chouteau Can you please elaborate? Your response does not really address the issue. In fact, it sounds dismissive, like [your response re: aarch64 / Raspberry Pi 3/4 runtime system support for GNAT FSF](https://github.com/AdaCore/bb-runtimes/issues/60#issuecomment-1186859381). Is AdaCore business strategy regarding these issues really that critical that they are willing to burn community goodwill for it? Or are you not authorized to speak on their behalf? Perhaps you can show some support and find someone in your organization who can address the FLOSS community's concerns.

**Comment by Fabien-Chouteau** [comment]
> @Fabien-Chouteau Can you please elaborate? Your response does not really address the issue.

@systems-praxis Nytpu was not sure about the ownership of that domain so provided the info. That's it.

I don't see how the rest of your message relates to the topic of this GitHub issue.
Which by the way Alejandro closed because it has not much to do with the Alire project itself.

**Comment by pyjarrett** [comment]
@nytpu I made a website over the weekend that I think hits all of your points: https://ada-lang.io/

Feel free to add to it, especially tutorials/how-tos.

**Comment by nytpu** [comment]
@pyjarrett
Awesome! Looks almost exactly like what I was thinking of.

Although it would be nice if you mentioned *nix distributions that have working GNAT (and other Ada-related) packages available, and then recommend Alire for everyone else. I'll look into adding it, but it might necessitate a bit of reorganization since the installation page is dedicated to Alire

**Comment by pyjarrett** [comment]
@nytpu Building on the lessons learned from Go and Rust, I'm only interested in promoting Alire usage.

One of the huge reasons I almost quit Ada in the beginning was dealing with the large amount of complexity of GPR files.  Alire hides a lot of this complexity and also significantly simplifies toolchain installation and usage.

If there are *nix distributions where Alire releases aren't available, there should be an effort to create packages for these systems.

**Comment by reznikmm** [comment]
Probably keeping get started page simple is better. There are many other
ways to install gnat, but we should firstly mention the simplest one. Alire
is simple and consistent over 3 platforms.

ср, 31 серп. 2022, 04:26 користувач Paul Jarrett ***@***.***>
пише:
