### ISSUE TITLE
Feature Request: Installer

### ISSUE THREAD

**Issue by AJ-Ianozi** [alire-project/alire#1164]
I'm not certain if this is the right spot to put this, but: Is there any interest in an installer/updater for Alire written in Ada?

On *nix systems it could download the proper version of Alire from github and install it in `$HOME/.alire/bin`, optionally adding the value to user's local $PATH.  We could potentially do similar with MacOS.

On Windows it could install Alire to `%USERPROFILE%\.alire\bin` (or Program Files if we wanted to keep going that route) while bringing in msys2 at that time, if needed.

If done correctly, the entire Ada toolchain could be installed with a simple sh script, [similar to what rustup is doing](https://github.com/rust-lang/rustup/blob/master/rustup-init.sh).

I would be happy to try putting something together if there's some interest and something is not already in the works.

**Comment by mosteo** [comment]
A copy/paste shell one-liner would be nice, and simple enough given our release artifacts, at least for Linux/macOS. In fact, there used to be one in the very beginning.

I would prefer to be asked about where to put `alr`, as I already have my local `bin` folder for this kind of things. Obviously offering a sensible default would be okay.

Also, for Linux at least, there's the autocomplete script in [scripts/alr-completion.bash](https://github.com/alire-project/alire/blob/master/scripts/alr-completion.bash) that might make sense to set up too.

**Comment by AJ-Ianozi** [comment]
I think a prompt to install the binary is reasonable (I also have alire in a local `bin` folder). Do you happen to still have the installation script for alire? 

Edit: github is so confusing at times, I think I just closed this issue! But it’s fine, I’m going to mess with things this week and see way I can look at.

**Comment by mosteo** [comment]
The old installer is buried in old revisions (e.g. in ecbffa22, in alire/alr-bootstrap.sh) but since that requires a working Ada toolchain and it builds from sources, that's not anymore the way to go.
