### ISSUE TITLE
GNAT options from withed crate issue.

### ISSUE THREAD

**Issue by Blady-Com** [alire-project/alire#1182]
In a withed crate, -gnatW8 is needed to read the source code but not needed for the main program thus I don't want to add this option which is not relevant at main level.
How to do it so?
(the option -gnatW8 in the withed crate GPR seems not be considered with alr 1.2.1)

**Comment by stephe-ada-guru** [comment]
Specifying -gnatW8 in the gpr file for the withed crate should work; how are you specifying it?

**Comment by Blady-Com** [comment]
Here it is in the withed crate: [lib_uxstrings1.gpr](https://github.com/Blady-Com/UXStrings/blob/master/lib_uxstrings1.gpr#L39)

**Comment by Fabien-Chouteau** [comment]
Hi @Blady-Com I am going to close this issue as this is outside the scope of Alire.
