### ISSUE TITLE
Generated Library_Dir question.

### ISSUE THREAD

**Issue by Blady-Com** [alire-project/alire#1184]
In generated library crate GPR file, Object_Dir is depending of Build_Profile but not Library_Dir:
```
   for Object_Dir use "obj/" & Crate_Config.Build_Profile;
   for Library_Dir use "lib";
```
Is it an oversight?

**Comment by Fabien-Chouteau** [comment]
The `lib` dir is a standard installation folder, we cannot have different names for it.

**Comment by Blady-Com** [comment]
Well, I'm puzzled when I noticed other practices as for instance Adacore adds Library_Kind in [gnatcoll_sqlite.gpr](https://github.com/AdaCore/gnatcoll-db/blob/master/sqlite/gnatcoll_sqlite.gpr#L36):
`for Library_Dir     use "lib/" & Project'Library_Kind;`
What is the rationale?

**Comment by Fabien-Chouteau** [comment]
Honestly I don't know. It's possible that `gprinstall` will put everything in `lib/` in the end...
