### ISSUE TITLE
Remove cross-compilers from assistant

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#1211]
Since cross-compiling crates usually include the dependency on the necessary x-compiler, we can reduce confusion to first-time users if only native compilers are listed.

**Comment by RREE** [comment]
Perhaps it might be useful to have an option that also lists the cross-compilers (e.g. `--list-x`). I got used to run `alr toolchain --select` to see which compilers and cross-compilers are available, select the newest AVR or ARM compilers and run it again to set the default compiler back to the native compiler.

**Comment by Fabien-Chouteau** [comment]
You can use `alr search gnat_` instead ;)

**Comment by mosteo** [comment]
`alr` defaults to the native toolchain in the interactive assistant, and just offers to confirm the native toolchain on first run without showing the whole list. I don't think we need to do more on this front right now.
