### ISSUE TITLE
publish --tar bad error message

### ISSUE THREAD

**Issue by stephe-ada-guru** [alire-project/alire#1214]
Using alr version 1.2.1. On Windows 10, in Windows PowerShell, with msys2 in Path, in an alire workspace:

alr publish --tar
ERROR: failed precondition from alire-roots-optional.ads:43
ERROR: alr encountered an unexpected error, re-run with -d for details.

Adding -d gives more details:
stderr: Invalid TOML contents in file
invalid token at alire.toml:5:12
stderr: ALIRE.CHECKED_ERROR
stderr: Invalid TOML contents in file
invalid token at alire.toml:5:12
stderr: raised ALIRE.CHECKED_ERROR : alire-stored-error:1
[C:\home\stephe\bin\alr.exe]
0xdc8cdb Semantic_Versioning.Basic.At_Least at alire.adb:251
0xd008d6 Semantic_Versioning.Basic.At_Least at alire-toml_load.adb:227
0xbdad47 Semantic_Versioning.Basic.At_Least at alire-releases.adb:890
0xbf1fe5 Semantic_Versioning.Basic.At_Least at alire-roots-optional.adb:54
0xbe3c04 Semantic_Versioning.Basic.At_Least at alire-root.adb:17
0xb64a42 Semantic_Versioning.Basic.At_Least at alire-publish.adb:87
0xb5ecaf Semantic_Versioning.Basic.At_Least at alire-publish.adb:913
0x49f2a3 Semantic_Versioning.Basic.At_Least at alr-commands-publish.adb:49
0x51c0a3 Semantic_Versioning.Basic.At_Least at clic-subcommand-instance.adb:742
0x528a27 Semantic_Versioning.Basic.At_Least at alr-commands.adb:492
0x401761 Alr.Main at alr-main.adb:10
0x404bd6 Main at b__alr-main.adb:2130
0x401423 __tmainCRTStartup at ???
0x40113b mainCRTStartup at ???
[C:\WINDOWS\System32\KERNEL32.DLL]
0x7ff886b57032
[C:\WINDOWS\SYSTEM32\ntdll.dll]
0x7ff888a6269f

Apparently there is a bad entry in the alire.toml; attached (as alire.toml.txt to satisfy github)
[alire.toml.txt](https://github.com/alire-project/alire/files/9738932/alire.toml.txt)

This should give a more friendly error message.

The problem on this line is missing string quotes. There are also several other errors; after several rounds of "alr -d", alr publish --tar finally moved to the next step.

**Comment by mosteo** [comment]
Thanks for the report, indeed this kind of situation should not result in unhandled  exceptions.
