### ISSUE TITLE
publish --tar on Debian fails in step 5

### ISSUE THREAD

**Issue by stephe-ada-guru** [alire-project/alire#1218]
"alr publish --tar" on Debian fails in step 5. The error message is:

Publishing assistant: step 5 of 8: Deploy sources
################################################################################################################# 100.0%
✓ Computed hash: sha256:d5a89e26beae0bc03ad18a0b0d1d3d75f87c32047879d25da11970cb5c4662a3
✓ Computed hash: sha512:42e53d96e5961e95b7a984d9c9778a1d3bd8ee0c87b8b3b515fa31f67c2d073c8565afc2f4b962c43668c4efa1e478da9bb0ecffa79479c7e880731bc4c55765
warn: tar failed: Command ["tar", "-x", "-f", "/Projects/org.wisitoken/alire/tmp/alr-xigd.tmp/wisitoken-4.0.0.tgz"] exited with code 2 and output: /usr/bin/tar: This does not look like a tar archive\n\ngzip: stdin: not in gzip format\n/usr/bin/tar: Child returned status 1\n/usr/bin/tar: Error is not recoverable: exiting now
error: Command ["tar", "-x", "-f", "/Projects/org.wisitoken/alire/tmp/alr-xigd.tmp/wisitoken-4.0.0.tgz"] exited with code 2 and output: /usr/bin/tar: This does not look like a tar archive\n\ngzip: stdin: not in gzip format\n/usr/bin/tar: Child returned status 1\n/usr/bin/tar: Error is not recoverable: exiting now

I've verified that the file on the remote host (https://download.savannah.nongnu.org/releases/ada-mode/wisitoken-4.0.0.tgz) is in tar format, and is in fact the same as the file that was uploaded from ./alire/archives. I'm guessing alr downloaded it, and is attempting to untar it to verify that it's a good archive? 

The directory alire/tmp/alr-xigd.tmp is deleted after alr returns. I guess I'd have to run alr under gdb to figure out what's going on?

This process worked for the stephes_ada_library crate.

**Comment by stephe-ada-guru** [comment]
I'm getting the same failure on another crate, with the file https://download.savannah.nongnu.org/releases/ada-mode/emacs_wisi-4.1.0-beta.tgz

I noticed that when I try to download the file via Firefox "save link as", it is corrupted (actually, it's an html file saying "404 not found"), but when I download it with scp, it's fine. So maybe there's something wrong on the savannah end.

**Comment by stephe-ada-guru** [comment]
After several hours, the error went away. So this was a problem with the git host. Sorry for the noise.

**Comment by stephe-ada-guru** [comment]
Now this error is back, with file https://download.savannah.nongnu.org/releases/ada-mode/emacs_gpr_query-1.0.0.tgz
Retrieving it with wget works fine, but alr publish still says tar thinks it's not in gzip format.

**Comment by mosteo** [comment]
We use `curl` instead of `wget`, but I just checked and it downloads properly the file. Could you attach the log with `-vv -d` global switches?

**Comment by stephe-ada-guru** [comment]
I just read the alire sources, and found that this just does curl and tar xf, which (as you say), works fine when I run it from a shell. So I ran "alr publish --tar" again, and this time it got farther (it's now complaining about GNATCOLL_ALIRE_PREFIX - maybe another issue).

So savannah is just flaky sometimes, and the solution is to try again later. Sigh.

**Comment by stephe-ada-guru** [comment]
It appears part of the problem is that savannah redirects downloads to a mirror; apparently it takes a while for the mirror(s) to catch up.
