### ISSUE TITLE
"alr exec" show error messages from command

### ISSUE THREAD

**Issue by stephe-ada-guru** [alire-project/alire#1227]
I'm trying to run 

alr exec "gprinstall -f -p -P emacs_gpr_query.gpr --install-name=emacs_gpr_query $1"

from a shell script that builds and installs a crate. This currently fails with:

ERROR: Command ["gprinstall -f -p -P emacs_gpr_query.gpr --install-name=emacs_gpr_query "] exited with code -1

This is not very helpful; I'd like to see the messages that gprinstall outputs on standard error.

**Comment by mosteo** [comment]
`alr` does not hide command output by default (try e.g. `alr exec -- ls`), it only dims it if using an ANSI tty, so I'm not sure what's going on.

Maybe try without the quotes and with `--` to mark the beginning of your command? I guess it may be that the quoted string is used as the whole exec name.

**Comment by Fabien-Chouteau** [comment]
Yes the problem are the quotes. You are try to run a executable called: `gprinstall -f -p -P emacs_gpr_query.gpr --install-name=emacs_gpr_query` ^^

Try again with: `alr exec -- gprinstall -f -p -P emacs_gpr_query.gpr --install-name=emacs_gpr_query $1`

**Comment by stephe-ada-guru** [comment]
The double quotes was the problem. I missed the `--` in the help. Sorry for the noise.
