### ISSUE TITLE
use hyphens instead of underscores

### ISSUE THREAD

**Issue by reznikmm** [alire-project/alire#1230]
I think USAGE output should be changed. See:

```
$ alr action --help
SUMMARY
   List or manually trigger action hooks

USAGE
   alr action [options] [post_fetch|pre_build|post_build|test]

$ alr action post_fetch
error: TOML keys should use hyphens instead of underscores, but found key: post_fetch
```
This command runs fine, however:

    $ alr action post-fetch

**Comment by mosteo** [comment]
Right. I hate that we aren't using underscores consistently everywhere like in Ada.

**Comment by 0rzech** [comment]
IMHO, hyphens are more comfortable in CLI and are more prevalent. YMMV, of course. 😉

**Comment by Joebeazelman** [comment]
Alire incorrectly reports "TOML Keys should use hyphens" error if you accidentally leave off the table tag, for instance,  `configuration.values`:

```
[configuration.values]
my_hal.Use_Startup = false
my_hal.Interrupts="bb_runtimes"
```

Spent too much time tracking this issue. The error should be something like "unknown key, are you missing a table tag? If not, keys at the root level cannot contain underscores."

**Comment by Fabien-Chouteau** [comment]
The code you provided gives me:
```
error: Unknown configuration variable 'my_hal.interrupts'
```

Can you provide a full reproducer?

**Comment by Joebeazelman** [comment]
Do you need the toml file? Also what version are you running?

**Comment by Fabien-Chouteau** [comment]
> Do you need the toml file?

Yes please, and all the files necessary to reproduce the error.

> Also what version are you running?

What matters here is the version you are running.

**Comment by Joebeazelman** [comment]
I'm running version 2.0.1.  In the code snippet below, note the table name has been commented out. When I run `alr build` in the workspace, I get the following error:

```
error: Cannot continue without a workspace:
error:    Loading release from manifest: alire.toml:
error:    Failed to load alire.toml:
error:    Loading release from manifest: alire.toml:
error:    TOML keys should use hyphens instead of underscores, but found key: rp2040_hal
```



### Toml file
```
name = "rp_pico_2040"
description = "RP2040 g-coder"
version = "0.1.0-dev"

authors = ["Joe Beazelman"]
maintainers = ["Joe Beazelman <joebeazelman@gmail.com>"]
maintainers-logins = ["joebeazelman"]

executables = ["rp_pico_2040"]

#[configuration.values]
rp2040_hal.Use_Startup = false
rp2040_hal.Interrupts="bb_runtimes"

[[depends-on]]
pico_bsp = "^2.0.0"

[[pins]]
pico_bsp = { path='../../deps/pico_bsp' }
usb_embedded = { path='../../deps/usb_embedded' }
rp2040_hal = { path='../../deps/rp2040_hal' }
```

**Comment by JeremyGrosser** [comment]
`#[configuration.values]`
I don't think that's supposed to be commented out. Remove the `#`

**Comment by mosteo** [comment]
@Joebeazelman, could you please open a new issue to track this separately?
