### ISSUE TITLE
'alr get ada_language_server' fails if gnat 12 is not default toolchain

### ISSUE THREAD

**Issue by stephe-ada-guru** [alire-project/alire#1233]
I'm trying to install the latest ada_language_server:

$ alr get ada_language_server=23
⚠ Complete solution not found after 5 seconds.
ⓘ The best incomplete solution yet is:
                                                                
   RELEASE                 DEPENDENCY                                        
   (none)                  gnat((>=12 & <=2000) & (/=2020)) & (>=11) (hinted)
   gnatcoll=23.0.0         gnatcoll((23.0.0) & (^23)) & (~23.0.0) (solved)   
   ...

The gnat dependency is not resolved, even though gnat 12 is available:
$ alr toolchain 
CRATE         VERSION  STATUS    NOTES                               
gprbuild      21.0.2   Available                                     
gprbuild      22.0.1   Available                                     
gprbuild      2022.0.0 Available Provided by system package: gprbuild
gnat_native   11.2.3   Available                                     
gnat_native   12.1.2   Available                                     
gnat_external 11.3.0   Default   Detected at /usr/bin/gnat           

Since I've selected gnat_external 11.3 as the default, perhaps it is ok that ada_language_server cannot be installed. But in that case, the error message should be much clearer. Currently, it just keeps asking for more time to find a solution, but it will never succeed. Perhaps the error message could be:

"The default toolchain gnat_external 11.3.0 does not satisfy the ada_language_server gnat dependency. To resolve this, select a different toolchain".

I'd prefer alr to offer to use gnat 12 for just this crate, or perhaps an option to specify that.

**Comment by mosteo** [comment]
The selected compiler should not prevent the solver from finding the available proper one and use it only for `ada_language_server`. I will look into reproducing this.

**Comment by mosteo** [comment]
Now I'm thinking that there may be some extra logic involved when an external compiled is selected. If you feel like poking at this, you may try to unselect it (select either none one of the native ones, not necessarily the 12.1 one) and report what happens.

**Comment by mosteo** [comment]
I just checked that, and indeed the problem is `gnat_external` being explicitly selected. So this indeed merits some improvements.
