### ISSUE TITLE
Update README of the testsuite

### ISSUE THREAD

**Issue by 0rzech** [alire-project/alire#1245]
Python 2 reached its EOL over 2 years ago and e3-testsuite supports Python 3.9 and 3.10.

I could rewrite the scripts to Py3 - unless there's some hardcore obstacle overshadowing my knowledge. 😉

**Comment by mosteo** [comment]
Our test suite is running on Python3 since long ago. Did you see something pointing to the contrary?

(Closing unless evidence for something to fix arises.)

**Comment by 0rzech** [comment]
> Did you see something pointing to the contrary?

@mosteo Yes, the [README](https://github.com/alire-project/alire/blob/2d8fab44939cfc2b32bc0693ed75a6f5141b3252/testsuite/README.md). 😉

**Comment by mosteo** [comment]
Allright, I see, thanks for the heads-up!
