### ISSUE TITLE
Fix the author check for submitted crates

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#1246]
The JS TOML parser is choking on valid TOML for some reason, making some proper submissions seem failed.

**Comment by Fabien-Chouteau** [comment]
We should move those checks into the Alire program itself in my opinion. 

Maybe in the `alr dev` command.

**Comment by mosteo** [comment]
Yes, the only reason for not doing that was to have a faster check, but with the stable release action and assuming I manage to get caching in place, it should be almost as fast.

And the rest of checks are much slower anyway.

**Comment by mosteo** [comment]
Implemented in https://github.com/alire-project/alire-index/pull/808
