### ISSUE TITLE
Error parsing community index

### ISSUE THREAD

**Issue by Jkillelea** [alire-project/alire#1248]
Building alire off of the latest master fails with the following error:

```
error: Invalid TOML contents in file:
error:    invalid UTF-8 encoding at /home/jacob/.config/alire/indexes/community/repo/index/ad/ada_fuse/ada_fuse-1.0.1.toml:8:20
```

**Comment by mosteo** [comment]
Could you please double-check that you have updated the git submodules before building?

**Comment by Jkillelea** [comment]
Doing a fresh clone with `git clone --recursive` seems to have fixed things, thanks.
