### ISSUE TITLE
`alr search` should include descriptions

### ISSUE THREAD

**Issue by manthonyaiello** [alire-project/alire#1250]
I wanted to find how to install SPARK using Alire, so, after failing with `alr get spark`, I tried `alr search spark`. This produced two hits - neither of which are actually the SPARK toolchain - even though `gnatprove` has, in its description, "Automatic formal verification of SPARK code".

I suggest that it would be helpful if `alr search` included results from descriptions. (Given that the help says "Search a string in release names and properties", I'm surprised that it does not do so, currently.)

**Comment by mosteo** [comment]
This is actually accomplished with `alr search --property spark` (for any field in the manifest) or `alr search --crates spark` (for descriptions only). By default the lookup is in names only, although I see how the short help text may be misleading.

**Comment by Fabien-Chouteau** [comment]
I agree with Tony here that this is not a helpful result. I think the default should look it names, descriptions and tags.

**Comment by stephe-ada-guru** [comment]
@Fabien-Chouteau +1

**Comment by mosteo** [comment]
Alright, reopening.
