### ISSUE TITLE
alr index reports the most frustrating error message: "Not a readable directory"

### ISSUE THREAD

**Issue by stephe-ada-guru** [alire-project/alire#1251]
Running on Windows:

alr -v index --add git@github.com:stephe-ada-guru/alire-index.git#stephe-patches --name stephepatches --before community

-> Using default value for configuration 'distribution.disable_detection': 'FALSE'
-> Found 1 indexes
ERROR: Not a readable directory
-> alr index unsuccessful

_which_ directory? the program knows perfectly well what directory it is trying to read; include it in the error message!

Happens both in an Alire workspace and out.

**Comment by stephe-ada-guru** [comment]
I tried running alr under the debugger. I compiled it with --development, so assertions are enabled. Now it's raising Assertion_Error in Alire.Config.Edit.Set_Path in the main elaboration code.  So I did not find the code that reported the frustrating error message.

Platform.Folders.Config is returning "C:\home\stephe\.config\alire" because that's where HOME is, when I'm running in a mingw32 shell. However, I first ran alr in a PowerShell, where HOME is either not defined or is c:\Users\Stephe, so it setup alire config in c:\Users\Stephe\.config\alire, and C:\home\stephe\.config\alire doesn't exist.

And yet when I run "alr index" (the non-assertions build) with HOME=c:/home/stephe, it reports:

 NAME      URL                                                           PATH                                                
1 community git+https://github.com/alire-project/alire-index#stable-1.2.1 C:\Users\Stephe\.config\alire\indexes\community\repo

Very confusing. Apparently with assertions disabled, it falls back to the Windows default home?

I'll delete the c:\Users\Stephe\.config\alire, and try to start over, always with HOME set properly.

**Comment by mosteo** [comment]
The lacking error message is at `alire-index_on_disk.adb:176` (in master). You can add some log output, but I expect it to be the local path to which the checkout is being attempted.

There are some other similarly improvable errors close by, so filing this one for enhancement.

**Comment by stephe-ada-guru** [comment]
Well that didn't work. alr toolchain --select ended up creating c:\Users\Stephe\.config\alire, even though HOME pointed somewhere else.

Setting ALR_CONFIG=c:/home/stephe/.config/alire makes 'alr toolchain' use that directory.  So I'll use that as a workaround on Windows for now.

Something is not using HOME consistently. Hmm. Maybe because it's "/home/stephe"  instead of "c:/home/stephe"? Nope, that did not help.

Running 'alr toolchain' with the assertions enabled build raises the assertion error, before it tries to install the default config. So that's not consistent either.

**Comment by stephe-ada-guru** [comment]
Setting ALR_CONFIG did not solve the original problem with "alr index --add ...". More debugging later.

**Comment by stephe-ada-guru** [comment]
The assertion failure is from the Dynamic _Predicate on type Absolute_Path. That calls Alire.Check_Absolute_Path. The version compiled is in os_linux, but I'm on Windows! So the alr environment is wrong for this build. 

That's because there are several settings of "*OS" in the various *.gpr; alr_env.gpr is not with'd by any other gpr. so they all end up as "unix". I'll submit a separate issue on this.

**Comment by stephe-ada-guru** [comment]
After using the recommended build procedure for alr (issue 1255), I managed to get a better error message (patch attached):  
$ c:/Projects/Alire/alire-main/bin/alr.exe index --add git@github.com:stephe-ada-guru/alire-index.git#stephe-patches --name stephepatches --before community
ERROR: 'git@github.com:stephe-ada-guru\alire-index.git#stephe-patches' is not a readable directory

"alr index --help" does not say what the url argument should point to; I assumed this would work. 

Ah; I changed the url to use https instead of git@github:

$ c:/Projects/Alire/alire-main/bin/alr.exe index --add https://github.com/stephe-ada-guru/alire-index.git#stephe-patches --name stephepatches --before community
ERROR: HTTP/HTTPS URLs are not valid index origins. You may want git+https://github.com/stephe-ada-guru/alire-index.git#stephe-patches instead.

One more try:

$ c:/Projects/Alire/alire-main/bin/alr.exe index --add git+https://github.com/stephe-ada-guru/alire-index.git#stephe-patches --name stephepatches --before community

That seems to have worked. So this issue is a request for three things:

1) Include the directory in the "Not a readable directory" error message.
2) A similar error message about the url scheme when given git@github:user (and use "scheme", not "origin"). Or make git@github work; then I can use that workspace to commit changes.
3) In "alr index --help", a description of what the url argument should be. Perhaps:

The url should use the git+https or file: scheme, and point to a git repository containing the index.

[error_message.diff.txt](https://github.com/alire-project/alire/files/10136049/error_message.diff.txt)

**Comment by stephe-ada-guru** [comment]
After using the recommended build procedure for alr (issue 1255), I managed to get a better error message (patch attached):  
$ c:/Projects/Alire/alire-main/bin/alr.exe index --add git@github.com:stephe-ada-guru/alire-index.git#stephe-patches --name stephepatches --before community
ERROR: 'git@github.com:stephe-ada-guru\alire-index.git#stephe-patches' is not a readable directory

"alr index --help" does not say what the url argument should point to; I assumed this would work. 

Ah; I changed the url to use https instead of git@github:

$ c:/Projects/Alire/alire-main/bin/alr.exe index --add https://github.com/stephe-ada-guru/alire-index.git#stephe-patches --name stephepatches --before community
ERROR: HTTP/HTTPS URLs are not valid index origins. You may want git+https://github.com/stephe-ada-guru/alire-index.git#stephe-patches instead.

One more try:

$ c:/Projects/Alire/alire-main/bin/alr.exe index --add git+https://github.com/stephe-ada-guru/alire-index.git#stephe-patches --name stephepatches --before community

That seems to have worked. So this issue is a request for three things:

1) Include the directory in the "Not a readable directory" error message.
2) A similar error message about the url scheme when given git@github:user (and use "scheme", not "origin"). Or make git@github work; then I can use that workspace to commit changes.
3) In "alr index --help", a description of what the url argument should be. Perhaps:

The url should use the git+https or file: scheme, and point to a git repository containing the index.

[error_message.diff.txt](https://github.com/alire-project/alire/files/10136049/error_message.diff.txt)

**Comment by Fabien-Chouteau** [comment]
This error message was improved by #1523.
