### ISSUE TITLE
Output when building from `emacs` contains escape codes

### ISSUE THREAD

**Issue by jquorning** [alire-project/alire#1256]
I suggest that `alr` should not emit escape codes as default, but turn on colours etc only when instructed. Essentially what I am trying to say is to have a shell script front-end. RFC?

This is output when building from emacs:

```
-*- mode: compilation; default-directory: "~/GitHub/jquorning/hello/src/" -*-
Compilation started at Thu Dec  1 19:01:59

alr build
^[[36m^[[1mⓘ^[[39m^[[22m Building ^[[1mhello^[[22m/^[[35m^[[1mhello.gpr^[[39m^[[22m...
^[[2mCompile
   [Ada]          hello.adb
Bind
   [gprbind]      hello.bexch
   [Ada]          hello.ali
Link
   [link]         hello.adb
^[[22mBuild finished successfully in ^[[1m1.16^[[22m seconds.


Compilation finished at Thu Dec  1 19:02:00
```

**Comment by mosteo** [comment]
For scripting, you should use the `-n --no-tty` switches.

It's true that we're not attempting to detect the terminal ANSI capabilities, just that there is a connected terminal.

We might try to better detect if the terminal is ANSI capable, but I suspect it won't be easy to do portably.

**Comment by jquorning** [comment]
@mosteo; A bold suggestion would be to have two versions of `alr`; `alr-pro`, and `alr-newbee`; where the pro is the lean, simple, no-color, non-interactive. The newbee version is the one with all bells and whistles; colours and the like.

I know that my contributions are minor; but I keep thinking I should suggest a discussion of a `alr-2.0`..?

**Comment by mgrojo** [comment]
Emacs sets the `TERM` variable to `dumb` when running a command under <kbd>M-!</kbd> or <kbd>M-x compile</kbd>. It would make sense to honour that environment variable and automatically switch to `--no-color`, or `--no-tty` (I don't know where these two differ).
