### ISSUE TITLE
Uninstalling dependency does not remove dependency from gpr file in config folder

### ISSUE THREAD

**Issue by bracke** [alire-project/alire#1261]
Alire adds some with's to the gpr file in the config folder when installing a dependency. When uninstalling the same dependency  Alire does not remove them.

Recipe:

alr get hello
cd hello_1.0.2_5715870b
alr with adayaml
alr with --del adayaml
alr build

Results in:

hello_config.gpr:3:06: imported project file "yaml-utils.gpr" not found
hello_config.gpr:3:06: imported by "/Users/bent/Projects/Ada/h/hello_1.0.2_5715870b/config/hello_config.gpr"
hello_config.gpr:3:06: imported by "/Users/bent/Projects/Ada/h/hello_1.0.2_5715870b/hello.gpr"
hello_config.gpr:4:06: imported project file "yaml.gpr" not found
hello_config.gpr:4:06: imported by "/Users/bent/Projects/Ada/h/hello_1.0.2_5715870b/config/hello_config.gpr"
hello_config.gpr:4:06: imported by "/Users/bent/Projects/Ada/h/hello_1.0.2_5715870b/hello.gpr"
gprbuild: "/Users/bent/Projects/Ada/h/hello_1.0.2_5715870b/hello.gpr" processing failed
error: Command ["gprbuild", "-s", "-j0", "-p", "-P", "/Users/bent/Projects/Ada/h/hello_1.0.2_5715870b/hello.gpr"] exited with code 4
error: Compilation failed.

Removing those lines from the gpr file fixes the problem.

kind regards
Bent Bracke

**Comment by Fabien-Chouteau** [comment]
@bracke until we fix this, you can add run an `$ alr update` before the build and everything should work fine.

**Comment by bracke** [comment]
@Fabien-Chouteau Can confirm - that fixes the problem.

**Comment by mosteo** [comment]
This is no longer an issue in the master branch.
