### ISSUE TITLE
Add a way to specify the alr to test in testsuite

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#1268]
See related #1262

**Comment by 0rzech** [comment]
Does such need arise often? Tests are rather bound to code revisions.

Not sure about Windows, but on Linux and MacOS running
```sh
PATH="${HOME}/path/to/alire/bin:${PATH}" ./run.py
```
does the job, should one need to test another version of `alr`.

**Comment by mosteo** [comment]
> Does such need arise often?

I don't think so. Probably over-zealousness on our part.

**Comment by 0rzech** [comment]
> I don't think so. Probably over-zealousness on our part.

I appreciate your honesty! 😄

**Comment by 0rzech** [comment]
> I don't think so. Probably over-zealousness on our part.

I appreciate your honesty! :smile:
