### ISSUE TITLE
External dependency indicator is confusing

### ISSUE THREAD

**Issue by Lucretia** [alire-project/alire#1270]
Hi,

I'm just proposing to change X to D as it makes more sense. I looked at SDLAda and saw the X and thought it meant something else, like it wasn't building for some reason.

I would also advise changing U to P also.

These two changes would make these flags consistent with the other two.

**Comment by mosteo** [comment]
You mean in the `alr search` output?

**Comment by Lucretia** [comment]
Yes

```
$ alr search sdla
NAME    STATUS  VERSION  DESCRIPTION                 NOTES                            
sdlada    X     2.5.4-1  Ada 2012 bindings to SDL 2       
```

This just looks like "doesn't build" or something similar.

**Comment by mosteo** [comment]
OK, I see how these can make more sense.

**Comment by Fabien-Chouteau** [comment]
The `X` flag means "the release has dependencies that cannot be resolved". We could change it to a red `R`.

**Comment by mosteo** [comment]
In the end the explanation is at the bottom of the `alr search`, and I don't want to break any existing scripts that could rely on the current output. If we rework the search output at some point it would be a better time.
