### ISSUE TITLE
An invalid character in my toml file triggered a discriminant check failed error

### ISSUE THREAD

**Issue by Joebeazelman** [alire-project/alire#1274]
Instead of giving me a parsing error, putting  an errant character at the end of my file gave me this error:

toml-generic\_parse.adb:393 discriminant check failed

I thought you should know about it since it looks like a dynamic type checking error which shouldn't happen.

**Comment by mosteo** [comment]
Would you have a reproducer at hand? Or do you remember which character and in which manifest entry it was?

**Comment by Joebeazelman** [comment]
I don't remember unfortunately.  I think I had a capital B at the end of the file.

**Comment by simonjwright** [comment]
Managed to reproduce by adding a trailing alphanumeric as the last character in a random `alire.toml`, without a following newline. Adding the newline results in the proper `invalid syntax at alire.toml:19:1`.

**Comment by mosteo** [comment]
Given that the reported error happens inside the ada-toml library, I think this issue should better be filed in the upstream project: https://github.com/pmderodat/ada-toml/issues

Closing this one.
