### ISSUE TITLE
Don't ask if user wants to proceed if there are no changes

### ISSUE THREAD

**Issue by RREE** [alire-project/alire#1278]
I ran `alr update` without changing the `alire.toml` file. The question, if the user wants to proceed is not needed then and should be skipped.
```
❯ alr update

Changes to dependency solution:

   No changes between former and new solution.

Do you want to proceed?
[Y] Yes  [N] No  (default is Yes)
Using default: Yes
```

**Comment by mosteo** [comment]
Right, this is an old nuisance which I thought was already fixed. We are indeed doing the check but somehow an equality operation in a somewhat complex type is reporting differences where there (afaics) aren't; might be related to discriminants and unused fields.
