### ISSUE TITLE
alire.ada.dev: add link to download Alire for other systems

### ISSUE THREAD

**Issue by mgrojo** [alire-project/alire#1279]
It is a good practice, when you provide a specific download link for your OS, to include also a less highlighted link to download for any other system.

Currently, alire.ada.dev only includes a "Download Alire" | "for _your OS_". This may confound new users, who actually may need Alire for other OS, to think that it is only available for the OS running the browser.

See real user experience test: https://groups.google.com/g/comp.lang.ada/c/xKXW0UVUaO8/m/3KYU6t_nBwAJ

**Comment by mgrojo** [comment]
I've just seen https://github.com/alire-project/alire.ada.dev/pull/22

One easy solution is to restore the original "Install Alire" button as "Install Alire" | "for other systems", with the same target as before, as the second button in a row of three.

**Comment by Fabien-Chouteau** [comment]
I added this: https://github.com/alire-project/alire.ada.dev/pull/25
