### ISSUE TITLE
How to release crate despite known issues?

### ISSUE THREAD

**Issue by pjljvandelaar** [alire-project/alire#1286]
Dear Alire developers,

I would like to release a new version of my crates.
However, I experience problems due to known, yet not solved issues.
In particular,
* https://github.com/AdaCore/libadalang/issues/949
   prevents running my tests on windows.
   Unfortunately, initially the latest version of gnat-coll is installed by alire, 
   and despite constraining the gnat-coll version, the error doesn't go away.
* https://github.com/alire-project/alire/issues/1283
   prevents having my crate successfully build remote.

Are there work-arounds known for these issues?

Thanks in advance,
     Pierre

**Comment by mosteo** [comment]
No known workaround since the startup sequence is hardcoded in our testing workflows.

I will try to solve these issues today. I had a huge email backlog from the holidays period but I expect to be fully functional very soon.

**Comment by pjljvandelaar** [comment]
Some problems are not solved, but I was able to release.
Therefore, I close the issue.
