### ISSUE TITLE
Suppress warnings when using printenv --unix

### ISSUE THREAD

**Issue by jklmnn** [alire-project/alire#1294]
When running `alr` e.g. with `update` a warning appears when an old index is still in use:
```
$ alr update         
⚠ Index 'als' version (1.2.0) is older than the newest supported by alr (1.2.1)
⚠ You can disable this warning with configuration key 'warning.old_index'
ⓘ If you experience any problems loading this index, you may need to reset the community index with 'alr index --reset-community'. Note that this operation will delete any local changes to the community index.
```

That is fine so far. However this warning is also printed to stdout when using `alr printenv` I think it should at least be suppressed when using `printenv` with `--unix`, `--powershell` or `--wincmd`. These flags are usually used to be parsed by a shell environment, e.g. with `eval $(alr printenv --unix)`, however the printed warning immediately causes an error and the environment is not applied.

I see that using `warning.old_index` is a workaround however I think it's useful to have this warning enabled with regular command without breaking the environment.

**Comment by mgrojo** [comment]
The good-Unix-citizen solution would be to always print those warnings and errors in the error output, then `eval` would not see the warning text.

```shell
$ echo Hola $(ls Mundo)
ls: cannot access 'Mundo': No such file or directory
Hola
$ echo Hola $(ls Mundo 2> /dev/null)
Hola
$ touch Mundo
$ echo Hola $(ls Mundo)
Hola Mundo
$ 
```

**Comment by jklmnn** [comment]
> The good-Unix-citizen solution would be to always print those warnings and errors in the error output

Yes I think this is the correct solution here.
