### ISSUE TITLE
MacOS not distinguished from Linux?

### ISSUE THREAD

**Issue by pmunts** [alire-project/alire#1296]
Today I picked up a open-box Mac Mini M1 (arm64) to play around with.  After installing some homebrew stuff and Simon's compiler for M1 silicon, I tried out alire.  I was able to build `alr` 1.2.2 from a source checkout without any problems.

However, when I tried it out, I ran into some problems, that look like `alr` can't tell the difference between Linux and MacOS.

First, I did this, which should not succeed, because `libsimpleio` is **only** supposed to be available for Linux:
```
bethany:~ pmunts$ alr get libsimpleio
ⓘ Deploying libsimpleio=1.20658.1...                                     
################################################################################################################# 100.0%

libsimpleio=1.20658.1 successfully retrieved.
There are no dependencies.
```

On Windows, the same command fails (which is correct):
```
C:\Users\pmunts>alr get libsimpleio
ERROR: Release within the requested versions [libsimpleio*] does not exist in the catalog.
```

Then I tried the following:
```
bethany:~ pmunts$ alr get remoteio
warn:                                                                    
warn:    New solution is incomplete.
warn:    +↪ libhidapi *    (new,external)
warn:    +↪ libusb    ~1.0 (new,external)
warn: 
warn: Could not find a complete solution for remoteio=1.20650.1
Build will fail unless externals are made available, do you want to continue?
[Y] Yes  [N] No  (default is No) yes
ⓘ Deploying remoteio=1.20650.1...
################################################################################################################# 100.0%
warn: Generating possibly incomplete environment because of missing dependencies
ⓘ Running post_fetch actions for remoteio=1.20650.1...
sed: 1: "src/objects/hid-hidapi.ads": unterminated substitute pattern
error: A post-fetch action failed, re-run with -vv -d for details
```
For some reason, `alr` tried to run the Linux post-fetch action, which happens to run `sed`, which on a Mac is goofy compared to Linux: It demands a suffix immediately after the `-i` option.

Attached is the `
[remoteio.toml.txt](https://github.com/alire-project/alire/files/10453729/remoteio.toml.txt)
.toml` for `remoteio`, which I'd like to use on MacOS.

**Comment by Fabien-Chouteau** [comment]
On macOS you have to compile with this environment variable: `ALIRE_OS=macOS`. That likely the issue here.

See: https://github.com/alire-project/alire#building-from-sources
