### ISSUE TITLE
Version command not running

### ISSUE THREAD

**Issue by vani2620** [alire-project/alire#1301]
I tried building the project from source and while it seemed to have built successfully, running `alr version` doesn't seem to work. I'm using 64-bit Windows. The error I get reads

Program 'alr.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
+ alr version
+ ~~~~~~~~~~~.
At line:1 char:1
+ alr version
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by mosteo** [comment]
How did you do the build?

For this kind of question I think is more appropriate to use the Discussions, at least unless some clear bug is identified. I'm going to convert this issue but I don't think it changes anything wrt to subscriptions and etc.
