### ISSUE TITLE
Allow sharing build of common crates

### ISSUE THREAD

**Issue by stephe-ada-guru** [alire-project/alire#1308]
There are (soon to be) three emacs crates (emacs_ada_mode, emacs_gpr_mode, emacs_wisitoken_grammar_mode) that depend on several other crates (stephes_ada_library, emacs_wisi, gnatcoll). I commonly install all three top-level crates, so the dependency crates get compiled three times. There are probably other examples of this with other crates; gnatcoll is probably used by many crates.

It would speed things up and save disk space if those dependency builds could be shared.

It would make sense to only allow sharing release builds, to avoid release/devel conflicts. We'd have to ensure that any other gpr external variables are set compatibly; it should be possible to write the variables to a file and compare that for each attempted share.

This is similar to the way the gnat and gprbuild deployments are shared.

**Comment by mosteo** [comment]
This was already in our radar for the near term, so stay tuned.

**Comment by mgrojo** [comment]
Will this simply be solved locally through sharing the cache dependencies globally to the user or by per-crate configuration? Or will it be provided organization-wide, I mean, via sharing the built artifact using a remote repository, like other tools do (e.g. Maven tool and Nexus repository)? The first point is good news, the second one, would be awesome (and compatible to the first one).

**Comment by mosteo** [comment]
For the time being it will be something along the lines of your first suggestion.

**Comment by mosteo** [comment]
Implemented in #1449
