### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by Peter186** [alire-project/alire#1317]
### Discussed in https://github.com/alire-project/alire/discussions/1316

<div type='discussions-op-text'>

<sup>Originally posted by **Peter186** February  1, 2023</sup>
The Linux installation instructions on https://alire.ada.dev/docs/#first-steps  say to add alr to the environment variable PATH, by running

    export PATH=<PATH_TO_EXTRACTED>/bin/:$PATH

Should this not be

    export PATH=<PATH_TO_EXTRACTED>:$PATH ?

Thanks and regards.
</div>

**Comment by Fabien-Chouteau** [comment]
Hi @Peter186, this is because the archive contains a `bin/` directory where the executable is located.
