### ISSUE TITLE
`alr build` does not work

### ISSUE THREAD

**Issue by yannickmoy** [alire-project/alire#1357]
Hi, I just got a fresh clone of the repo, installed version of 1.2.2 of Alire on Linux (Ubuntu 20.04) and ran `alr build` which is documented in the README as getting and building all dependencies, but I ran into an error:

```
clic-subcommand-instance.ads:3:06: error: file "toml.ads" not found
```

Is there anything more to do?

**Comment by mosteo** [comment]
Mmm I understand that this is when trying to build the dev branch with the stable `alr`.

You can either build with the nightly release or, probably simpler, just run the `dev/build.sh` (after checking out submodules if you didn't already) which doesn't require `alr` to build itself.

**Comment by yannickmoy** [comment]
thanks @mosteo that worked!
