### ISSUE TITLE
alire way for unreleased dependencies?

### ISSUE THREAD

**Issue by HROMANO** [alire-project/alire#1359]
I was giving a try to VSS, but the functions I want to use are not in the latest release.

Is there an alire way to use some devel/unreleased version as a dependency? Like setting [[depends-on]] to a specific branch/commit/url? Probably something to forbid when publishing a crate, but useful when developing it. I didn't saw that in the doc.

And as a bonus to apply patches to dependencies (something like makepkg does on archlinux)?

Thanks

**Comment by mosteo** [comment]
Look here: https://alire.ada.dev/docs/#work-in-progress-dependency-overrides

You could automatically patch by defining a post-fetch action in your own crate, I guess, although I've never tried that.

**Comment by HROMANO** [comment]
Thanks. I'll have to change my glasses next time!
