### ISSUE TITLE
Alire trying to install msys2 on non-existent drive location on windows

### ISSUE THREAD

**Issue by WRidder** [alire-project/alire#1374]
Tried using version `1.2.2` and `1.2.1`. 

Installed alire, next running `alr` to install msys2 yields the following result:  
```bash
PS C:\Users\XX> alr
Alire can use the msys2 Windows system package manager to provide easy install
of tools (git, unzip, make, etc.) as well as libraries (libsdl, libusb, etc.)
The use of msys2 is recommend for a better user experience.
(msys2 will be installed in 'H:\\.cache\alire\msys64').
Do you want Alire to install msys2? (recommended)
[Y] Yes  [N] No  (default is Yes)
Using default: Yes

raised ALIRE.CHECKED_ERROR : alire-stored-error:1
[C:\Program Files\Alire\bin\alr.exe]
0xdc98eb Semantic_Versioning.Basic.At_Least at alire.adb:251
0xdca0c0 Semantic_Versioning.Basic.At_Least at alire.adb:270
0xdc9dee Semantic_Versioning.Basic.At_Least at alire.adb:263
0xa703dc Semantic_Versioning.Basic.At_Least at alire-platforms-current__windows.adb:421
0xa707bd Semantic_Versioning.Basic.At_Least at alire-platforms-current__windows.adb:439
0x403f25 Adainit at b__alr-main.adb:1848
0x404bd1 Main at b__alr-main.adb:2129
0x401423 __tmainCRTStartup at ???
0x40113b mainCRTStartup at ???
[C:\windows\System32\KERNEL32.DLL]
0x7ffe41047602
[C:\windows\SYSTEM32\ntdll.dll]
0x7ffe4208269f
ERROR: invalid new directory path name "H:". (This error can be overridden with --force.)
ERROR: alr encountered an unexpected error, re-run with -d for details.
```

The `H:` directory does not exist on my computer. Only a `C:` and `D:` drive exist. I am using 
```
Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
```

**Comment by mosteo** [comment]
Could you please report the value of your `HOMEDRIVE` and `USERPROFILE` env variables? For example, in a `cmd.exe` terminal:
```
echo %HOMEDRIVE%
echo %USERPROFILE%
```

**Comment by WRidder** [comment]
great catch, `echo %HOMEDRIVE%` yields `H:`. 

This drive is a personal drive when in the office environment. So makes sense. However, being a network drive, this is not a good fit to install msys2 since it is not disconnected WFH. However, changing the `echo %HOMEDRIVE%` is not as easy as it seems on a corporate laptop. 

Anyway, issue is clearly on my end. Thanks for the pointers!

**Comment by mosteo** [comment]
Alire 1.3+ is using %USERPROFILE%, in case it helps you in the future.

**Comment by WRidder** [comment]
Yes, that will help for sure. In the current situation, using %HOMEDRIVE% alire is not useable when using laptops which have network drives which are only present when in the company network.
