### ISSUE TITLE
exec: `--` "end of options" switch doesn't work with `--help`

### ISSUE THREAD

**Issue by leogermond** [alire-project/alire#1379]
The `--` switch is often used to mean "end of options", meaning the remainder of the line should not be parsed as dash-prefixed options but should be understood / forwarded at face value.

Steps:
`alr exec -- ldd --help`

Expected:
`--help` is passed as is to `ldd`. `ldd` displays its help menu

Actual:
`alr` parses `--help`, catches it. `alr` display its own help menu.

I'm pretty sure that's a bug considering `--`  is described on `alr`'s usage line
`alr exec [options] [-P?] [--] <executable/script> [<switches and arguments>]`
(pretty sure there is a `--help` parsing shortcut which causes the issue)

Context: running through Alire app on Windows 11, `alr --version` is `alr 1.2.2`

**Comment by Fabien-Chouteau** [comment]
That's because of a special handing of `-h` `--help` in https://github.com/alire-project/clic

https://github.com/alire-project/clic/blob/8d26222de71014554999e48c821906fca0e3dc41/src/clic-subcommand-instance.adb#L541
