### ISSUE TITLE
Use GNATCOLL.VFS for filesystems handling

### ISSUE THREAD

**Issue by pmderodat** [alire-project/alire#140]
As discussed in #135 , we should probably use `GNATCOLL.VFS` to save us the trouble of reimplementing basic filesystem handling capabilities, such as composing filenames from arbitrary components (i.e. Join("/blah/foo", "bar/baz"), which `Ada.Directories.Compose` does not allow), creating directories in a recursive fashion, checking whether a path is absolute, etc. File system handling is hard to get right even for one platform, so when we want to handle both Windows and Unix-style systems, things get pretty much involved!

I’ll use this issue to track the addition of [gnatcoll-core](/AdaCore/gnatcoll-core) as a new dependency and the incremental reimplementation of our file system handling primitives using GNATCOLL.VFS.

**Comment by mosteo** [comment]
GNATCOLL was incorporated in #152 and since then VFS is used as needed.
