### ISSUE TITLE
MacPorts on macOS

### ISSUE THREAD

**Issue by simonjwright** [alire-project/alire#1403]
Having added support for the package manager [Homebrew](https://brew.sh), I'm tentatively considering the same for [MacPorts](https://www.macports.org). Would there be interest? What are the timescales for 2.0?

**Comment by mosteo** [comment]
> What are the timescales for 2.0?

Not long now. Ideally release candidate in early august.

**Comment by simonjwright** [comment]
Implemented in fa6c67d.
