### ISSUE TITLE
Unable to build Alire due to ada_toml issue

### ISSUE THREAD

**Issue by rveenker** [alire-project/alire#1415]
After cloning Alire recursively and checking out the master branch, I could not build alr because there was an issue with ada_toml:
The message I get when using 'alr update' is:
⚠ Pin for ada_toml does not contain an Alire manifest. It will be used as a raw GNAT project.

When I try to build using 'alr build', I get:
clic-config.ads:3:06: error: file "toml.ads" not found

Note that I am using Alire version 1.2.2 for Linux (from the Alire website).
However, I was able to build alr from the 'release/1.2' branch.

**Comment by mosteo** [comment]
Thanks for the report. Yes, this is a known issue that was already fixed for future versions.

You can alternatively build the same version directly using `gprbuild -p -j0 alr_env.gpr`.
