### ISSUE TITLE
CI fails in Install FSF Toolchain

### ISSUE THREAD

**Issue by simonjwright** [alire-project/alire#1417]
See [this run](https://github.com/simonjwright/alire/actions/runs/5737861391/job/15550313359), which was a check on a proposed patch to address #1410.

For info, the master branch that I was running the PR against was up-to-date with alire-project/alire:master.

Also, I see that the docker workflow ran OK.

**Comment by mosteo** [comment]
Is this reproducible? I've seem some iffy behavior from GH actions from time to time (this doesn't seem one of those, but just in case).

**Comment by simonjwright** [comment]
I just re-ran the linux & macos workflows, with the same result in each case (and the same failure); starting at [line 200](https://github.com/simonjwright/alire/actions/runs/5737861391/job/15587992479#step:3:215),
```
Note: Installing gnat_native=12.2.1...
ERROR: directory tree rooted at "/home/runner/work/alire/alire/alire_prefix/gnat_native_12.2.1_11f3b811/lib64" could not be deleted
ERROR: alr encountered an unexpected error, re-run with -d for details.
Error: Process completed with exit code 1.
```

May I try a PR to the project repo? (I was hoping to fix any errors before the real PR)

**Comment by simonjwright** [comment]
I decided to raise the PR against the alire repo, which only failed on macOS (because of a side-effect of this change); other workflows OK.

I recently tried a similar scheme (try a PR on my own fork), which failed similarly, and worked fine on the alire repo, so I don’t think I’ll be trying that again.

No idea why :-(

**Comment by mosteo** [comment]
I'm starting to see this in my own workflows for different distros. I'll try to add some debug output to that deletion routine.
