### ISSUE TITLE
"un-git" the releases deployed from git repos  

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#1455]
What I mean here is to **not** have releases deployed from git as valid git checkouts.

This idea starts with a discussion with a user that was confused by Alire's behavior. This person wanted to use `alr get` as a way to checkout a repository to work on it, and was surprised by the fact that `alire.toml` was modified (see why here: https://github.com/alire-project/alire/issues/1385#issuecomment-1716222070).

For me the disconnect is in the expectation that `alr get` gives when the source of the release is a git repo. Indeed you get a git checkout, but it's a release not a development branch.

What I want to suggest here is to change this behavior and not have releases as valid git checkout. The only way I found to do this is to remove the `.git` folder after `git clone` .

**Comment by mgrojo** [comment]
If you're definitely implementing this, I suggest running `git clone` with the argument `--depth 1`, otherwise the clone will download all the history, only to be deleted later, wasting time and bandwidth.

**Comment by Fabien-Chouteau** [comment]
> If you're definitely implementing this, I suggest running `git clone` with the argument `--depth 1`, otherwise the clone will download all the history, only to be deleted later, wasting time and bandwidth.

Indeed, in fact we can probably start by doing `--depth 1` already.

**Comment by rocher** [comment]
Also, please consider a "git restore alire.toml" after a fresh clone to
avoid seeing this file as modified.

**Comment by Fabien-Chouteau** [comment]
> Also, please consider a "git restore alire.toml" after a fresh clone to avoid seeing this file as modified.

The file is modified for a good reason. see here: https://github.com/alire-project/alire/issues/1385#issuecomment-1716222070

**Comment by rocher** [comment]
Thanks Fabien for this reference, good point.
Is there a (more complete) explanation of why and how manifests are
modified?

BR,
-- Francesc Rocher
