### ISSUE TITLE
xmlada build fails depending on contents of `Path` Windows system variable

### ISSUE THREAD

**Issue by MaxBarraclough** [alire-project/alire#1474]
I saw this issue in Windows 11/x86-64 with alr 1.2.2. I was able to fix it by tidying my `Path` system-variable, removing the `C:\Users\mb\Downloads\swigwin-4.1.1\swigwin-4.1.1` entry which I had added some time ago for non-Ada reasons. Seemingly this caused an issue in finding a script file. (A basic *hello world* would build fine regardless.)

What follows is how I encountered the issue prior to tidying `Path`:

I first encountered it after trying this (gnatcoll depends on xmlada):

    alr with gnatcoll

Minimal steps triggering the issue, enabling chatty output:

    alr init --bin demo_proj
    cd demo_proj
    alr with xmlada

Output:

    Note: Synchronizing workspace...
    Nothing to update.
    
    Requested changes:
    
       + xmlada ^23.0.0 (add)
    
    Changes to dependency solution:
    
       +i gnat   13.1.0 (new,installed,gnat_native,indirect)
       +  xmlada 23.0.0 (new)
    
    Do you want to proceed?
    [Y] Yes  [N] No  (default is Yes)
    Using default: Yes
    Note: Deploying xmlada=23.0.0...
          -=O=-           #        #         #          #
    Note: Running post_fetch actions for xmlada=23.0.0...
    configure: loading site script /usr/local/etc/config.site
    configure: error: cannot find install-sh, install.sh, or shtool in "/c/Users/mb/Downloads/swigwin-4.1.1/swigwin-4.1.1" "/c/Users/mb/Downloads/swigwin-4.1.1/swigwin-4.1.1/.." "/c/Users/mb/Downloads/swigwin-4.1.1/swigwin-4.1.1/../.."
    ERROR: A post-fetch action failed, re-run with -vv -d for details

**Comment by Fabien-Chouteau** [comment]
@mosteo I am not sure there's much we can do here...

**Comment by mosteo** [comment]
Right, I just wanted to confirm that this doesn't apply to a default installation.
