### ISSUE TITLE
Suggestion: `alr install` to use `$HOME/.local/bin` as default directory for executables 

### ISSUE THREAD

**Issue by mgrojo** [alire-project/alire#1481]
I wonder if `alr install` should honor the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

>  User-specific executable files may be stored in $HOME/.local/bin. Distributions should ensure this directory shows up in the UNIX $PATH environment variable, at an appropriate place. 

It doesn't sound very mandatory, but that will make the installed programs directly visible, at least on most Linux distributions.

Was this considered? It's just a minor matter, though, since the prefix can be freely specified.

Two other comments about the prefix:

Can't the prefix be configured, only specified on the command line? 

```
alr install --help
[...]
   --prefix=ARG  Override installation prefix (default is ${CRATE_ROOT}/alire/prefix))
```
Shouldn't it say that the default is `${HOME}/.alire` as in the DESCRIPTION?

**Comment by mosteo** [comment]
The thing with using a shared folder like `.local/bin` is that if you mess your prefix (and `alr install` isn't trying to be super consistent unlike e.g. `apt`, as there are unknowns about binary artifacts) you can't simply remove and reinstall. So, in this instance, I followed the example of Rust's `.cargo/bin`.

> Shouldn't it say that the default is ${HOME}/.alire as in the DESCRIPTION?

Yes, I thought I had fixed this recently, but maybe I did only in the description.

**Comment by mgrojo** [comment]
Suggestion already considered and discarded; issue in help fixed; so closing this now.
