### ISSUE TITLE
Remove a crate dependency using "without" keyword

### ISSUE THREAD

**Issue by dalybrown** [alire-project/alire#1484]
This is very minor, but an intuitive way to remove a crate dependency could be to use the keyword `without`.

As an example:

`alr with crate_name` can add the dependency.
`alr without crate_name` can remove the dependency.

This could be in addition to the existing `with --del` option. Again, very minor, but it seems more natural to me :).

**Comment by mgrojo** [comment]
You can already do this through an alias:

```sh
alr config --set --global alias.without 'with --del'
```
There are predefined aliases, so it might also make sense to have this included.

**Comment by dalybrown** [comment]
Oh cool - I hadn't used that yet. Thanks!

**Comment by mosteo** [comment]
I'm not very keen on having two ways of doing the same; given that you can define the alias if you want, I will close this one with no action.
