### ISSUE TITLE
Confusing output for alr with command when a crate does not exist

### ISSUE THREAD

**Issue by stcarrez** [alire-project/alire#1488]
When using the `alr with` command, if you give a wrong crate name, you will get the following output:

```
$ alr with plop
Requested changes:                                                   

   ✓ plop * (add)
                            
Changes to dependency solution:

   New solution is incomplete.
   +❗ plop * (new,missing:unknown)

Do you want to proceed?
[Y] Yes  [N] No  (default is No)
```

This output is confusing for me because it suggests that the `plop` crate is found as it is written in the beginning with the green checkbox:

```
Requested changes:                                                   

   ✓ plop * (add)
```

We should have a clever message that simply tells us the crate is not found.

**Comment by mosteo** [comment]
Sensible, thanks for the report.
