### ISSUE TITLE
`-c` global option doesn't load config as expected

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#1496]
Hi there, 
so a colleague and I notice a problem when using local config dir with `-c`.

Here's the procedure to reproduce:
```console
$ mkdir my_conf
$ echo "test_value=42" > my_conf/config.toml 
$ alr -c my_conf config --get test_value --global
```
I would expect this to show the value `42`.

This is a reproducer, the original issue was trying to setup a `alr toolchain --select` with a local config folder.

**Comment by mosteo** [comment]
Thanks for the reproducer
