### ISSUE TITLE
v2.0.0-beta1 binaries fail on Linux distributions with older libc.so.6

### ISSUE THREAD

**Issue by serock** [alire-project/alire#1511]
When attempting to run the AppImage binary on **openSUSE Leap 15.5**, it fails with the following messages:
```
./alr-2.0.0-beta1-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./alr-2.0.0-beta1-x86_64.AppImage)
./alr-2.0.0-beta1-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./alr-2.0.0-beta1-x86_64.AppImage)
./alr-2.0.0-beta1-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./alr-2.0.0-beta1-x86_64.AppImage)
```
When attempting to run the x86_64-linux binary on **openSUSE Leap 15.5**, it fails with similar messages:

```
./alr: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./alr)
./alr: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./alr)
./alr: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./alr)
```

Similar messages are seen on **Ubuntu 20.04 LTS** for both the AppImage and x86_64-linux binaries.

**Comment by mgrojo** [comment]
The [AppImage project recommends](https://github.com/AppImage/appimage.github.io#checklist-for-submitting-your-own-appimage):

> Must run on the [oldest still-supported Ubuntu LTS release](https://www.ubuntu.com/info/release-end-of-life) without the installation of additional packages. Targeting the oldest still-supported LTS is to ensure that the AppImage will run not only on the very latest, but also on older target systems, such as enterprise distributions (not limited to Ubuntu)

The oldest supported [Ubuntu release in GitHub actions](https://github.com/actions/runner-images#available-images) is Ubuntu 20.04. Thus, the solution is building with that Ubuntu version.

**Comment by mosteo** [comment]
I actually spent some time attempting to downgrade our appimages to Ubuntu 20.04, but the compiler in that distro isn't able to compiler Alire anymore due to elaboration circularities. At that point I tried installing newer compilers but more problems that I can't remember started creeping up, and I hadn't the time to spare.

I agree that it would be good to comply with that recommendation.

**Comment by serock** [comment]
Hi @mosteo. I modified the `.github/workflows/ci-appimage.yml` to build an appimage on Ubuntu 20.04 with GNAT 10. I submitted pull request #1519.
