### ISSUE TITLE
Document creating a Github Personal Access Token

### ISSUE THREAD

**Issue by Lucretia** [alire-project/alire#1521]
Just need a section using both of GH's PAT's on which permissions to set up.

**Comment by stcarrez** [comment]
I agree! I've tried but failed miserably: it didn't worked for me with a token that GitHub gave to me. May be it was a permission issue but I think I granted almost everything. The token expires quickly, which is fine for security, but annoying to create again.

**Comment by Lucretia** [comment]
I created a classic one with the following permissions ``` public_repo, read:user, repo:status, repo_deployment, user:email``` which I'm certain is too much, but it worked. The new beta ones are too complex and the docs are non-existent.
