### ISSUE TITLE
Multiple binaries not shown only one is run

### ISSUE THREAD

**Issue by Lucretia** [alire-project/alire#1524]
I had 1.2.1 installed, I have since installed 1.2.2 and nightly and all give the following:

```bash
$ ./bin/alr run --list
Crate learnadainy builds these executables:
   learnadainy (found at /home/laguest/src/mine-new/learnadainy/bin/learnadainy)
```

```alr run``` only runs the last executable in the ```Main`` section in the GPR.

**Comment by Lucretia** [comment]
See #239

**Comment by Lucretia** [comment]
Also,

```bash
$ alr run hello
ⓘ Building learnadainy=0.1.0-dev/learnadainy.gpr...                   
gprbuild: "empty" up to date
gprbuild: "hello" up to date
gprbuild: "learnadainy" up to date
Build finished successfully in 2.68 seconds.
error: The requested executable is not built by this release (see declared list with 'alr run --list')
```

**Comment by Fabien-Chouteau** [comment]
At the moment Alire is not aware of the binaries declared in the GPR file. What Alire know is what is listed in the `executables = ["my_main"]` property of the `alire.toml` manifest.

So you have to add `empty`, and `hello` to that list.
