### ISSUE TITLE
Mandatory maintainers-logins field in manifest should not be limited to GitHub logins

### ISSUE THREAD

**Issue by dalybrown** [alire-project/alire#1553]
I'm not sure the history of why this field is a prerequisite to publishing. However, I don't think it should be limited to just GitHub logins since some of us use (or... want to use) a private index not hosted on GitHub.

If the idea is to limit who can modify the crate, perhaps instead of hard coding rules to match GitHub logins, it can automatically detect which system (GitLab, GitHub, others) and use rules to match logins for that. Alternatively, provide some way to generate publishing information from the `alr publish` commands that allows you to omit this field. A third option is to look for a code owners file in the repo and respect those rules on who can update the crate.

**Comment by Fabien-Chouteau** [comment]
Hi @dalybrown, the GitHub login is only required for the community index as a basic way to [check the identity of the person](https://github.com/alire-project/alire-index-checks/blob/stable-1.2.1/scripts/check-author.sh) submitting a release or updating a release. 

For other indexes it is optional, so it doesn't matter what you put in it?

I am curious, may I ask what is your use case for a private index?

**Comment by dalybrown** [comment]
We just used our public GitHub logins for now, but the `alr publish` command seems to require the fields be present, regardless of the index (or just assumes you only publish to the community index). Maybe I didn't understand the `alr publish` command enough and that it is *only* for the community index. In that case, I misunderstood what it was for. (I thought it was a general purpose helper for publishing to any index.) We just hand create our manifest files for our private index for now.

We use a private index because we develop most of our software in Ada/SPARK and wanted to use a package manager for our internally develop proprietary Ada code. We have previously written our own package manager but decided to adopt what we hope will be the language's standard package manager.

We use it similar to how companies would use a private python index, or a private debian package manager, or a private maven repository.

**Comment by mosteo** [comment]
@dalybrown, you're right that the check is premature in the sense that you may only want the generated manifest. In 2.0 it will make sense to disable that particular check when `--skip-submit` is supplied (that doesn't exist in 1.x).

I think you may be currently able to override the check with `alr --force publish`.
