### ISSUE TITLE
Error: port info --version returned 2 lines.

### ISSUE THREAD

**Issue by Blady-Com** [alire-project/alire#1574]
**Checklist**

- [X] I've included the output of `alr version`.
- [X] I've included complete steps to reproduce my issue.

**Describe the bug**
Using MacPorts on macOS, it happens that MacPorts needs to be updated, it tells that with a warning:
`Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.`
This extra line misleads alr when searching for a port version, for exemple:
```
% port info --version gnutls
Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
version: 3.7.10
```

**To Reproduce**
0. Wait some time for an outdated MacPorts configuration
1. Go to any location
2. Run
`alr -v -d search uxstrings`

error: port info --version returned 2 lines.

**Expected Behavior**
Alr outputs the expected information:
```
NAME       STATUS  VERSION               DESCRIPTION                         NOTES
uxstrings          0.6.0+alpha-20231007  Unicode Extended Strings utilities
```
**`alr` version**
alr 2.0-beta1

**`alr` logs**
% alr -v -d search uxstrings
-> Using default value for configuration 'distribution.disable_detection': 'FALSE'
detail: Found 1 indexes             
detail: Loading index found at /Users/me/.config/alire/indexes/community/repo/index
detail: Loading full index from /Users/me/.config/alire/indexes/community/repo/index
detail: Using default value for configuration 'warning.old_index': 'TRUE'
detail: Spawning: ["git", "branch"] > /private/var/folders/2q/ygx0g3dx6bv7m1ld1rvm84j80000gq/T/alr-zsbr.tmp
detail: Spawning: ["uname", "-m"] > /private/var/folders/2q/ygx0g3dx6bv7m1ld1rvm84j80000gq/T/alr-byii.tmp
detail: Searching "uxstrings"...                
detail: Index already loaded, loading skipped  
detail: Loading index found at /Users/me/.config/alire/indexes/community/repo/index
detail: Loading index found at /Users/me/.config/alire/indexes/community/repo/index
detail: Loading index found at /Users/me/.config/alire/indexes/community/repo/index
detail: Loading index found at /Users/me/.config/alire/indexes/community/repo/index
detail: Loading index found at /Users/me/.config/alire/indexes/community/repo/index
detail: Loading index found at /Users/me/.config/alire/indexes/community/repo/index
detail: Solving dependencies with options: Age order: NEWEST; Completeness: FIRST_COMPLETE; Externals: DETECT; Hinting: HINT
detail: Root dependency tree is: (gnat>=2021 | (>=12 & <2000) and simple_components^4.62.0)
detail: No user pins to apply                  
                                                                                ◶ Searching... ux... Solving dependencies... Looking for external crate: gnat_ex                                                                                ◶ Searching... ux... Solving dependencies... Looking for external crate: gnat_ex                                                                                ◶ Searching... ux... Solving dependencies: 0/0/0/2 (complete/partial/dupes/state                                                                                ◶ Searching... ux... Solving dependencies: 0/0/0/2 (complete/partial/dupes/state                                                                                detail: Looking for system package: gnutls       
                                                                                detail: Spawning: ["port", "info", "--version", "gnutls"] > /private/var/folders/2q/ygx0g3dx6bv7m1ld1rvm84j80000gq/T/alr-hmqi.tmp
                                                                                                                                                                ◶ Searching... ux... Solving dependencies: 0/0/0/2 (complete/partial/dupes/state                                                                                stderr: CONSTRAINT_ERROR
stderr: port info --version returned 2 lines.
stderr: raised CONSTRAINT_ERROR : port info --version returned 2 lines.
Load address: 0x10f9eb000
Call stack traceback locations:
0x10ff92153 0x10fe68d40 0x10fe7f90b 0x10fef3087 0x10ff242a6 0x10fef4de6 0x110297b23 0x11029a1e5 0x1102a91c4 0x11029a357 0x1102a70c4 0x1102960fd 0x11029a1e5 0x1102a91c4 0x11029a357 0x110299fcb 0x1102a0b0f 0x1102a851b 0x110298312 0x11029a1e5 0x1102a0b0f 0x1102a851b 0x110298312 0x11029a1e5 0x1102a91c4 0x11029a357 0x11029200e 0x11028f767 0x10fa849ce 0x10fa86c29 0x10fa87e49 0x10fa8380c 0x10faed926 0x10faf94fc 0x10f9edb45 0x10f9f0f2e 0x7ff817e3541d

error: port info --version returned 2 lines.
error: alr encountered an unexpected error, re-run with -d for details.

**Comment by mosteo** [comment]
This probably should be demoted to a warning, although it is currently an error to avoid entering invalid regexes into the index. Grmmm.

Thanks for the report.

**Comment by mosteo** [comment]
@Blady-Com, could you check if the extra warning line is going to stderr or stdout?
