### ISSUE TITLE
Confusion between Alire Configuration (alr config) and Crate configuration

### ISSUE THREAD

**Issue by reznikmm** [alire-project/alire#1607]
**Describe the bug**
It seems configuration variable don't work.

**To Reproduce**
- `alr init --bin test; cd test`
- `alr config --set cortex_m.core m4f`
- `alr with cortex_m`
At this point alr 2.0 rc1 succeed, but alr 1.2.1 shows error:
> error: Configuration variable 'cortex_m.core not set and has no default value.

But the variable is there:
```
alr config --list --show-origin
LOCAL: last_build_profile=DEVELOPMENT
GLOBAL: toolchain.external.gprbuild=FALSE
GLOBAL: toolchain.assistant=false
LOCAL: cortex_m.core=m4f
GLOBAL: toolchain.use.gnat=gnat_arm_elf=13.2.1
GLOBAL: toolchain.use.gprbuild=gprbuild=22.0.1
GLOBAL: toolchain.external.gnat=FALSE
```
- `alr build`
```
warn: Configuration variable 'cortex_m.core' not set and has no default value.
error: Configuration variables without a default remain unset
```

**Expected Behavior**
I expect:
- No error messages if variable is set with `alr config --set cortex_m.core m4f`

**`alr` version**
<details>
<summary>alr version</summary>
APPLICATION
alr version:               2.0-rc1
libalire version:          2.0-rc1
compilation date:          2024-02-29 11:12:30
compiled with version:     13.2.0

CONFIGURATION
config folder:             /root/.config/alire
cache folder:              /root/.local/share/alire
vault folder:              /root/.local/share/alire/releases
build folder:              /root/.local/share/alire/builds
temp folder:               /root/test
force flag:                FALSE
non-interactive flag:      FALSE
community index branch:    stable-1.3.0
compatible index versions: ^1.1 & <=1.3.0
indexes folder:            /root/.config/alire/indexes
indexes metadata:          OK
index #1:                  (community) git+https://github.com/alire-project/alire-index#stable-1.3.0
toolchain folder:          /root/.local/share/alire/toolchains
toolchain assistant:       disabled
tool #1 gnat:              not configured
tool #2 gprbuild:          not configured
system package manager:    /usr/bin/apt
distro detection disabled: FALSE

WORKSPACE
root status:               VALID
root release:              test=0.1.0-dev
root load error:           none
root folder:               /root/test
current folder:            /root/test

SYSTEM
distribution:              UBUNTU
host-arch:                 X86_64
os:                        LINUX
target:                    NATIVE
toolchain:                 USER
word-size:                 BITS_64

</details>

**Comment by Fabien-Chouteau** [comment]
Hi Max,

`alr config` is for Alire configuration, not crate configuration. I know it's confusing, but everything is working fine.

Edit alire.toml to put the cortex_m crate configuration value in it:
```toml
[configuration.values]
cortex_m.core = "m4f"
```
