### ISSUE TITLE
Strange failure in CI with nightly Alire

### ISSUE THREAD

**Issue by simonjwright** [alire-project/alire#1629]
This issue can be seen at [this sdl2-examples run](https://github.com/simonjwright/sdl2-examples/actions/runs/8231488117/job/22506897267).

alr is 2.0-dev+beta2.

The workflow says
```
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up Alire
      uses: alire-project/setup-alire@v2
      with:
        version: "nightly"
    -
      name: Install toolchain
      run: |
        alr --non-interactive config --global --set toolchain.assistant false
        alr --non-interactive toolchain --install gnat_native
        alr --non-interactive toolchain --install gprbuild
        alr --non-interactive toolchain --select gnat_native
        alr --non-interactive toolchain --select gprbuild
    -
      name: Build
      run: |
        cd ada
        alr --non-interactive build
```
and the log says
```
Run alr --non-interactive config --global --set toolchain.assistant false
Warning: `alr config` is deprecated. Please use `alr settings` instead.
ERROR: Unrecognized option '--install' (command/topic "toolchain").
ERROR: try "alr help toolchain" for more information.
Error: Process completed with exit code 1.
```

**Comment by mosteo** [comment]
Thanks for the report, these are expected with recent refactorings, namely #1614 and #1621. Once everything is ready for 2.0 I will focus on the consequences.

**Comment by mosteo** [comment]
Sorry, I thought at first that by CI you referred to our checks. Indeed, you'll have to update your workflow to use `alr toolchain --select`. For what I see in the linked CI run, you never needed `alr toolchain --install` as `alr toolchain --select` does essentially the same, so you can just remove those two lines.
