### ISSUE TITLE
Alire 2.0.0 release doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by manthonyaiello** [alire-project/alire#1639]
The libc version against which Alire is built remains too new to allow the resulting binaries to work on Ubuntu 20.04. Trying to use Alire on this platform results in:

```
alr - toolchain --select gnat_native^13 gprbuild^22
alr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by bin/alr)
alr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by bin/alr)
alr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by bin/alr)
```

Unless Alire depends on features from newer versions of libc, it would be better to build on an older Ubuntu (e.g., 20.04) to ensure backwards compatibility.

**Comment by manthonyaiello** [comment]
(xref #1526)

**Comment by reznikmm** [comment]
I build ALS/Libadalang with GitHub Actions and I use alr to install the toolchain and fetch `xmlada`. Some users have Ubuntu 20.04, I guess, so I need Ubuntu 20.04 to build ALS usable by them. It would be nice to have `alr` running on Ubuntu 20.04.

**Comment by mgrojo** [comment]
This problem seems to be affecting also the PR check [centos-stream-fsf-latest](https://github.com/alire-project/alire-index/actions/runs/8287982135/job/22681576995#logs):

https://github.com/alire-project/alire-index/actions/runs/8287982135/job/22681576995#step:6:80

**Comment by mosteo** [comment]
Thanks for the report, this is not good.
