### ISSUE TITLE
`alr edit` with VS Code opens project file instead of project directory

### ISSUE THREAD

**Issue by yannickmoy** [alire-project/alire#1692]
**Checklist**

- [X] I've included the output of `alr version`.
- [X] I've included complete steps to reproduce my issue.

**Describe the bug**
When running `alr edit` with VS Code as the editor, it runs `code my_project.gpr` which simply opens the project file. It looks like it would be more useful to run `code .` to open the current project directory. WDYT?

**`alr` version**
alr 2.0.1

**Comment by mosteo** [comment]
I indeed always open with `code .`, I wonder if opening the `.gpr` file has any implication for the Ada plugin. @reznikmm, I think you'll have the answer to this.

**Comment by yannickmoy** [comment]
No effect that I can see, expect that it just opens the project file, which is typically not what you want.

**Comment by reznikmm** [comment]
Ada VS Code extension doesn't use `code` arguments. So it's better to execute `code .` instead of `code ${GPR_FILE}`.
