### ISSUE TITLE
Bug with "alr search" on macOS

### ISSUE THREAD

**Issue by vdiem** [alire-project/alire#1697]
**Checklist**

- [X] I've included the output of `alr version`.
- [X] I've included complete steps to reproduce my issue.

**Describe the bug**
Alire crashes on a simple search request.

**To Reproduce**

$ rm -rf .alire            
$ rm -rf .local/share/alire
$ rm -rf .config/alire     

$ alr -d search json       
◷ Searching... Loading indexes... Cloning into '/Users/vdiem/.config/alire/indexes/community/repo'...
remote: Enumerating objects: 10206, done.
remote: Counting objects: 100% (263/263), done.
remote: Compressing objects: 100% (169/169), done.
remote: Total 10206 (delta 110), reused 194 (delta 75), pack-reused 9943
Receiving objects: 100% (10206/10206), 1.88 MiB | 15.42 MiB/s, done.
Resolving deltas: 100% (5501/5501), done.
warn: Spent 0.01 seconds exploring complete solutions                                       
warn: Exploring incomplete solutions to dependencies, this may take some time...            
warn: Spent 0.01 seconds exploring complete solutions                                        
warn: Spent 0.01 seconds exploring complete solutions                                       
warn: Spent 0.01 seconds exploring complete solutions                                        
warn: Spent 0.17 seconds exploring complete solutions                                        
warn: Exploring incomplete solutions to dependencies, this may take some time...             
◴ Searching... jw... Solving dependencies... Looking for external crate: make...             
<data>:1:1: Unexpected character 'r'
stderr: GNATCOLL.JSON.INVALID_JSON_STREAM                                          
stderr: Unexpected character 'r'
stderr: raised GNATCOLL.JSON.INVALID_JSON_STREAM : Unexpected character 'r'
Load address: 0x10bb37000
Call stack traceback locations:
0x10c56024a 0x10c560313 0x10c56192e 0x10c562660 0x10c566965 0x10c098be7 0x10c09b1a0 0x10bf7985f 0x10bf8f850 0x10c001f56 0x10c03104e 0x10c003809 0x10c3aeac3 0x10c3b07fa 0x10c3bc0ec 0x10c3b0894 0x10c3b0692 0x10c3b58d6 0x10c3bb7d3 0x10c3af2fc 0x10c3b07fa 0x10c3a90a4 0x10c3a6917 0x10bbccde6 0x10bbce89a 0x10bbcfb52 0x10bbd0c5b 0x10bbcc0b2 0x10bbcc49b 0x10bc3527d 0x10bc4057a 0x10bb3905a 0x10bb3c728 0x7ff815050364

error: Unexpected character 'r'
error: alr encountered an unexpected error, re-run with -d for details.
error: error location: Call stack traceback locations:

**Expected Behavior**
Describe what happened and how it deviates from what should have happened, if unclear from the previous steps.
It should provide a list of crates matching the search, but alr crashes ! 

**`alr` version**

APPLICATION
alr version:               2.0.1
libalire version:          2.0.1
compilation date:          2024-06-14 19:22:27
compiled with version:     14.1.0

CONFIGURATION
settings folder:           /Users/vdiem/.config/alire
cache folder:              /Users/vdiem/.local/share/alire
vault folder:              /Users/vdiem/.local/share/alire/releases
build folder:              /Users/vdiem/.local/share/alire/builds
temp folder:               /private/var/folders/qf/7sf0z3jn11bbyjv2rz8f39680000gp/T
force flag:                FALSE
non-interactive flag:      FALSE
community index branch:    stable-1.3.0
compatible index versions: ^1.1 & <=1.3.0
indexes folder:            /Users/vdiem/.config/alire/indexes
indexes metadata:          OK
index #1:                  (community) git+https://github.com/alire-project/alire-index#stable-1.3.0
toolchain folder:          /Users/vdiem/.local/share/alire/toolchains
toolchain assistant:       enabled
tool #1 gnat:              not configured
tool #2 gprbuild:          not configured
system package manager:    /usr/local/bin/brew
distro detection disabled: FALSE

WORKSPACE
root status:               OUTSIDE
root release:              N/A
root load error:           N/A
root folder:               N/A
current folder:            /Users/vdiem

SYSTEM
distribution:              HOMEBREW
host-arch:                 X86_64
os:                        MACOS
target:                    NATIVE
toolchain:                 USER
word-size:                 BITS_64

**`alr` logs**
$ alr -vv -d search json 
[...]
debug: Listing release: gnatdist_garlic=6.0.1
debug: Status ended: gn
debug: Status start: gn
debug: Status ended: gn
debug: Status start: gn
debug: Listing release: gnatdoc=24.0.0
debug: Status ended: gn
debug: Status start: gn
debug: Status ended: gn
debug: Status start: gn
debug: Listing release: gnatprove=13.2.1
debug: Status ended: gn
debug: Status start: gn
debug: Status ended: gn
debug: Status start: gn
debug: Listing release: gnoga=2.1.2
debug: Status ended: gn
debug: Status start: gn
debug: Status ended: gn
debug: Status start: gp
debug: Listing release: gpr_unit_provider=23.0.0
debug: Status ended: gp
debug: Status start: gp
debug: Status ended: gp
debug: Status start: gp
debug: Listing release: gprbuild=22.0.1
debug: Status ended: gp
debug: Status start: gp
debug: Status ended: gp
debug: Status start: gs
debug: Listing release: gsl=0.1.0
debug: Status ended: gs
debug: Status start: gs
debug: Status ended: gs
debug: Status start: gt
debug: Listing release: gtkada=24.0.0
debug: Status ended: gt
debug: Status start: gt
debug: Status ended: gt
debug: Status start: gw
debug: Listing release: gwindows=1.4.3
debug: Status ended: gw
debug: Status start: gw
debug: Status ended: gw
debug: Status start: ha
debug: Listing release: hac=0.30.0
debug: Status ended: ha
debug: Status start: ha
debug: Status ended: ha
debug: Status start: ha
debug: Listing release: hal=0.4.0
debug: Status ended: ha
debug: Status start: ha
debug: Status ended: ha
debug: Status start: ha
debug: Listing release: hangman=1.0.0
debug: Status ended: ha
debug: Status start: ha
debug: Status ended: ha
debug: Status start: he
debug: Listing release: hello=1.0.2
debug: Status ended: he
debug: Status start: he
debug: Status ended: he
debug: Status start: he
debug: Listing release: hex_format=0.1.0
debug: Status ended: he
debug: Status start: he
debug: Status ended: he
debug: Status start: hi
debug: Listing release: hirtos=2.0.0
debug: Status ended: hi
debug: Status start: hi
debug: Status ended: hi
debug: Status start: hi
debug: Listing release: hirtos_separation_kernel=2.0.0
debug: Status ended: hi
debug: Status start: hi
debug: Status ended: hi
debug: Status start: hm
debug: Listing release: hmac=2.0.0
debug: Status ended: hm
debug: Status start: hm
debug: Status ended: hm
debug: Status start: hm
debug: Listing release: hmc5883=1.0.0
debug: Status ended: hm
debug: Status start: hm
debug: Status ended: hm
debug: Status start: ho
debug: Listing release: honki_tonks_zivilisationen=0.5.5305
debug: Status ended: ho
debug: Status start: ho
debug: Status ended: ho
debug: Status start: hu
debug: Listing release: hungarian=1.0.0
debug: Status ended: hu
debug: Status start: hu
debug: Status ended: hu
debug: Status start: in
debug: Listing release: ini_files=11.0.0
debug: Status ended: in
debug: Status start: in
debug: Status ended: in
debug: Status start: in
debug: Listing release: inotify=2.0.1
debug: Status ended: in
debug: Status start: in
debug: Status ended: in
debug: Status start: in
debug: Listing release: intl=1.0.1
debug: Status ended: in
debug: Status start: in
debug: Status ended: in
debug: Status start: is
debug: Listing release: iso=2.0.0
debug: Status ended: is
debug: Status start: is
debug: Status ended: is
debug: Status start: it
debug: Listing release: iterators=0.2.0
debug: Status ended: it
debug: Status start: it
debug: Status ended: it
debug: Status start: it
debug: Listing release: itsybitsy_bsp=0.0.4
debug: Status ended: it
debug: Status start: it
debug: Status ended: it
debug: Status start: it
debug: Listing release: itsybitsy_rp2040_bsp=0.2.0
debug: Status ended: it
debug: Status start: it
debug: Status ended: it
debug: Status start: j2
debug: Listing release: j2ada=1.4.2
debug: Status ended: j2
debug: Status start: j2
debug: Status ended: j2
debug: Status start: jo
debug: Listing release: journada=1.0.0
debug: Status ended: jo
debug: Status start: jo
debug: Status ended: jo
debug: Status start: js
debug: Listing release: json=5.0.3
debug: Listing release: json=5.0.3
debug: Status start: Solving dependencies
debug: Not reloading crate gnat                
debug: Not redoing detection of externals for crate gnat
debug: Not reloading crate gnat                
debug: Not reloading crate gprbuild            
debug: Not redoing detection of externals for crate gprbuild
debug: Not reloading crate gprbuild            
debug: Not reloading crate gprbuild            
debug: Detected available tools:               
detail: Solving dependencies with options: Age order: NEWEST; Completeness: FIRST_COMPLETE; Externals: DETECT; Hinting: HINT
detail: Root dependency tree is: (empty)       
detail: No user pins to apply                  
debug: Returning trivial solution for empty dependencies
debug: Status ended: Solving dependencies      
debug: Status ended: js                        
debug: Status start: js
debug: Status ended: js
debug: Status start: ju
debug: Listing release: jupyter_kernel=1.0.0
debug: Status ended: ju
debug: Status start: ju
debug: Status ended: ju
debug: Status start: jw
debug: Listing release: jwt=1.0.0
debug: Listing release: jwt=1.0.0
debug: Status start: Solving dependencies
debug: Not reloading crate gnat                
debug: Not redoing detection of externals for crate gnat
debug: Not reloading crate gnat                
debug: Not reloading crate gprbuild            
debug: Not redoing detection of externals for crate gprbuild
debug: Not reloading crate gprbuild            
debug: Not reloading crate gprbuild            
debug: Detected available tools:               
detail: Solving dependencies with options: Age order: NEWEST; Completeness: FIRST_COMPLETE; Externals: DETECT; Hinting: HINT
detail: Root dependency tree is: matreshka_league*
detail: No user pins to apply                  
debug: Not reloading crate matreshka_league    
debug: Not reloading crate matreshka_league    
debug: Skipping detection for crate without externals: matreshka_league
debug: Not reloading crate matreshka_league    
debug: Not reloading crate matreshka_league    
debug: Not reloading crate matreshka_league    
debug: Skipping detection for crate without externals: matreshka_league
debug: Not reloading crate matreshka_league    
debug: SOLVER: EXPAND                          
debug:   i: 4231; p: 0                         
debug:   TARGET: matreshka_league*             
debug:   SEEN: (empty)                         
debug:   EXPANDED: (empty)                     
debug:   REMAIN: (empty)                       
debug:   SOLUTION: (empty)                     
debug: Not reloading crate matreshka_league    
debug: Not reloading crate matreshka_league    
debug: Not reloading crate matreshka_league    
debug: Skipping detection for crate without externals: matreshka_league
debug: Not reloading crate matreshka_league    
debug: Not reloading crate matreshka_league    
debug: Not reloading crate matreshka_league    
debug: Skipping detection for crate without externals: matreshka_league
debug: Not reloading crate matreshka_league    
debug: SOLVER: considering 3 candidates to matreshka_league*: matreshka_league=18.1.0, matreshka_league=20.1.0, matreshka_league=21.0.0
debug: SOLVER: dependency FROZEN: matreshka_league=21.0.0 to satisfy matreshka_league* adding 2 dependencies to tree i: 4231; p: 0; TARGET: matreshka_league*; SEEN: (empty); EXPANDED: (empty); REMAIN: (empty); ; NEW: (make* and gnat<2000)
debug: SOLVER: EXPAND                          
debug:   i: 4232; p: 4231                      
debug:   TARGET: (empty)                       
debug:   SEEN: matreshka_league*               
debug:   EXPANDED: matreshka_league=21.0.0     
debug:   REMAIN: (make* and gnat<2000)         
debug:   SOLUTION: matreshka_league->matreshka_league=21.0.0
debug: SOLVER: EXPAND                          
debug:   i: 4233; p: 4232                      
debug:   TARGET: (make* and gnat<2000)         
debug:   SEEN: matreshka_league*               
debug:   EXPANDED: matreshka_league=21.0.0     
debug:   REMAIN: (empty)                       
debug:   SOLUTION: matreshka_league->matreshka_league=21.0.0
debug: SOLVER: EXPAND                          
debug:   i: 4234; p: 4233                      
debug:   TARGET: make*                         
debug:   SEEN: matreshka_league*               
debug:   EXPANDED: matreshka_league=21.0.0     
debug:   REMAIN: gnat<2000                     
debug:   SOLUTION: matreshka_league->matreshka_league=21.0.0
debug: Not reloading crate make                
debug: Not reloading crate make                
debug: Not reloading crate make                
debug: Looking for externals for crate: make   
debug: Detecting via provider: make            
debug: Status start: Looking for external crate: make
debug: Attempting detection of available external: make                            
debug: Looking for system packages that provide crate: make                        
detail: Looking for system package: make                                           
debug: detect? make                                                                
debug: Selected name for tempfile: /private/var/folders/qf/7sf0z3jn11bbyjv2rz8f39680000gp/T/alr-vobc.tmp when at dir: /Users/vdiem
detail: Spawning: ["brew", "info", "--json=v1", "make"] > /private/var/folders/qf/7sf0z3jn11bbyjv2rz8f39680000gp/T/alr-vobc.tmp
debug: Deleting temporary file /private/var/folders/qf/7sf0z3jn11bbyjv2rz8f39680000gp/T/alr-vobc.tmp...

<data>:1:1: Unexpected character 'r'
debug: Status ended: Looking for external crate: make                              
debug: Status ended: Solving dependencies                                          
debug: Status ended: jw                        
debug: Status ended: Searching
debug: ---8<--- Exception dump begin ---8<---
debug: GNATCOLL.JSON.INVALID_JSON_STREAM
debug: Unexpected character 'r'
debug: raised GNATCOLL.JSON.INVALID_JSON_STREAM : Unexpected character 'r'
Load address: 0x108e7d000
Call stack traceback locations:
0x1098a624a 0x1098a6313 0x1098a792e 0x1098a8660 0x1098ac965 0x1093debe7 0x1093e11a0 0x1092bf85f 0x1092d5850 0x109347f56 0x10937704e 0x109349809 0x1096f4ac3 0x1096f67fa 0x1097020ec 0x1096f6894 0x1096f6692 0x1096fb8d6 0x1097017d3 0x1096f52fc 0x1096f67fa 0x1096ef0a4 0x1096ec917 0x108f12de6 0x108f1489a 0x108f15b52 0x108f16c5b 0x108f120b2 0x108f1249b 0x108f7b27d 0x108f8657a 0x108e7f05a 0x108e82728 0x7ff815050364

debug: --->8--- Exception dump end ----->8---
stderr: GNATCOLL.JSON.INVALID_JSON_STREAM
stderr: Unexpected character 'r'
stderr: raised GNATCOLL.JSON.INVALID_JSON_STREAM : Unexpected character 'r'
Load address: 0x108e7d000
Call stack traceback locations:
0x1098a624a 0x1098a6313 0x1098a792e 0x1098a8660 0x1098ac965 0x1093debe7 0x1093e11a0 0x1092bf85f 0x1092d5850 0x109347f56 0x10937704e 0x109349809 0x1096f4ac3 0x1096f67fa 0x1097020ec 0x1096f6894 0x1096f6692 0x1096fb8d6 0x1097017d3 0x1096f52fc 0x1096f67fa 0x1096ef0a4 0x1096ec917 0x108f12de6 0x108f1489a 0x108f15b52 0x108f16c5b 0x108f120b2 0x108f1249b 0x108f7b27d 0x108f8657a 0x108e7f05a 0x108e82728 0x7ff815050364

error: Unexpected character 'r'
error: alr encountered an unexpected error, re-run with -d for details.
error: error location: Call stack traceback locations:

**Comment by mosteo** [comment]
Thanks for the report. Could you paste the output of
```
brew info --json=v1 make
```
in that machine?

**Comment by vdiem** [comment]
Sure. Here it is :

[
  {
    "name": "make",
    "full_name": "make",
    "tap": "homebrew/core",
    "oldnames": [

    ],
    "aliases": [

    ],
    "versioned_formulae": [

    ],
    "desc": "Utility for directing compilation",
    "license": "GPL-3.0-only",
    "homepage": "https://www.gnu.org/software/make/",
    "versions": {
      "stable": "4.4.1",
      "head": null,
      "bottle": true
    },
    "urls": {
      "stable": {
        "url": "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.lz",
        "tag": null,
        "revision": null,
        "using": null,
        "checksum": "8814ba072182b605d156d7589c19a43b89fc58ea479b9355146160946f8cf6e9"
      }
    },
    "revision": 0,
    "version_scheme": 0,
    "bottle": {
      "stable": {
        "rebuild": 0,
        "root_url": "https://ghcr.io/v2/homebrew/core",
        "files": {
          "arm64_sonoma": {
            "cellar": "/opt/homebrew/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:2cf9b5846e07363681d41819a13d2d9a993a69dd5090bbfae3da182915e777b9",
            "sha256": "2cf9b5846e07363681d41819a13d2d9a993a69dd5090bbfae3da182915e777b9"
          },
          "arm64_ventura": {
            "cellar": "/opt/homebrew/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:23e26446ffdefd2b7fe44c559e11ab6bc127abd32233847f4e73bb3de87d98c6",
            "sha256": "23e26446ffdefd2b7fe44c559e11ab6bc127abd32233847f4e73bb3de87d98c6"
          },
          "arm64_monterey": {
            "cellar": "/opt/homebrew/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:f3c69489afdb2ad686c7674d85deac4fcfdb3f891664c08c5d255af20a6eddcb",
            "sha256": "f3c69489afdb2ad686c7674d85deac4fcfdb3f891664c08c5d255af20a6eddcb"
          },
          "arm64_big_sur": {
            "cellar": "/opt/homebrew/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:cdb852c53ed94d31d5f4988338336b004f21857d1ecaa8e84b1c155bf92e0c47",
            "sha256": "cdb852c53ed94d31d5f4988338336b004f21857d1ecaa8e84b1c155bf92e0c47"
          },
          "sonoma": {
            "cellar": "/usr/local/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:8c51e1eebb1cb1ae3acc4c52d041b141dd7d1ca005ba0081fd7c47162d4a50db",
            "sha256": "8c51e1eebb1cb1ae3acc4c52d041b141dd7d1ca005ba0081fd7c47162d4a50db"
          },
          "ventura": {
            "cellar": "/usr/local/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:206c13dc47f17131b1337ed24677b69288c2f03f780d09d1c3e5fd11a41d6ad9",
            "sha256": "206c13dc47f17131b1337ed24677b69288c2f03f780d09d1c3e5fd11a41d6ad9"
          },
          "monterey": {
            "cellar": "/usr/local/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:75651f4a57f1a712dfed7ed926de8b4c7f6c728544627ea059304f28455c4bab",
            "sha256": "75651f4a57f1a712dfed7ed926de8b4c7f6c728544627ea059304f28455c4bab"
          },
          "big_sur": {
            "cellar": "/usr/local/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:2571cf69a3d123408660797685af0040097b1c273b13dfd0e3653ca1150830e2",
            "sha256": "2571cf69a3d123408660797685af0040097b1c273b13dfd0e3653ca1150830e2"
          },
          "x86_64_linux": {
            "cellar": "/home/linuxbrew/.linuxbrew/Cellar",
            "url": "https://ghcr.io/v2/homebrew/core/make/blobs/sha256:bded8e436d51f10ee36207ec69a0a318fb8583f83a5863f45bb203d3ae055170",
            "sha256": "bded8e436d51f10ee36207ec69a0a318fb8583f83a5863f45bb203d3ae055170"
          }
        }
      }
    },
    "pour_bottle_only_if": null,
    "keg_only": false,
    "keg_only_reason": null,
    "options": [

    ],
    "build_dependencies": [

    ],
    "dependencies": [

    ],
    "test_dependencies": [

    ],
    "recommended_dependencies": [

    ],
    "optional_dependencies": [

    ],
    "uses_from_macos": [

    ],
    "uses_from_macos_bounds": [

    ],
    "requirements": [

    ],
    "conflicts_with": [

    ],
    "conflicts_with_reasons": [

    ],
    "link_overwrite": [

    ],
    "caveats": "GNU \"make\" has been installed as \"gmake\".\nIf you need to use it as \"make\", you can add a \"gnubin\" directory\nto your PATH from your bashrc like:\n\n    PATH=\"$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$PATH\"\n",
    "installed": [

    ],
    "linked_keg": null,
    "pinned": false,
    "outdated": false,
    "deprecated": false,
    "deprecation_date": null,
    "deprecation_reason": null,
    "disabled": false,
    "disable_date": null,
    "disable_reason": null,
    "post_install_defined": false,
    "service": null,
    "tap_git_head": "79b063e381a837e4276bea56d6c2b5ae49205c0e",
    "ruby_source_path": "Formula/m/make.rb",
    "ruby_source_checksum": {
      "sha256": "1f0384f9d3108f5155a54aa118069ef394678e27dd2a0eae061b8e36055ab789"
    }
  }
]

**Comment by mosteo** [comment]
I am unable to reproduce this problem (see test run [here](https://github.com/mosteo/alire/actions/runs/11070199065/job/30759365835?pr=32#step:8:1)). Maybe `brew` was emitting some extra text for some reason?
