### ISSUE TITLE
`alr search gnat` produces error

### ISSUE THREAD

**Issue by khv2online** [alire-project/alire#1772]
**Checklist**

- [x] I've included the output of `alr version`.
- [x] I've included complete steps to reproduce my issue.

**Describe the bug**
I'm trying to run command `alr search gnat`, and it produces an error.

**To Reproduce**
1. Run 'alr search gnat'
2. See error

**Expected Behavior**
See the list of found packages.

**`alr` version**
`2.0.1`

**`alr` logs**
```
warn: Spent 0.02 seconds exploring complete solutions
warn: Spent 0.04 seconds exploring complete solutions
error: Empty point number
error: alr encountered an unexpected error, re-run with -d for details.
error: error location: 0x457d88 Semantic_Versioning.Parse.Eat_Number at semantic_versioning.adb:78
```

**Comment by mosteo** [comment]
Thanks for the report. This is fixed in the devel branch, and a bugfix release is around the corner.

As a workaround you can use `alr toolchain --select` to inspect all available gnat compilers.
