### ISSUE TITLE
2.0.2 release id

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#1781]
Hi @mosteo, 

I had to quickly deploy a hack for alire.ada.dev since the format of the version from `alr version` changed again in `2.0.2` release and now include commit id in build extension.
 
https://github.com/alire-project/alire.ada.dev/commit/bcc83cf279c097b58e1c83474da2c40224d9b606

We need the version id to be able to create a link to the download archive: https://github.com/alire-project/alire/releases/tag/v2.0.2

I would really prefer to have `alr version` show the same version as the release tag and release package.
The alternative would to implement some semver support in alire.ada.dev bash script.

**Comment by mosteo** [comment]
I see, sorry about that. Then we can include the commit information as a separated field entirely and leave the version as it was.
