### ISSUE TITLE
--trust switch to enforce integrity levels

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#208]
Right now hashes are mandatory for source archives and are used when available for git sources, but not required. Since giving warnings would pollute most releases, I suggest the following mechanism (or other that we discuss here) to select desired behavior.

Add a `--trust={off,warn,full}` switch that, on retrieval of a release, works as follows:
- off: no warnings for VCS origins without hashes (current status)
- warn: emit a warning for VCS origins without hashes (might become the default if at some point most crates have hashes).
- full: fail for any release without integrity hashes

**Comment by Fabien-Chouteau** [comment]
I think hash of the source is the bare minimum that we should accept. So I don't like the idea of disabling the checks.

**Comment by mosteo** [comment]
Then we don't need a switch at all, once we fill in the hashes for all existing crates, and require it for all new submissions. It's certainly the safest approach.

**Comment by Fabien-Chouteau** [comment]
> Then we don't need a switch at all, once we fill in the hashes for all existing crates, and require it for all new submissions. It's certainly the safest approach.

Yes, and we can automatically check the hash field on pull-requests on the index repo.

**Comment by mosteo** [comment]
Closing since we don't need it.
