### ISSUE TITLE
Add in-alr way of computing integrity hashes for releases

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#209]
At present hashes must be computed by hand with `git archive | shaXsum`, but since this is hidden knowledge for users, a way of computing a hash for a repository commit from `alr` should be provided. Furthermore, this probably should be easily integrated in the workflow for submitting a new crate release (both `cargo` and `opam` have a `publish` command).

**Comment by Fabien-Chouteau** [comment]
I agree.

I see that as a command that takes a valid origin (online archive, git repo) and produce the hash.

`alr checksum https://github.com/alire-project/alire@master`

**Comment by mosteo** [comment]
This is available after #215.
