### ISSUE TITLE
alr crashes when GNAT is not in PATH

### ISSUE THREAD

**Issue by senier** [alire-project/alire#236]
I built `alr` from master (aa96bf8f) using GNAT Community 2019 on Debian 10/x86_64 according to the instructions in the README. After putting `alr` into my path, I tried the example from the README in a newly created, empty directory:

```sh
$ mkdir ~/tmp/alire
$ cd ~/tmp/alire
$ alr get hangman
ERROR: alr get unsuccessful
```
```sh
$ alr search hangman
ERROR: alr search unsuccessful
```
```sh
$ alr list | grep hangman
hangman              Hangman game for the console
```
```sh
$ alr show hangman
hangman=1.0.0: Hangman game for the console
Origin: source archive v1.0.tar.gz at https://github.com/alire-project/Hangman/archive/v1.0.tar.gz with hash sha512:be628ad574b3072b2b854bf8f272c6c9d95cf9b2d88e7baa9a09754519ba6dc393b7fc7241547a9efc9705bfc77ca427a164ae8a52cfa5d739367f0bbaba7903
Properties:
   Author: Jon Hollan, Mark Hoffman, & Brandon Ball
   Description: Hangman game for the console
   Executable: hangmain
   Maintainer: alejandro@mosteo.com
   Maintainers_Logins: mosteo
```
```sh
$  alr version
alr build is (OUTSIDE) (0 releases indexed) (loaded in 0.001s)
config folder is /home/senier/.config/alire
source folder is /home/senier/.config/alire/alire
alr root is empty
alr project root detection has settled on path: /home/senier/tmp/alire
alr is finding 0 GPR project files
alr session state is OUTSIDE
alr compiled on [2019-11-14 08:58:47] with GNAT version [Community 2019 (20190517-83)]
ERROR: alr version unsuccessful
```

Doing the same from withing the source directory works (same for `alr get` and `alr run`):

```sh
alr search hangman
NAME     STATUS  VERSION  DESCRIPTION                   NOTES
hangman          1.0.0    Hangman game for the console
```

Seems like something basic is going wrong here. Ideas?

**Comment by mosteo** [comment]
I can't reproduce over here, so could you provide the output of some failing command with `-vv -d` extra switches (I'll add this info to the beta page)?

Also, the output of `alr index --list` might be useful.

**Comment by senier** [comment]
The `-vv -d` switches helped solving the mystery. The issue was that GNAT was not in PATH:

```sh
-->> Spawning: gnat  > GNAT-TEMP-000001.TMP
-->> Process errored with code 1 and output: 
ERROR: alr get unsuccessful
```

I have some magic in my bash configuration that adds GNAT to the PATH only when a `.gpr` file is present in the current directory. That's why it seemed to work only in the alire repo.

As an enhancement, `alr` should complain explicitly about missing executables.

**Comment by mosteo** [comment]
Yup. We had this check for gnatmake but at some point it was removed because it seems gnatmake is not really required for cross-compilation. Anyway we should report this better, and certainly not as an obscure error. Thanks!
