### ISSUE TITLE
Location of binaries

### ISSUE THREAD

**Issue by senier** [alire-project/alire#238]
The catalog format description states that executables can be specified as follows:

```
executables = ["bin/my_main"]
```

When doing that, however, `alr` says:

```
Project sxml builds these executables:
ERROR: invalid simple name "obj/benchmark"
ERROR: alr encountered an unexpected error, re-run with -d for details.
```

The project file has `Object_Dir` set to "obj". It works when removing the path. How is that supposed to work?

**Comment by mosteo** [comment]
Binaries are to be given without path. If the docs say otherwise that's a bug there.

The rationale is that binaries can appear in different places depending on the build scenario, so that's why they're looked for dynamically.
