### ISSUE TITLE
Handling of multiple binaries

### ISSUE THREAD

**Issue by senier** [alire-project/alire#239]
I have a simple project file:

```sh
$ cat FOO.gpr 
project FOO is
   for Source_Dirs use (".");
   for Object_Dir use "obj";
   for Main use ("bar.adb", "baz.adb");
end FOO;
```

The toml file has the following additions to the default template:

```sh
project-files = ["FOO.gpr"]
executables = ["bar", "baz"]
```

Both executables are found after compiling:

```sh
$ alr run --list
Project foo builds these executables:
   bar (found at alire/build/obj/bar)
   baz (found at alire/build/obj/baz)
```

But running yields:

```sh
$ alr run
Warning: Executable "foo" not found
ERROR: alr run unsuccessful
```

When removing the second binary, bar is executed. Seems like `alr` uses the configured binary when only one is present, but falls back to the project name when multiple binaries are present.

* Is there a way to set the default binary to run on `alr run`?
* I wonder why binaries need to be configured in the catalog at all - couldn't this be derived from the project file's `for Main use (...)`?

**Comment by mosteo** [comment]
> When removing the second binary, bar is executed. Seems like `alr` uses the configured binary when only one is present, but falls back to the project name when multiple binaries are present.

Yes, I double-checked with the source and this is how it's working. Defaulting to an undeclared executable is a bug.

> * Is there a way to set the default binary to run on `alr run`?

Not currently. Closest thing to a workaround is to say the executable you want to run, e.g. `alr run baz`. We could make the first declared executable the default one, with trivial changes to code.

> * I wonder why binaries need to be configured in the catalog at all - couldn't this be derived from the project file's `for Main use (...)`?

Having executables in the catalog allows e.g. `alr show` to work without having to download anything beyond the index. More generally, this way users can query the catalog without requiring further downloads or going online. This is also used while generating the website, for example.

We might parse the GPR file in `alr publish` to extract executables automatically and simplify publication, though.

**Comment by senier** [comment]
> Yes, I double-checked with the source and this is how it's working. Defaulting to an undeclared executable is a bug.
> Not currently. Closest thing to a workaround is to say the executable you want to run, e.g. `alr run baz`. We could make the first declared executable the default one, with trivial changes to code.

I have no strong opinion here. Running the first executable in the list instead of stopping even though executables are configured may give a better user experience.

> Having executables in the catalog allows e.g. `alr show` to work without having to download anything beyond the index. More generally, this way users can query the catalog without requiring further downloads or going online. This is also used while generating the website, for example.

That makes sense, thanks for the explanation.

> We might parse the GPR file in `alr publish` to extract executables automatically and simplify publication, though.

Good idea.

**Comment by Fabien-Chouteau** [comment]
I would say that when there are mode than one executable and the user doesn't specify which one should be run, `alr` should print the list of exe and exit with an error.
