### ISSUE TITLE
Spawn: use array of strings for arguments

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#253]
Since the different `Spawn` functions in `Alire.Os_Lib.Subprocess`  take the command line as a string and then split it with `System.Os_Lib.Argument_String_To_List` we have to be careful with white-spaces in paths. Having a space in my Windows user directory, I notice a few problems when spawning `tar` and `git`.

It seems like directly using an array of string to pass the arguments to `Spawn` would make this easier to handle in the code.

**Comment by mosteo** [comment]
So, with #252, we should converge to a single `Checked_Spawn` that takes an array of strings, right?

**Comment by Fabien-Chouteau** [comment]
I think so.

The problem is that arrays of strings are a pain in the back in Ada. Maybe String vector is better.

Also it looks like `Alr.Os_Lib` also has subprocess function that should be replaced.

**Comment by mosteo** [comment]
Yep, that's why `Alire.Utils.String_Vector` has chained ops so it can be used in place: `Empty_Vector.Append ("foo").Append ("bar")`. Still a bit verbose...

**Comment by Fabien-Chouteau** [comment]
The Ada 202x container aggregates will be nice in that situation. But let's not wait for that to refactor.

**Comment by mosteo** [comment]
Fixed by #255.
