### ISSUE TITLE
[RFC] Windows ecosystem for Alire

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#276]
Now that we have stable Windows builds I started to try and use `alr` on Windows for my projects.

Doing so I faced many difficulties related to the availability of tools such as `wget`, `make` and `tar`. Not only these tools are not available by default on the system, they also have different behavior depending on where you get them (`wget --force-local` for instance). 

This makes me wonder if we should consider that `alr` has to be used within the context of a Windows system "package manager" such as `Chocolatey`, `Mysys2` or `Cygwin`.

There is also the question of distributing `alr` using those package managers.

**Comment by mosteo** [comment]
I imagine we could try to move to library versions of such dependencies, being able to provide a self-contained `alr` executable. At some point I tried to do that for `git` but it's not simple, and would impact the building process.
An advantage of using a known environment for Windows would be that crates could count on it being available to them, too.

**Comment by Patschkowski** [comment]
vcpkg :)

**Comment by Patschkowski** [comment]
I also ran into the tar.exe issue on Windows, but after adjusting my PATH to point to msys running the hello example works fine for me - good job!

**Comment by Fabien-Chouteau** [comment]
Thanks for the feedback @Patschkowski.

**Comment by Fabien-Chouteau** [comment]
I am looking into this again. Msys2 looks like the most interesting ecosystem at this point.

One possible integration I see is:
 - `alr` detects if `Msys2` is installed
 - If it is not installed, `alr` can install it (after a query to the user)
 - `alr` adds `Msys2` paths into it's environement
 - `alr` can now install and use packages from `Msys2`

**Comment by Patschkowski** [comment]
Hi Fabien,

because I would like to see PolyORB also as an alire crate I agree that msys2 should be used :)

Regards,
Felix

**Comment by Fabien-Chouteau** [comment]
> because I would like to see PolyORB also as an alire crate I agree that msys2 should be used

What is the link between PolyORB and Msys2?

**Comment by Fabien-Chouteau** [comment]
For those interested (@Patschkowski ?), I worked on msys2 support here: #336 .

**Comment by Patschkowski** [comment]
Hi @Fabien-Chouteau , I will try to reserve some time this week to have a look at it.

**Comment by Fabien-Chouteau** [comment]
Alire now installs its own `msys2` and use it for external crates and required tools (git, tar, etc.).
