### ISSUE TITLE
[RFC] Defining bundled libraries in the index

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#297]
It has already arisen a few times (last one: alire-project/alire-index#73) that GNAT CE versions bundle a bunch of libraries with it, which are missing in other versions. This needs some way of making it explicit or we find ourselves with releases that either are compiler-specific or declare dependencies that will be downloaded even when already bundled with the compiler.

In an abstract level, the idea is that if e.g. GNAT 2019 is available, we know that a particular set of other crates' releases are too, and they should be available for dependency resolution (but without the need to deploy).

I have not a proposal for this right now so this is to track the issue. One possibility would be adding it to the `external` kind (if we go that way, #295) used for compiler detection. When creating the detected compiler release, we could create the rest of related crates releases.

**Comment by mosteo** [comment]
Hi @Fabien-Chouteau , I've been looking around the installation folders of GNAT CE 2019 and couldn't find anything evident where this information could be automatically obtained. I see the project files in `/share/gpr`, but not even these contain the library version. Do you know if I'm missing something, or this information is simply not available there? Thanks!

**Comment by Fabien-Chouteau** [comment]
There is no other version number than 2019.

But you should not spend time going in that direction because we plan to make these bundled libraries available in Alire, so it doesn't matter if they are shipped with the compiler or not.

**Comment by mosteo** [comment]
OK, thanks. Closing then.
