### ISSUE TITLE
Double `alr with` corrupts the session

### ISSUE THREAD

**Issue by pmderodat** [alire-project/alire#310]
It has happened to me several times over the last months, but I’ve found a way to reproduce only now:

```sh
$ alr init foo --bin
$ cd foo
$ alr build
[build succeeds]
$ alr with libhello
$ alr build
[build succeeds]
$ alr with libhello
ERROR: Cannot continue with invalid session: Failed to load /tmp/foo/alire/foo.toml: dependency version must be a string
ERROR: alr with unsuccessful
# Oh no! It’s corrupted!
$ alr build
ERROR: Cannot continue with invalid session: Failed to load /tmp/foo/alire/foo.toml: dependency version must be a string
ERROR: alr build unsuccessful
$ alr with --del libhello
ERROR: Cannot continue with invalid session: Failed to load /tmp/foo/alire/foo.toml: dependency version must be a string
ERROR: alr with unsuccessful
```
Once you got there, the only way out I found was to manually edit `alire/foo.toml` to remove the problematic entry for `libhello`.

**Comment by stcarrez** [comment]
I'm facing this issue quite often too.

It would be nice if the project toml file is updated only when the with command succeeds, or, that some automatic rollback is made (there is already a backup file with .prev prefix).
