### ISSUE TITLE
Website: Show short description after name in crates view

### ISSUE THREAD

**Issue by Jellix** [alire-project/alire#312]
Looking at https://alire.ada.dev/crates.html, it is sometimes hard, impossible or even misleading to infer from a project name what it might be about, so maybe the short description could be shown next to the name?

So, instead of having just things listed like

* Basalt
* Geste

which leaves the user pretty much guessing what this thing is about, add the short description next to it:

* Basalt - Collection of formally verified building blocks
* Geste - GEneric Sprite and Tile Engine

Possibly related to #185, but I would assume that the short description is enough to make you click on an interesting crate and then you'll have the full information anyway.

**Comment by Fabien-Chouteau** [comment]
Thank you @Jellix, it a good idea!

I implemented it: https://alire.ada.dev/crates.html
