### ISSUE TITLE
[RFC] Security of git commit hashes as proof of integrity

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#315]
Hi @senier, @Fabien-Chouteau told me that you had discussed again the viability of relying on git commit hashes for integrity validation. Do you have a consensus, or want to bring me up to speed on your latest thoughts?

**Comment by Fabien-Chouteau** [comment]
@senier I don't know if we actually talked about this. But we had a few conversation within AdaCore.

The main question is the trade-off between security and ease of use. Archives and sha512 are very annoying to do and raise the barrier of entry.

**Comment by senier** [comment]
@Fabien-Chouteau @mosteo No, we didn't talk about this lately. Can you elaborate on the complications you're referring to? I guess it's about being forced to have an archive and the inability to use a git repo directly?

**Comment by mosteo** [comment]
Sorry @Fabien-Chouteau , I misunderstood you then.

@Fabien-Chouteau , if the problem is with ease of use, further work with `publish` could take care of that. I see that as kind of prioritaire already.

@senier Yup, having to zip, hash, upload... instead of simply copying the URL and hash.

**Comment by Fabien-Chouteau** [comment]
> @Fabien-Chouteau , if the problem is with ease of use, further work with `publish` could take care of that. I see that as kind of prioritaire already.

We can improve but it will take a lot of time and work. If we could allow this in the meantime.

**Comment by mosteo** [comment]
No objection on my part, and we are still in beta anyway.

**Comment by Jellix** [comment]
> @Fabien-Chouteau , if the problem is with ease of use, further work with `publish` could take care of that. I see that as kind of prioritaire already.
> 
> @senier Yup, having to zip, hash, upload... instead of simply copying the URL and hash.

I've actually used [Online Convert](https://hash.online-convert.com/sha512-generator) which also takes an URL as argument. Comes close. And you can hash after uploading. That, of course, implies you trust your service provider to not change the content of your archive in transit.

**Comment by mosteo** [comment]
I just stumbled into this, which seems to squarely address our same concerns about using commit hashes:

https://github.com/cgwalters/git-evtag

Alas, it isn't going to be in git any time soon:

https://public-inbox.org/git/1515442320.3241451.1228399576.66D7DA96@webmail.messagingengine.com/T/#u

It seems that until the transition away from sha-1 isn't completed there won't be a total guarantee. Although at

https://git-scm.com/docs/hash-function-transition/

one can read

> Git v2.13.0 and later subsequently moved to a hardened SHA-1 implementation by default, which isn’t vulnerable to the SHAttered attack.

**Comment by Fabien-Chouteau** [comment]
We decided to allow git commit URL in the community index, but only from a list of trusted host services (GitHub, GitLab, etc.).
