### ISSUE TITLE
Use Alire in an offline environment

### ISSUE THREAD

**Issue by rveenker** [alire-project/alire#317]
In the FOSDEM 2020 presentation, Alire was demonstrated offline. I would like to also setup Alire on a standalone offline machine.
I noticed that in alr-defaults.ads, the github URI's are hardcoded. I tried specifying a local file URI but without success. (Keep getting 'Not a readable directory')
Perhaps these URI's could be moved to a TOML configuration file?

**Comment by stcarrez** [comment]
You can add your local repository by using the **alr index** command.
I've done this to setup my own local repo:
```
alr index --add=`pwd` --name local
```

Then, **alr index --list** should give you the repository list.

**Comment by rveenker** [comment]
Thanks, that worked.
I just had to add a new index.toml file in the new index directory containing 'version = "0.1" '
But now the alr commands are working :-)

**Comment by rveenker** [comment]
I am reopening this issue because I am still unable to add new crates to the local index.
The added 'local' index is not used apparently. 

> alr index --list
# name  URL                      PATH
1 local file://d:\alire-index  d:\alire-index
 
> alr list
No hits    .

Please advise on how to add a crate to this local catalog.

**Comment by rveenker** [comment]
Solved the problem!
I had created the toml file in the wrong directory.
