### ISSUE TITLE
alr build always looks for system packages

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#341]
It seems like this is not a necessary step once the system package is installed by either `alr get`, `alr with` or `alr update`.

Looking for system packages can take a lot of time, even if they are already installed. At least it is the case with the current implementation on Windows msys2.

**Comment by mosteo** [comment]
This is a consequence of not having a lockfile yet (#251). I'd say this is fairly high in the list of priorities.

**Comment by Fabien-Chouteau** [comment]
On windows with msys2 `alr build` and `alr run` are very slow because of this. When there are system dependencies of course.

**Comment by mgrojo** [comment]
It seems this is no longer done, at least on Ubuntu. See https://matrix.to/#/!DNeiNadAgLpbmdDKov:gitter.im/$RKiTbq_VJR3At1Z-N-aAynMm9lZCRB3lrhaGb5K2qgg?via=gitter.im&via=matrix.org&via=attendees.fosdem.org

Maybe you can close this, if this is the behaviour you want out of performance criteria.

**Comment by mosteo** [comment]
Thanks for bringing this up. Closing as it was implemented long ago (#355).
