### ISSUE TITLE
Should crate set PATH=lib_dir on Windows?

### ISSUE THREAD

**Issue by reznikmm** [alire-project/alire#354]
I've tried to use Matreshka library with `alire` on `msys2` Windows shell. It seems it works fine, but compiled test executable is unable to file matreshka *.DLL's.

So, my question is: Should `matreshka` crate export PATH environment on windows or we could invent something in `alire` to deal with this common Windows specific problem?

**Comment by mosteo** [comment]
Hi Maxim, thanks for the report. There's a proposal about setting env vars in #345. I guess that would do for this case?

**Comment by reznikmm** [comment]
It seems #345 talks about environment _during_ crate building, while here we need an environment to be used _after_ the build (if this difference matters). May be to be emitted with `alr setenv`. Also I don't know how to calculate the value of the PATH, in my case it's `<current_dir>/alire/build/alire/cache/dependencies/matreshka_league_18.1.0_4fab6c03/.libs/`.

**Comment by mosteo** [comment]
Yup, that should be emitted by `alr setenv` and also be used by `alr build`/`alr run`. The paths should be specified as relative to the crate somehow, so in your case you would use (for example) `"$crate_root/.libs".

At present we don't distinguish building and running contexts; neither testing/releasing. I guess that's something that may be necessary eventually.

**Comment by reznikmm** [comment]
So, each crate, that provides DLL-s on Windows should export `PATH` environment variable to point place where DLL-s are located, right?

**Comment by mosteo** [comment]
Yes. You can set paths relative to your crate directory by using `${CRATE_ROOT}` in the manifest, see the entry on [environment](https://github.com/alire-project/alire/blob/master/doc/catalog-format-spec.md#release-information).

Furthermore, in the master branch you can use `alr exec -- your_command` to run any script or executable within the same environment printed by `alr printenv`.

I'm closing this one now as https://github.com/alire-project/alire/pull/452 implemented the required functionality for this to work.
