### ISSUE TITLE
Save dynamic expressions on TOML export

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#358]
Currently there is a loss of information on crate saving, because dynamic expressions are resolved for the current environment.

There is not a clear short-term need for this. If we want to move progressively to full manipulation of crate files through alr commands it might become necessary. This might be helpful for the publishing process perhaps.

**Comment by Fabien-Chouteau** [comment]
@mosteo is this still relevant?

**Comment by mosteo** [comment]
I don't think so. We still generate a manifest during `alr get`, but that one is not intended to go back into the index. And we could replace this generation with copying the manifest from the index anyway.

If we needed the feature in the future it can be reopened at that time.
