### ISSUE TITLE
Report the expected alr index version when an older local index is found

### ISSUE THREAD

**Issue by stcarrez** [alire-project/alire#366]
After upgrading to a new *alr* version, I'm getting the following error:

```
ERROR: xxx/index/index.toml: index version is older than that expected by alr. Please update your local index (alr index --update-all)
ERROR: alr list unsuccessful
```

Of course some repository format changed and the suggested command will never
work for your own local repository. At least it would be nice to print the expected version number.

**Comment by mosteo** [comment]
I understand, thanks for the report.
