### ISSUE TITLE
alr list vs alr search --list

### ISSUE THREAD

**Issue by stcarrez** [alire-project/alire#369]
There are two ways to list the available packages:

```
alr list
```
and
```
alr search --list
```
Both commands have different outputs.
I would suggest to avoid duplicating ways to list things.
By the way, the output produced by the search is far more useful since you know the package version.

**Comment by mosteo** [comment]
The original reason for that separation is that `list` acts on crates and `search` on releases. I guess both could be folded into one adding a `--releases` switch for example.

**Comment by ghost** [comment]
`alr search --list` was accurate when it comes to crate installation availability for me.

Hopefully, ncursesada will be available for OpenSuSE x86_64 platform soon.

**Comment by mosteo** [comment]
For this one I would propose to simply rename `alr list` to `alr crates`
