### ISSUE TITLE
alr with to show all dependencies

### ISSUE THREAD

**Issue by stcarrez** [alire-project/alire#371]
When you run the command:
```
alr with
```
it gives you the list of crate that you project is using. There is nothing about other crate dependencies.

In previous versions of Alire, it was easier to find out all the libraries that are used, I was looking
at the generated GPR file and it helped me.  With the removal of that, it's harder.

Now the `alr with` command could be improved to show the dependencies of the current project.
May be with some new option:

```
alr with --print
```
You could even print that as an acyclic graph :-)

```
alr with --print-graph
```
It would be nice that it also prints out the version number used for each crate.

**Comment by mosteo** [comment]
While inside your alire-aware project, you can get that information with `alr show --solve`, which will itemize your direct dependencies, the complete solution, and the acyclic graph.

If you have `graph-easy` in your path (in ubuntu/debian you have it in `libgraph-easy-perl`) the graph will be formatted in ASCII art.

Perhaps we could show only this part of the information of `alr show` in `alr with` too.

Thanks for all the reports, btw.

**Comment by mosteo** [comment]
I just opened #373 because testing my suggestion above hit that bug. You can still what would be the expected output of `alr show` using a remote crate as argument: `alr show hello --solve`, for example.
