### ISSUE TITLE
xmlada crate breaks the build and further integrations in Alire index

### ISSUE THREAD

**Issue by stcarrez** [alire-project/alire#380]
The current `xmlada` crate breaks the build if you use it.
I've manged to remove it locally because xmlada is provided by GNAT 2019.
But, this fails on the automated build when a pull request is proposed on the Alire index.

All the pull requests I've made on Alire index are now marked as failed because they use `xmlada`.

Is there any way to fix that?

```
/users/runner/runners/2.169.1/work/_temp/gnat-community-2019-20190517-x86_64-darwin-bin/bin/gcc -c -x ada -gnatA -g -O2 -O2 -gnatn -gnatwU -gnatec=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/GNAT-TEMP-000003.TMP -gnatem=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/GNAT-TEMP-000007.TMP /Users/runner/runners/2.169.1/work/alire-index/alire-index/ado_2.1.0_6acf616c/alire/cache/dependencies/xmlada_16.1.0_a2d45474/input_sources/input_sources.adb
input_sources-http.adb:194:07: missing argument for parameter "Level" in call to "Set_Socket_Option" declared at g-socket.ads:1283

   compilation of input_sources-http.adb failed

gprbuild: *** compilation phase failed
```

**Comment by mosteo** [comment]
It seems in the future things will be simpler as these projects will be provided as regular crates (see #alire-project/alire#297).

Right now, I can see two short-term possibilities (untested, so I'd need to experiment):

1. Don't depend on xmlada and instead depend on compiler versions that bundle the version you need.
1. We update the xmlada crate with a newer version that doesn't cause these errors. This is probably more future-proof.

**Comment by stcarrez** [comment]
Yes, I'll remove the dependency on xmlada. I have a similar issue with AWS anyway.
Thanks!

**Comment by mosteo** [comment]
Closing, as AdaCore has already indexed the `xmlada` crate with sources valid for all compiler versions tested by Alire.
