### ISSUE TITLE
Ensure alr build checks and download dependencies first

### ISSUE THREAD

**Issue by ghost** [alire-project/alire#426]
Hi. I have an existing local project that was initialized with `alr init`, and specified used dependency already (i.e, utilada_curl). 

However, if I want to build it without existing `alire/cache` and `alire/build`, it will give me this error

```
==============Messages for file: /home/momozor/quicklisp/local-projects/nl/ada/nzping/nzping.gpr
     1. with "utilada_curl";
             |
        >>> unknown project file: "utilada_curl"
gprbuild: "nzping.gpr" processing failed
error: Compilation failed.
```

It seems `alr build` tries to build the project first before installing dependencies specified in the specification TOML file.

Am I missing something here?

Thanks.

**Comment by mosteo** [comment]
Hi @momozor, I would need a more detailed sequence of the steps you did. For example, how did you add the dependency? If I do `alr with utilada_curl`, it already downloads the required project. After that and adding the `with "utilada_curl";`, issuing an `alr run` will build the necessary sources.

We are working on streamlining this two-step process so `alr with` will take care of also updating your project file (#313).

The alternative way is to update by hand also the `alire/crate.toml` file to add the dependency, and then issuing an `alr update`. The extra `alr update` didn't use to be necessary, so this is actually a regression. Maybe this is what you did?

**Comment by mosteo** [comment]
Note to self: check that whenever `crate.toml` is younger than `crate.lock`, we need an implicit update.

**Comment by ghost** [comment]
@mosteo 

I apologize for not being clear enough.

I just wanted to build a fresh project that uses alr.

For example, if I git clone https://github.com/momozor/nzping (which already uses alr and has specified dependencies) and tries to run `alr build` inside the project, it will return the same error.

```==============Messages for file: /home/momozor/quicklisp/local-projects/nl/ada/nzping/nzping.gpr
     1. with "utilada_curl";
             |
        >>> unknown project file: "utilada_curl"
gprbuild: "nzping.gpr" processing failed
error: Compilation failed.
```

It worked fine when I start a totally new project from scratch with 

-  `alr init --bin`
- `alr with utilada_curl`
- `alr build`

-----
For example, with Rust's cargo, I could just download a random Rust project, and run `cargo build` and expect the dependencies to download automatically and build correctly.

I'm not sure if `alr build` does the same thing similar to `cargo build` in this case (which is pretty convenient).

**Comment by ghost** [comment]
The workaround that works for me currently - 

1. git clone https://github.com/momozor/nzping and cd into the project
2. Remove `alire/nzping.lock` and remove `utilada_curl` dependency line from `alire/nzping.toml`.
3. Run `alr with utilada_curl`
4. Run alr build

**Comment by mosteo** [comment]
I see. You're cloning a project that has the `alire` folder checked in (which isn't supposed to be done for now, for reasons. Another known shortcoming with a solution in the roadmap).

It should suffice to delete the `*.lock` and running `alr update`, without re-adding dependencies. 

This problem is related to alire-project/alire#240.

> I'm not sure if alr build does the same thing similar to cargo build in this case (which is pretty convenient

Eventually, yes, they should be equivalent.

**Comment by ghost** [comment]
Thanks for the tips.
