### ISSUE TITLE
Docker with `alr` preinstalled

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#43]

**Comment by mosteo** [comment]
So curious users can test it without installing.

Not to be confused with #161, which is intended to allow crate packagers to test a release with the official docker images before submitting it.

**Comment by onox** [comment]
If I just want to know if `alr build` would work, is this the issue that tracks it? I'm looking to migrate from Shippable to GitHub Actions. Is it possible to support monorepo's that host multiple crates as well?

**Comment by mosteo** [comment]
> If I just want to know if alr build would work, is this the issue that tracks it?

I think #161 is the one you want. In fact, this one does not make much sense anymore since we have appimages that serve the same purpose.

> Is it possible to support monorepo's that host multiple crates as well?

At present, these crates would have to be submitted as source archives with only the relevant subfolder contents. Or you could do some trickery with branches to prepare each release; not sure how involved that would get.

**Comment by mosteo** [comment]
Closing; anyone wanting to play with `alr` can use the prebuilt binaries in every pull request, besides the releases.
