### ISSUE TITLE
Poor UX on `alr init` if you change what the main procedure is called

### ISSUE THREAD

**Issue by esthermations** [alire-project/alire#430]
I basically just ran into this situation:

- Create a new project using `alr init --bin my_project`
- Edit the TOML to set my information
- Change the main procedure from `my_project.adb` to `my_project-main.adb` and sort out gprbuild and etc
- Attempt to run my hello world example using `alr run`
- Alr can't find the executable because it expects it to be called `my_project` even though that wasn't written anywhere
- I have to look at the docs, use `alr run -v` to see a suggestion to define executables in my TOML file, then look up the TOML spec here to figure out how to get `alr run` to work

I think most of this could be circumvented by just adding an `executables = "my_project"` line in the `[general]` section of the generated TOML files, so people realise they need to set it / can change it, right when they're first setting up their project.

Also, alr should possibly check the project's .gpr files for a `for Main use (...);` line to guess where the exe might be.

Thanks!

**Comment by mosteo** [comment]
Hello, Esther, thanks for the feedback. Definitely we have many rough corners that unfortunately right now are taking back seat to missing core features. Eventually we should get around to improve these aspects.

**Comment by esthermations** [comment]
No worries at all! I just thought I'd record this experience as an issue before I forget. Thanks for the hard work!

**Comment by mosteo** [comment]
Once #547 is merged, the initial manifest will contain the executable property for binary projects, increasing visibility of this property.
