### ISSUE TITLE
CI for v2018

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#44]

**Comment by reznikmm** [comment]
There is [docker image](https://hub.docker.com/r/reznik/gnat/) for gnat community 2018 if you need it. It's on the same Docker image but with new tag: **gpl.2018.slim**

It contains just GNAT compilers with any libraries (XMLADA, GNATCOLL, etc) stripped.

**Comment by mosteo** [comment]
Didn't realize this was fixed already with commit 58e00277d4ccbbdf7a38c1317dc0579c32a86933.

@reznikmm Indeed your image came in handy, specially since there doesn't seem to be a headless installer for gnat 2018. Thanks!

**Comment by pmderodat** [comment]
@mosteo Just in case it’s useful to you in the future: GNAT 2018 _does_ have a headless installer: https://github.com/AdaCore/gnat_community_install_script

**Comment by mosteo** [comment]
Ah - yes it is (or will be, for 2019). I didn't think to look there, only checked on the libre website.
