### ISSUE TITLE
Document configuration keys

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#445]
PR #443 is the first one to take advantage of the stored configuration, and likely we will have many more to help with the publishing workflow.

At some point we may want to document configuration entries with their type/purpose. Ideally, it should be done in a way that we can reuse for the website and `alr`. Perhaps a collection from which we can both create a topic for `alr help` and markdown for the website.

**Comment by Fabien-Chouteau** [comment]
I am already working on this.
