### ISSUE TITLE
gnatcoll 2018 doesn't compile

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#45]
Errors during compilation:

gnatcoll-projects.adb:3429:24: "String_Vectors" is undefined (more references follow)
gnatcoll-projects.adb:3444:10: invalid prefix in selected component "Mains_Str_List"
gnatcoll-projects.adb:4991:23: "Expression" not declared in "Proc"

**Comment by pmderodat** [comment]
Hello @mosteo 
With what compiler have you tried this? GNATCOLL 2018 was built an tested only with GNAT Community 2018.

**Comment by mosteo** [comment]
Ah - you're right, this was with 7.3. I'll add an exclusion then.
