### ISSUE TITLE
Changes to remote and local manifests for a simpler publishing workflow 

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#473]
From the discussion in #466, @Fabien-Chouteau proposes two related changes to the format of the manifest (I hope not to mischaracterize anything):

- Locally, the manifest contains current information of the working release.
   - No need to specify the information below the version key, everything can be moved to top-level
   - Some fields can be omitted to avoid confusion, like `origin`, since they don't apply to the local code.

About this one I entirely agree. A question is: what happens with the `[general]` table? Should it simply be merged with the rest of fields in the release? 

- Remotely, each release is stored in a single file, as e.g. OPAM does. 

I'm not totally sure we need this one, as long as we get rid of the `[general]` table or, at least, fields in it that modify the behavior of several releases (dependencies, project files...). That is, every release is self-contained. As a counterpoint, Cargo uses a single file per crate, with the info of all releases, but it doesn't seem to have a common section.

So about this one, @Fabien-Chouteau , what was your idea on the common information? Store it with every release, keep it in an extra file per crate, ...? Since this affects the checks on ownership that you implemented, you may have already given this some thought.

**Comment by Fabien-Chouteau** [comment]
> About this one I entirely agree. A question is: what happens with the `[general]` table? Should it simply be merged with the rest of fields in the release?

I would say remove `[general]` level.

> So about this one, @Fabien-Chouteau , what was your idea on the common information? Store it with every release, keep it in an extra file per crate, ...? Since this affects the checks on ownership that you implemented, you may have already given this some thought.

I think it will be easier to store it with every release, one file per release and that's it.

Maybe later we will find that we need something else, maybe deltas from one release to the other, but for now it seems like the best option.

**Comment by mosteo** [comment]
Understood, then everything is clear. Since we have a few tricky patches ahead of us, I think I'll open any PRs as empty drafts as soon as I start work on them so you can see in advance where things are going.

**Comment by mosteo** [comment]
Implemented by #505.
