### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by jquorning** [alire-project/alire#483]
How to get in the air: Simplify and add lightness!

**Comment by Fabien-Chouteau** [comment]
Hello @jquorning ,

I am not sure to understand your question. Are those Ada libraries?

**Comment by jquorning** [comment]
G’day mate

> Den 27. jul. 2020 kl. 11.14 skrev Fabien Chouteau <notifications@github.com>:
> Hello @jquorning ,
> 
> I am not sure to understand your question. Are those Ada libraries?
> 
Maybe more like a collection of unstandardized frameworks i may be working on. It’s gonna be huge!

**Comment by Fabien-Chouteau** [comment]
The current instructions are available here: https://alire.ada.dev/docs/#publishing-your-projects-in-alire
You can also look at the existing .toml files in the index.

And of course don't hesitate to ask for help. 

Note that the process of publishing libraries is probably going to change in the short term.

**Comment by jquorning** [comment]
> Den 27. jul. 2020 kl. 12.00 skrev Fabien Chouteau <notifications@github.com>:
> 
> 
> The current instructions are available here: https://alire.ada.dev/docs/#publishing-your-projects-in-alire <https://alire.ada.dev/docs/#publishing-your-projects-in-alire>
> You can also look at the existing .toml files in the index.
> 
> And of course don't hesitate to ask for help.
> 
> Note that the process of publishing libraries is probably going to change in the short term.
> 
Sorry - I would just like to thank you on your big work with the Alire package manager tool suite.

When will the next release be due?

 
—
Jesper Quorning
Brovej 18
8543 Hornslet
jesper.quorning@gmail.com

**Comment by Fabien-Chouteau** [comment]
> When will the next release be due?

The first binary release is planned for the end of the year.
