### ISSUE TITLE
Where to put toml and lock files

### ISSUE THREAD

**Issue by NicolaiRuckel** [alire-project/alire#497]
I want to add our project to Alire but I'm still a bit confused on how to prepare my repository for that.
My plan was to write a CI job that creates the releases automatically instead of creating the archive manually. The documentation states that the `alire` folder should be excluded from the zip file though which makes that non-trivial since the default release would include that folder. Is it really correct to exclude the whole folder from the archive? I mean, I need the `toml` and `lock` file in the VCS, otherwise it had to be recreated for every release. Is there a suggested workflow for that? I looked at other projects on the Alire index and they all seemed to just omit those files but that looks very strange to me.

**Comment by mosteo** [comment]
Hi Nicolai,

we're on the verge of merging a refactoring of exactly these things, to clarify the workflow for users and publishers.

At this time there's no problem with putting both files under VCS at their current location, despite the recommendation. After the changes go in (that will be when we merge the `merging/big-refactor` branch, ETA by the end of next week I'd say) these two files will be at top-level and suggested to be put under VCS. The `alire` folder will remain for temporary/reconstructible data and should be ignored for VCS. There are a number of PRs dealing with these changes, but the concrete one about that is #494, if you're curious.

**Comment by mosteo** [comment]
Hi Nicolai,

the changes I talked about are now merged (#505), and they should address your question. Please comment if you find any problems.

See here: https://github.com/alire-project/alire/wiki/2020-Metadata-format-migration for a summary of the changes.
