### ISSUE TITLE
Re-enable crate testing per CI platform

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#510]
The `alire-crates-ci` is currently disabled because it was timing out. It should be re-enabled to help with getting the big picture of what crates are failing in what platforms (specially when there are distro version bumps). There's work already done so only one crate is tested per run, but this is yet untested.

Consider sustainability given GitHub Actions quotas.

**Comment by mosteo** [comment]
Did a little research on Travis quotas and just this month they switched they pricing plans. The ~free~ trial OSS tier provides now 10_000 ~monthly~ credits, i.e., [1_000](https://docs.travis-ci.com/user/billing-overview/#usage---credits) minutes.

**Comment by mosteo** [comment]
I got this (mostly) working again. @Fabien-Chouteau , right now I'm generating an individual report per release, and aggregating problems per platform: https://github.com/alire-project/alire-crates-ci

This raw information is already useful to locate failing crates, so we might leave it at that.

Another possibility would be to integrate some of this info in the website, or have a separate website with some reports.

**Comment by Fabien-Chouteau** [comment]
:+1: In the future we could check to integrate that in the main website.

**Comment by mosteo** [comment]
Just this week-end I played a bit with jekyll, shamelessly ripping off our official site. I didn't want to break anything so it's done in the GH pages of the crate testing repo: https://alire-project.github.io/alire-crates-ci/

**Comment by Fabien-Chouteau** [comment]
What we should do is to have the action create one or several json file in the repo, and then the website will take data from that.

**Comment by mosteo** [comment]
I have the info to generate badges ready. I think we can add just the badges to the main site and leave the reports where they are for the curious ones.

Could you please @Fabien take a look at the badges at e.g. https://alire-project.github.io/alire-crates-ci/crates/adayaml.html ? I know they're a bit verbose but I think it is important to show both distro and compiler version.

**Comment by Fabien-Chouteau** [comment]
For the badges would do the same as for alire.ada.dev which is to generate json files to feed into `img.shields.io`:
```
https://img.shields.io/endpoint?url=https://alire.ada.dev/badges/aaa.json
```
This way people can use this link in a README and the badge will stay up-to-date.

As far as the look of the badge, I would start from the Alr "last release" badge logo ![](https://img.shields.io/endpoint?url=https://alire.ada.dev/badges/aaa.json) and have a score for build success:
 - ![](https://img.shields.io/badge/CI-4/4-green?logo=academia&style=plastic)
 - ![](https://img.shields.io/badge/CI-2/4-orange?logo=academia&style=plastic)
 - ![](https://img.shields.io/badge/CI-0/4-red?logo=academia&style=plastic)

I am not sure if we need one badge per distro and compiler.

**Comment by mosteo** [comment]
That's certainly more compact, looks good
