### ISSUE TITLE
alr edit command

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#54]
To directly launch gnatstudio or other editors.

Current implementation is partial, only looking for `gnatstudio`. We want also the ability to open custom editors (which will require some way of defining the expected command line).

**Comment by mosteo** [comment]
Related: #379

**Comment by mosteo** [comment]
Implemented in #545.

**Comment by Fabien-Chouteau** [comment]
We can open another issue, but the current implementation is only partial. We want to support starting user defined editors.

**Comment by mosteo** [comment]
Ah, right. Let's reopen this one.

**Comment by kevlar700** [comment]
It would be nice to be able to set the editor on the fly by overriding the config on the command line, without changing the project default?

**Comment by Fabien-Chouteau** [comment]
In the dev branch we have `alr exec --` which will let you start any editor.
