### ISSUE TITLE
How to specify GPL with exception license?

### ISSUE THREAD

**Issue by reznikmm** [alire-project/alire#550]
Some packages have a GPL with GCC exception license. See [GNATCOLL](https://github.com/AdaCore/gnatcoll-core) for example. It has COPYING3 (GPL) and COPYING.RUNTIME (exception) files. The second one has a title:

> GCC RUNTIME LIBRARY EXCEPTION

Is it `GMGPL 3.0`?

**Comment by Fabien-Chouteau** [comment]
I use "GMGPL 3.0" for gnatcoll. Once we have support for SPDX (#191) it should be `GPL-3.0-or-later WITH GCC-exception-3.1`.

**Comment by reznikmm** [comment]
thank you!
