### ISSUE TITLE
Use an older glibc for the appimage?

### ISSUE THREAD

**Issue by glacambre** [alire-project/alire#560]
First, thanks for providing an appimage, it's a great way to allow painless installations.

I'm encountering a small issue though: I'm on an ubuntu machine that has glibc 2.27. The current appimage requires GLIBC_2.28. This means I can't run the appimage.

I'm not sure what the best glibc version to use is but [neovim](https://github.com/neovim) targets glibc 2.2.5 - that's pretty old but as far as I can tell it works on all my systems (old ubuntus, debian unstable and a very recent gentoo).

**Comment by mosteo** [comment]
Indeed our image is built in a `20.04` system. Thanks for raising this issue.

**Comment by mosteo** [comment]
We are building now on Ubuntu 18.04. This should also be safe for Debian stable. The alr-0.7 release now ships such an appImage, if you want to test it again: https://github.com/alire-project/alire/releases/tag/v0.7.0

I'm closing this issue for now, please reopen if you find any troubles.
