### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by Jellix** [alire-project/alire#569]
I tried to publish a remote repository, but hit

```
info: Publishing assistant: step 5 of 6: User review
stderr: SYSTEM.ASSERTIONS.ASSERT_FAILURE
stderr: failed precondition from alire-publish.adb:456
stderr: raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : failed precondition from alire-publish.adb:456
[/opt/GNAT/2020/bin/alr]
System.Assertions.Raise_Assert_Failure at s-assert.adb:46
Alire.Publish.Show_And_Confirm at alire-publish.adb:456
Alire.Publish.Start_At at alire-publish.adb:722
Alire.Publish.Remote_Origin at alire-publish.adb:880
Alr.Commands.Publish.Execute at alr-commands-publish.adb:76
Alr.Commands.Execute_By_Name at alr-commands.adb:743
Alr.Commands.Execute at alr-commands.adb:713
Alr.Main at alr-main.adb:28
Main at b__alr-main.adb:1851
[/lib/x86_64-linux-gnu/libc.so.6]
0x7f589a3980b1
[/opt/GNAT/2020/bin/alr]
0x43057c _start at ???
0xfffffffffffffffe
```

Digging a bit in the source code I then figured I should have updated the remote repository with the alire.toml as well.

That was totally my own fault, and is likely a rather special case (because it only happens as long as there's no alire.toml in the remote), but it could be nice if the error message would be a bit more user-friendly by mentioning the actual problem.

**Comment by mosteo** [comment]
Indeed that kind of errors should be properly detected and reported, as is the whole point of the `publish` command. Thanks for the report!
