### ISSUE TITLE
Installing an executable from an alire sandbox (gprinstall)

### ISSUE THREAD

**Issue by Jellix** [alire-project/alire#578]
I was just updating a project of mine to reflect the fact that it comes with Alire integration and noticed that there seems to be no intuitive way of doing a `gprinstall` from an Alire sandbox?

So, I do

```
alr get <crate>
cd <crate-directory>
alr build <crate>
```

Everything is fine until then, but doing

`gprinstall -P <gpr-file>`

doesn't work, of course, because gprinstall doesn't find any executables, because they were built in the sandbox.

And there seems to be no `alr install` command either.

What I found is that `gprinstall --relocate-build-tree=alire/build -P <gpr-file>` works.

Is that really the recommended way or should there rather be an `alr install` command for that?

**Comment by Fabien-Chouteau** [comment]
> Is that really the recommended way or should there rather be an `alr install` command for that?

There is no recommended way at the moment. This is indeed something missing in `alr`.

**Comment by mosteo** [comment]
Also take a look at #482.

**Comment by Jellix** [comment]
Ok, as there is a current solution with the option `--relocate-build-tree=alire/build` and you're having an RFC for an even more general solution, I'll close this.
