### ISSUE TITLE
Running alr without arguments also outputs an error

### ISSUE THREAD

**Issue by Irvise** [alire-project/alire#584]
When alr is run without commands or arguments, the documentation indicates:
```
Run alr without arguments to get a summary of available commands.
```
This does happen, however, before displaying the available commands, it also outputs an error at the beginning:
```
error: No command given

Ada Library Repository manager
USAGE: alr [global options] command [command options] [arguments]

[...]
```

This is in itself not wrong, but I believe this case is not an error, since this is an expected use of the tool.

Feedback and discussions on the matter are welcome.

**Comment by Fabien-Chouteau** [comment]
This sounds reasonable to me.
