### ISSUE TITLE
Better error reporting when running alr build

### ISSUE THREAD

**Issue by Irvise** [alire-project/alire#585]
When building a project with `alr build` but without the GNAT toolchain in $PATH `alr` outputs:
```
Klone nach '/home/fernando/.config/alire/indexes/community/repo' ...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 4090 (delta 25), reused 23 (delta 2), pack-reused 4028
Empfange Objekte: 100% (4090/4090), 681.35 KiB | 1.76 MiB/s, Fertig.
Löse Unterschiede auf: 100% (2488/2488), Fertig.
error: Compilation failed.
```
The last line is the error line, which currently is not very expressive.

Complete error reporting may not be possible nor desirable, however, I think better handling of some of the more common/simple cases should be had.

Since `gprbuild` and other used programs could not be available (due to setup issues or similar), `alr` should at least warn the user in a more expressive manner why the building step is failing. This will probably allow users to "debug" their issues faster and with less friction.

**Comment by mosteo** [comment]
Thanks for the report, @Irvise. #583 should fix this one.
