### ISSUE TITLE
alr publish reports strange error 'No Alire workspace found at .'

### ISSUE THREAD

**Issue by stcarrez** [alire-project/alire#594]
After adding the `tags`, `authors` and `website`, to the Alire manifest file, I've got the following strange error:

```
$ alr publish .
error: No Alire workspace found at .
```

Hopefully, the `-d` option helped, and it was caused by an invalid tag that was using upper case letters.

```
$ alr publish -d
stderr: Failed to load /src/awa/ada-awa/ada-el/alire.toml
Cannot load manifest elada, please review contents: 
Loading release from manifest: /src/awa/ada-awa/ada-el/alire.toml
tags
Tag string is not valid
stderr: Failed to load /src/awa/ada-awa/ada-el/alire.toml
Cannot load manifest elada, please review contents: 
Loading release from manifest: /src/awa/ada-awa/ada-el/alire.toml
tags
Tag string is not valid
stderr: Failed to load /src/awa/ada-awa/ada-el/alire.toml
Cannot load manifest elada, please review contents: 
Loading release from manifest: /src/awa/ada-awa/ada-el/alire.toml
tags
Tag string is not valid
stderr: No Alire workspace found at .
error: No Alire workspace found at .
```

It would be nice to have a clever error message with may be the tag string that is incorrect.

**Comment by stcarrez** [comment]
FYI, if the alire.toml file exists but has duplicate tags (or another issue), you'll get a similar error.

**Comment by Fabien-Chouteau** [comment]
I guess this message `Cannot load manifest elada, please review contents:` should not only be displayed with `-d`.

**Comment by mosteo** [comment]
Yes, we need to re-expose that the manifest is not loadable. I'll get on it once I unclog a few urgent matters.
