### ISSUE TITLE
Network Graph page should indicate which projects are in SPARK

### ISSUE THREAD

**Issue by MaxBarraclough** [alire-project/alire#603]
It would be neat if the [_Network Graph_](https://alire.ada.dev/network) page showed which projects are in SPARK, perhaps by using colour.

**Comment by Fabien-Chouteau** [comment]
Thanks for your feedback @MaxBarraclough ,

So far the only way to know if a crate is in SPARK is to use the tags declared by the contributor.

**Comment by Fabien-Chouteau** [comment]
I implemented something to provide different colors of node: https://alire.ada.dev/network

SPARK tagged nodes are in purple.
