### ISSUE TITLE
Style checks & CRLF on Windows for git origins

### ISSUE THREAD

**Issue by pmderodat** [alire-project/alire#615]
In https://github.com/alire-project/alire-index/pull/198, I’m trying to add a crate with a git-based origin. By default, the GPR project compiles with `-gnatyg -gnatwae` (it’s the dev mode). Unfortunately, on Windows, git automatically translates LF line endings to CRLF, then `-gnatyg` warns on them, and `-gnatwae` finishes to kill the build. ;-) See <https://github.com/alire-project/alire-index/pull/198/checks?check_run_id=1359857948>.

The obvious workaround is to use a source archive instead of a git checkout for the crate origin (I’m going to do that), but I suppose it would be great to make this configuration work at some point (though I have no idea how exactly): I suppose it makes sense for a lot of projects to use `-gnatyg -gnatwae` in dev mode, and to use this dev mode by default for development convenience.

Thoughts?

**Comment by mosteo** [comment]
@Fabien-Chouteau disabled that particular check for the project files generated by `alr init` (the template uses `-gnaty-d`), I guess to avoid causing this problem.

Given that both the project warnings and git behavior for line endings can be configured by a project owner, my impression is that this matter is beyond `alr` (now that we are initializing a combination that does not lead to this problem, of course).

**Comment by Fabien-Chouteau** [comment]
One problem is that someone developing a crate on Linux will only see that error when contributing to the index. It's good that we catch it, but it is late.

The other problem is that `git` doesn't provide a way to change this behavior when running `git clone`, one must first change the global configuration. Which is a bit intrusive.

I don't think we have a good solution available here. Unfortunately the answer will be: either change your compile flags or provide an archive.

**Comment by pmderodat** [comment]
I see, thanks! I’ll have to go with a source archive for now, and I guess I’ll add `-gnaty-d` for future releases.
