### ISSUE TITLE
alr publish on Windows just hangs

### ISSUE THREAD

**Issue by Patschkowski** [alire-project/alire#638]
Hi,

when I do an alr publish on my Windows machine it never gets past this point, it just hangs forever:

PS C:\lua2> alr publish                                                                                                 
Success: Local repository is clean.
Success: Revision exists in local repository (92a6a3ab85b962a24094106e8c102e4a9d16eed4).

Publishing assistant: step 1 of 6: Verify origin URL
Success: Origin is of supported kind: GIT
Success: Origin is hosted on trusted site: github.com

Publishing assistant: step 2 of 6: Verify GitHub infrastructure
Success: User has a GitHub account: Patschkowski

I tried to look it up in the alr source code. But I don't know what is causing this. Maybe the GIT connection, maybe it is waiting for some user input ... I have no clue

I would like to contribute 2 crates (Lua and AdaCore's wrapper of Lua) so I hope we can manage to work around this.

Kind regards,
Felix

**Comment by mosteo** [comment]
Thanks for the report, Felix. Windows is among our tested platforms so definitely we want this to be working. 

Time permitting, could you give us the output of `alr version`, and also run the problematic command with extra `-vv -d` flags? Thanks!

**Comment by Patschkowski** [comment]
Here you go

PS C:\lua2> alr version                                                                                                 
Alr version: 0.7.0-dev
Alire Library version: 0.7.0-dev
alr status is (valid) (0 releases indexed) (loaded in 1.149s)
config folder is C:\Users\nxp87720\.config\alire
source folder is C:\Users\nxp87720\.config\alire\alire
interaction flags are: force:FALSE not-interactive:FALSE
alr root is lua=5.4.1
alr root detection has settled on path: C:\lua2
alr is finding 2 GPR project files
alr session state is [VALID]
alr compiled on [2020-10-21 12:41:56] with GNAT version [Community 2020 (20200818-93)]
platform fingerprint: Windows Bits_64 Msys2
platform properties: MSYS2 WINDOWS NATIVE USER BITS_64
community index required branch: stable-0.4


PS C:\lua2> alr -vv -d publish                                                                                          
-->> Load config key: 'msys2.install_dir' = 'TOML_STRING'
-->> Load config key: 'user.github_login' = 'TOML_STRING'
-->> Looking for alire metadata at: C:\lua2
-->> Loading release lua=0.0.0
-->> Loading property key = description
-->> Loading property key = licenses
-->> Loading property key = maintainers
-->> Compiling email pattern...: ^[!--/-~][!-~]*@([[:alnum:]]([[:alnum:]]|-){0,61}[[:alnum:]])(\.([[:alnum:]]([[:alnum:]]|-){0,61}[[:alnum:]])){1,85}$
-->> Compiling named email pattern...: ^[^<]+ <[!--/-~][!-~]*@([[:alnum:]]([[:alnum:]]|-){0,61}[[:alnum:]])(\.([[:alnum:]]([[:alnum:]]|-){0,61}[[:alnum:]])){1,85}>$
-->> Loading property key = maintainers-logins
-->> Loading property key = name
-->> Loading property key = project-files
-->> Master load (static)
-->> Loading property key = version
-->> Valid root found at C:\lua2
-->> Looking for alire metadata at: C:\lua2
-->> Loading release lua=0.0.0
-->> Loading property key = description
-->> Loading property key = licenses
-->> Loading property key = maintainers
-->> Loading property key = maintainers-logins
-->> Loading property key = name
-->> Loading property key = project-files
-->> Master load (static)
-->> Loading property key = version
-->> Valid root found at C:\lua2
-->> Looking for alire metadata at: C:\lua2
-> Config file is not readable or doesn't exist: 'C:\lua2\alire\config.toml'
-> Spawning: ["pacman", "-V"] > GNAT-TEMP-000001.TMP
-->> Command exited with valid code: 0
-->> Looking for alire metadata at: C:\lua2
-->> Loading release lua=0.0.0
-->> Loading property key = description
-->> Loading property key = licenses
-->> Loading property key = maintainers
-->> Loading property key = maintainers-logins
-->> Loading property key = name
-->> Loading property key = project-files
-->> Master load (static)
-->> Loading property key = version
-->> Valid root found at C:\lua2
-> alr build is (valid) (0 releases indexed) (loaded in 1.312s)
-->> Looking for alire metadata at: C:\lua2
-> Using candidate alire root: C:\lua2
-> publish:
-->> Looking for alire metadata at: C:\lua2
-->> Loading release lua=0.0.0
-->> Loading property key = description
-->> Loading property key = licenses
-->> Loading property key = maintainers
-->> Loading property key = maintainers-logins
-->> Loading property key = name
-->> Loading property key = project-files
-->> Master load (static)
-->> Loading property key = version
-->> Valid root found at C:\lua2
-> Spawning: ["git", "status"] > GNAT-TEMP-000002.TMP
-> Spawning: ["git", "status", "--porcelain"] > GNAT-TEMP-000003.TMP
-->> Command exited with valid code: 0
-> Spawning: ["git", "remote"] > GNAT-TEMP-000004.TMP
-->> Command exited with valid code: 0
-> Spawning: ["git", "rev-list", "origin..HEAD"] > GNAT-TEMP-000005.TMP
-->> Command exited with valid code: 0
Success: Local repository is clean.
-> Spawning: ["git", "log", "HEAD", "-n1", "--oneline", "--no-abbrev-commit"] > GNAT-TEMP-000006.TMP
-->> Command exited with valid code: 0
Success: Revision exists in local repository (92a6a3ab85b962a24094106e8c102e4a9d16eed4).
-> Spawning: ["git", "config", "--list"] > GNAT-TEMP-000007.TMP
-->> Command exited with valid code: 0

Publishing assistant: step 1 of 6: Verify origin URL
Success: Origin is of supported kind: GIT
Success: Origin is hosted on trusted site: github.com

Publishing assistant: step 2 of 6: Verify GitHub infrastructure
Success: User has a GitHub account: Patschkowski

**Comment by mosteo** [comment]
I can reproduce it. I've narrowed it down to a call within GNAT.Expect not returning as it does on Linux. Working on a workaround.
