### ISSUE TITLE
current version of alire.toml in the repo leads to deprecated warning

### ISSUE THREAD

**Issue by yannickmoy** [alire-project/alire#640]
With a fresh checkout of alire, the first run of `alt get` got me the warning:

```
WARNING: Deprecated metadata possibly detected at /home/moy/dev/alire/alire.toml

Due to recent changes to Alire's way of storing metadata,
you need to reinitialize or migrate the workspace.
Please check here for details on how to migrate your metadata:
...
```

Possibly you want to remove or update the version of `alire.toml` in the repo?

**Comment by mosteo** [comment]
I guess that's because you ran `alr get` on a parent folder (`dev`?) of `alire/alire.toml`?

**Comment by mosteo** [comment]
I think we can safely remove this warning for the next stable release, as it was intended for when we migrated the location of the manifest.

**Comment by yannickmoy** [comment]
Oops I missed the previous messages... thanks!
