### ISSUE TITLE
alr run shows verbose compiler output

### ISSUE THREAD

**Issue by onox** [alire-project/alire#642]
When I execute `alr run` in keystoreada* I get output like this:

```
/usr/bin/gcc -c -x ada -gnatA -g -O2 -gnat2012 -gnatafno -gnatVa -gnatwa -gnatwU -gnatec=/tmp/GNAT-TEMP-000012.TMP -gnatem=/tmp/GNAT-TEMP-000013.TMP /home/onox/test/keystoreada_1.1.0_d28d822c/src/keystore-tools.adb
```

This is quite verbose IMO. Would it be possible to change it to something like the following?

```
Building dependency utilada:
  [Ada] keystore-tools.adb
  ...
```

**Comment by mosteo** [comment]
Thanks for all the comments/submissions, Simon.

I would be in favor of this, leaving the actual output for `-v`. Cursory checking shows that we're enabling verbose output even when no `-v` flag is passed for all spawned commands, which may be just an old oversight.

@Fabien-Chouteau do you like the idea?

In general, I think we need to review what goes in verbose output as right now some messages that qualify more as debug are spilling over.

**Comment by Fabien-Chouteau** [comment]
ok for me
