### ISSUE TITLE
alr show always shows Long_Description

### ISSUE THREAD

**Issue by onox** [alire-project/alire#645]
Showing Long_Description might make it more difficult to parse the output of alr show.
Could this property be only shown in verbose output (-v)?

**Comment by Fabien-Chouteau** [comment]
Do you mean parse by a script? Because for humans the description is important.

**Comment by mosteo** [comment]
What about a `Long description: <xxxx characters omitted, use -v to show them>` in the default verbosity level?

**Comment by onox** [comment]
@Fabien-Chouteau If a crate contains a long Long_Description it might make it more difficult to quickly scan (by a human) the output and find certain info in the output, so what @mosteo suggests sounds good to me.
