### ISSUE TITLE
Should unknown enum values in the index be an error?

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#650]
For our dynamic expressions we use enums with predefined values. Finding an unknown value is currently an error that stops Alire.

As adding values can be a transparent change for current users (e.g., adding a new supported distro), we could consider silently ignoring unknown enum values, unless we are `alr publish`ing. This would allow index updates without bumping the index version.

We could also add an `alr index --check` that reported "errors" that are being ignored for this kind of backwards compatible changes. Certain debug messages could be promoted to warnings with that command.

This happened for example with this submission: https://github.com/alire-project/alire-index/pull/215

**Comment by Fabien-Chouteau** [comment]
I don't think completely silent is a good idea because one could miss a typo for instance.

**Comment by mosteo** [comment]
Yup, that's the main problem.

Having warnings would probably be too polluting, and could scare users that did nothing but update the community index. I'm not sure how to strike the precise balance.

**Comment by Fabien-Chouteau** [comment]
> could scare users that did nothing but update the community
Right...

Let's do the --check then
