### ISSUE TITLE
Alire crate for 'alr' tool?

### ISSUE THREAD

**Issue by wiremoons** [alire-project/alire#657]
Hi

Thanks for creating Alire and the `alr` CLI tool - both have been very helpful to me while I have been learning the Ada language over the past months. Not only the use of the `alr` tool, but also being able to look at the [Alire GitHub source code](https://github.com/alire-project/alire/) for inspiration and coding examples has been very useful. It is very nice to have modern examples of Ada source code available for command line tools - just for ideas and see what 'best practice' might look like for a beginner!

I was going to add an Alire badge to to my (very much beta and beginner level) GitHub Ada code projects  - just as a way to help promote awareness of Alire for Ada software. The badge example given in the Alire document is of course to link to an individuals project Alire crate - which I don't have. I was instead going to link to the `alr` crate, but there does not appear to be one?

Is this on purpose - or should the `alr` command line tool itself be added as a Alire crate too - if only for completeness and to ensure its inclusion exists?

Alternatively - is there away to add a promotional *general Alire badge* to an individuals GitHub Ada code project - perhaps for projects that can be built using `alr` - but that does not warrant its own individual crate?

Thanks for your help and the great Alire project!

Simon

**Comment by Fabien-Chouteau** [comment]
Hello @wiremoons,

Thank you for the nice feedback :)

> Is this on purpose - or should the `alr` command line tool itself be added as a Alire crate too - if only for completeness and to ensure its inclusion exists?

We may add an `alr` crate in the index at some point.

> 
> Alternatively - is there away to add a promotional _general Alire badge_ to an individuals GitHub Ada code project - perhaps for projects that can be built using `alr` - but that does not warrant its own individual crate?

I added an `Alire` badge in the website: ![](https://img.shields.io/endpoint?url=https://alire.ada.dev/badges/alire-badge.json)
Just use this line in your GitHub markdown:
`![](https://img.shields.io/endpoint?url=https://alire.ada.dev/badges/alire-badge.json)`
