### ISSUE TITLE
Integrity hash field in archive sources

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#66]

**Comment by mosteo** [comment]
@Fabien-Chouteau, just to be sure we are on the same page in regard to the features we want for the first beta, and in the context of the above discussion. My current understanding is that:

- We want the whitelist for places that provide indexes (hence we trust their operators -- basically github at this point). This ensures index integrity.
  - In our discussion we talked about the whitelist for sources of crates, but see next point.
- If the index source is trusted, the hashes it provides are trusted. Thus:
  - Integrity hashes work for source archives (the `archive-hash` field).
  - Commits work for git/hg/svn, since these check integrity during retrieval (the `origin` field).

The thing is, and sorry for re-raising the issue -- it seemed clear at the time but not anymore --, I'm not sure why we wanted to hash directory contents, when the VCS is going to check it for us. If someone is messing with the network to try a MITM, as long as the index comes from a trusted site, we would detect the corruption on retrieval.

Also, have you some reference on hand for what you told me about Arduino? I'm going in circles with high-level trusted partners which I don't think is what you alluded to.

**Comment by Fabien-Chouteau** [comment]
>     * We want the whitelist for places that provide indexes (hence we trust their operators -- basically github at this point). 

If we do a hash of the repo content (`git archive | sha512sum`) I am not sure that we need the whitelist.

> This ensures index integrity.

This was more for crates integrity than the integrity of the index itself.
 
> The thing is, and sorry for re-raising the issue -- it seemed clear at the time but not anymore --, I'm not sure why we wanted to hash directory contents, when the VCS is going to check it for us. If someone is messing with the network to try a MITM, as long as the index comes from a trusted site, we would detect the corruption on retrieval.

I guess it is one or the other, whitelist or content hash.

> Also, have you some reference on hand for what you told me about Arduino? I'm going in circles with high-level trusted partners which I don't think is what you alluded to.

Have a look here: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

They accept GitHub, BitBucket or GitLab.

**Comment by mosteo** [comment]
> I guess it is one or the other, whitelist or content hash.

In that case I'd go for the content hash, which I see as more general.

**Comment by Fabien-Chouteau** [comment]
Me too
