### ISSUE TITLE
"cannot relocate deeper than object directory" on locally pinned deps

### ISSUE THREAD

**Issue by Heziode** [alire-project/alire#660]
Hi,

I get this error when try to `alr build` a project that depends on a local deps: `cannot relocate deeper than object directory`

The error came from a dependence that I added like this: `alr pin|with mylib --use /path/to/my-lib`

**Alr version**: 0.7.1

**Comment by Fabien-Chouteau** [comment]
I have seen the same problem but thought it was an issue on my side.

**Comment by mosteo** [comment]
I also saw this at some point but I thought it was solved. Oh well...

**Comment by Fabien-Chouteau** [comment]
@mosteo do we __have__ to set a `--relocate-build-tree=alire/build`?
One solution for multiple problems we see come from this relocation I think.

**Comment by mosteo** [comment]
Is there another way of making an out-of-tree build? It was my first time fighting with these gprbuild switches. That was my objective here.

Of course we could dispense with that, and build in-tree. Although I like the cleanliness of knowing we aren't touching anything, for example in pinned folders. This may be less of a concern for GNAT users, as gpr files allow to define where the build has to take place. Perhaps I'm seeing this more with a C++ mentality.

**Comment by mosteo** [comment]
I've been trying to wrap my head around how these two grpbuild options work and I don't think that this can generally work with e.g. Windows multiple drive names, as there cannot be a root dir that is above all sources if these are split on diferent drives.

So I'd say to remove this relocation, with the understanding that pinned directories will be built in place, with whatever consequences that has. For regular dependencies this is a non-issue as they are not intended for user editing.
