### ISSUE TITLE
`alr with` stores value of --use as absolute path in alire.lock

### ISSUE THREAD

**Issue by onox** [alire-project/alire#662]
I have a monorepo with a number of crates, including wayland_ada_scanner (a tool) and wayland_client_ada (a library).

During development or CI I would like to use the local wayland_ada_scanner crate in wayland_client_ada. I added the scanner as a dependency to wayland_client_ada as follows:

```
alr with wayland_ada_scanner^0.1.0 --use=../wayland_ada_scanner
```

This results in the following alire.lock file:

```
[solution]
[solution.context]
solved = true
[[solution.state]]
crate = "wayland_ada_scanner"
fulfilment = "linked"
pinned = false
transitivity = "direct"
versions = "^0.1.0"
[solution.state.link]
kind = "softlink"
path = "file:/absolute/path/to/wayland-ada/wayland_ada_scanner"
```

This obviously won't work for other users who clone the git repo. If the `--use` option is given a relative path, can this relative path be stored in the lock file as well? Perhaps the path can first be made absolute and then transformed to relative again to deal with symlinks and ../ folders.

**Comment by mosteo** [comment]
As you describe it, it makes sense. I had always assumed that one would not want to publish local paths, but I see your point. Thanks for the report.

This is thematically related to #508.

**Comment by onox** [comment]
I think the problem here is that `alr` doesn't really support monorepos. I've been playing with Yarn 2's [workspaces](https://yarnpkg.com/features/workspaces/) feature a bit, and it seems how it should work is that each folder (local crate) has an alire.toml file, but there's only 1 alire.lock file (in the root folder of the repo). The root folder also has an `alire.toml` file with an array of glob patterns that indicate which folders are local crates. During the publishing process, these alire.toml should be slightly modified (the `workspace:*` version get replaced with the actual version) and (I guess) the .tgz files should each get a specially crafted `alire.lock` file instead of the one from the root folder.

This way, during development, these local crates can be used together (they link to each other because of the special version number mentioned above), and the artifacts created during publishing (which will end up in alire-index) will point to the remote registry (alire-index (and github?)).

**Comment by mosteo** [comment]
Hi @onox, I just saw your messages in gitter. Indeed, each toml has to have a companion lock. A lock is at present a cached solution for the dependencies in the toml, with optional overrides. But also I think you've stumbled into something we did not yet explore, which is nested pins. 

From my reading of the Yarn 2 workspace feature that you provided, local pins should indeed cover your development use case, and as they seem to be falling short, I'll see to improve the feature. A different matter is how that affects the publishing of these interrelated crates. I need to give some thought to that.

**Comment by onox** [comment]
I have 2 monorepos: https://github.com/onox/wayland-ada and https://github.com/onox/orka.

I have put a small Yarn 2 monorepo on GitHub at https://github.com/onox/yarn-monorepo to show how things could work. Crate `bar` has a dependency on `foo` (both `bar` and `foo` are local folders) and `foo` has a dependency on `react` which is in the a remote registry (npm). Both local crates have a special `version` and no checksum.

If I were to publish these 2 crates, their `package.json` file would be automatically rewritten so that their dependencies would only point at versions in the remote registry. If I read the documentation correctly the files in the git repo remain untouched so developers can continue to use the local crates.

**Comment by mosteo** [comment]
Hi again, @onox. I think I have a good understanding of yarn monorepos now. Thanks a lot for the simple example! At this time I would like to avoid introducing some special monorepo manifests, if we don't really need them. Correct me if I'm wrong, in regard to possible Alire changes:

1. Making pins relative would fix the first issue of people being able to clone the monorepo and using it as is (once transitive pins work).
1. Pins have to work transitively to minimize user intervention.
1. We could provide some help at publish time to simultaneously generate the manifests of all crates in the monorepo, that would be in all respects just regular manifests.
