### ISSUE TITLE
Incomplete solution message not very clear to me

### ISSUE THREAD

**Issue by Fabien-Chouteau** [alire-project/alire#685]
I was testing `1.0-rc1` on Windows and I got the incomplete solution message:
```
Warning:
Warning:    New solution is incomplete.
Warning:    +~ gnat          /=2020 (new,external,indirect)
Warning:    +  libsdl2       2.0.12 (new,indirect)
Warning:    +  libsdl2_image 2.0.5  (new,indirect)
Warning:    +  libsdl2_ttf   2.0.15 (new,indirect)
Warning:    +  sdlada        2.3.1  (new)
Warning:
Warning: Could not find a complete solution for ada_voxel_space_demo=1.0.1
Build will fail unless externals are made available, do you want to continue?
[Y] Yes  [N] No  (default is No)
```
To me it is really not clear what dependency is missing. I know it is gnat from context, but the message could be a lot more explicit.

**Comment by mosteo** [comment]
There was some discussion about this in #646. We could abandon all "missing/external" distinctions (wrt the users) and simply use "missing" instead.

No matter how we word or segregate it, the telltale is that when the crate is accompanied by a subset dependency instead of a precise version, it's not solved. But of course the first time it may not be evident.

**Comment by Fabien-Chouteau** [comment]
For me it should be either something like:
```
Warning:    New solution is incomplete.
Warning:    +~ gnat          /=2020 (new,external,indirect) missing
Warning:    +  libsdl2       2.0.12 (new,indirect)
Warning:    +  libsdl2_image 2.0.5  (new,indirect)
Warning:    +  libsdl2_ttf   2.0.15 (new,indirect)
Warning:    +  sdlada        2.3.1  (new)
```
or
```
Warning:    New solution is incomplete.
Warning:    +  libsdl2       2.0.12 (new,indirect)
Warning:    +  libsdl2_image 2.0.5  (new,indirect)
Warning:    +  libsdl2_ttf   2.0.15 (new,indirect)
Warning:    +  sdlada        2.3.1  (new)
Warning:   Missing:
Warning:    +~ gnat          /=2020 (new,external,indirect)
```

**Comment by mosteo** [comment]
Not sure how well this mixes with the "missing" flag we already have for truly unknown/unavailable deps. Try for example `alr with hello=5`, and you'll get:
```
   New solution is incomplete.
   +⚠ hello =5 (new,missing)
``` 
We currently have these change flags:
- `external` when the dependency is unavailable but external definitions exist.
- `missing` when the crate is unknown (there's an extra warning) or there are no compatible versions.

**Comment by rogermc2** [comment]
Still a problem!  Very disappointing.
I tried `alr get libadalang` and ended up without any indication of just what "externals"  are missing:
~~~ 
warn:    New solution is incomplete.
warn:    +♼ gnat            12.2.1 (new,installed,gnat_native,indirect)
warn:    +  gnatcoll        23.0.0 (new)                               
warn:    +  gnatcoll_gmp    23.0.0 (new)                               
warn:    +  gnatcoll_iconv  23.0.0 (new)                               
warn:    +  langkit_support 23.0.0 (new)                               
warn:    +↪ libgmp          *      (new,external,indirect)             
warn:    +  libgpr          23.0.0 (new,indirect)                      
warn:    +  xmlada          23.0.0 (new,indirect)                      
warn: 
warn: Could not find a complete solution for libadalang=23.0.0
Build will fail unless externals are made available, do you want to continue?
[Y] Yes  [N] No  (default is No) Could not find a complete solution 
~~~
The statement `Build will fail unless externals are made available` is  useless unless the missing external are identified.

**Comment by mosteo** [comment]
The external is identified with "external":

> warn:    +↪ libgmp          *      (new,external,indirect) 

Since you're on Windows you're not getting colorized output, which may make it less conspicuous.

**Comment by rogermc2** [comment]
Thanks. Makes more sense with your explanation.
However, I'm using Mac Ventura which provides no colorized output.
The message ` libgmp * (new,external,indirect)` indicates to me that `libgmp` has been identified as external and is available indirectly.
If this is not the case, I would expect something like ` libgmp * (new,external,unavailable)` or, perhaps, ` libgmp * (new,external,indirect,unavailable)` 
As everything is labelled `warn:` perhaps the label on `libgmp` should be more indicative of a problem.
I don't really understand why everything is labelled `warn:` even including a blank line.
I would expect `warn:` on only `New solution is incomplete.`, `libgmp          *      (new,external,indirect)` and `Could not find a complete solution for libadalang=23.0.0`

**Comment by mosteo** [comment]
The "warn:" refers to the level of output that's being used. So even if you silenced regular messages, you'd see the ones labeled as warn.

"external" in this context means that Alire won't be supplying that dependency, so in practice it's equivalent to unavailable. There have been changes already to clarify this output, but they're still in the master branch: #1127

**Comment by kevlar700** [comment]
As a side note. I believe an externally installed libgmp was not found on Gentoo.

Assuming this is the right one?

https://packages.gentoo.org/packages/dev-libs/gmp

**Comment by mosteo** [comment]
Gentoo isn't yet supported, so any system libraries known to Alire via externals for other platforms won't be detected.

**Comment by rogermc2** [comment]
Thanks for your further clarification.
Correction to my earlier comment referring to colourization:
Mac Ventura does provide colour for `alr get`.
Unfortunately, I missed the clues provided by the colours but now see the relevance.

**Comment by Fabien-Chouteau** [comment]
I agree that incomplete solution message could be improved. A recap of what is missing in a separate section for instance.

**Comment by mosteo** [comment]
> I agree that incomplete solution message could be improved. A recap of what is missing in a separate section for instance.

Then let's reopen with that goal in mind.

**Comment by mosteo** [comment]
Then let's reopen with that goal in mind.

**Comment by rogermc2** [comment]
Having clarified that, I now need to know how to make `libgmp` "available".
`libgmp.a` and `libgmp.dylib` are in my `/usr/local/lib`.

**Comment by peihunglin** [comment]
Running into the same issue with libgmp.  Is there anyway that Alire can recognize the libgmp from the system?

**Comment by mosteo** [comment]
> Running into the same issue with libgmp. Is there anyway that Alire can recognize the libgmp from the system?

What's the OS/distro?

**Comment by peihunglin** [comment]
> > Running into the same issue with libgmp. Is there anyway that Alire can recognize the libgmp from the system?
> 
> What's the OS/distro?

RHEL8

**Comment by mosteo** [comment]
> > > Running into the same issue with libgmp. Is there anyway that Alire can recognize the libgmp from the system?
> > 
> > 
> > What's the OS/distro?
> 
> RHEL8

Alright. Then, according to this output:
```
$ alr show libgmp --external
Kind           Description                 Details                     Available
System package 4 candidate system packages Debian: libgmp-dev          True
                                           Ubuntu: libgmp-dev
                                           Msys2: mingw-w64-x86_64-gmp
                                           Arch: gmp
                                           others: unavailable
```
we don't have definitions for REHL, and that's why it isn't detected.

You can try locally to add the necessary definition to the index in the `index/li/libgmp/libgmp-external.toml` file. The index location will be output by `alr index`.

Feel free to submit a PR to the index with this addition.
