### ISSUE TITLE
zlib_ada deployment error

### ISSUE THREAD

**Issue by Patschkowski** [alire-project/alire#691]
Hi,

I have added a dependency to my toml on zlib_ada like this

[[depends-on]]
make = "*"
win32ada = ">=21.0"
zlib_ada = ">=1.3"

but then I get a deployment error for this crate. Here is sample debug output. I think the problem is that in the downloaded archive there is no single folder but multiple files.

alr printenv output

-> Config file is not readable or doesn't exist: 'C:\build\alire\alire\config.toml'
-> Using default value for configuration 'distribution.disable_detection': 'FALSE'
-> Spawning: ["pacman", "-V"] > GNAT-TEMP-000001.TMP
Warning: Deprecated license indentifier 'Custom'. Please replace with an SPDX expression (https://spdx.org/licenses/)
-> alr build is (valid) (0 releases indexed) (loaded in 5.922s)
-> Using candidate alire root: C:\build\alire
-> printenv:
-> Found 1 indexes
-> Found 1 indexes
-> Loading index found at C:\Users\nxp87720\.config\alire\indexes\community\repo\index
-> Loading full catalog from C:\Users\nxp87720\.config\alire\indexes\community\repo\index
-> Spawning: ["git", "branch"] > GNAT-TEMP-000002.TMP
Warning: Deprecated license indentifier 'Custom'. Please replace with an SPDX expression (https://spdx.org/licenses/)
-> Using default value for configuration 'update-manually-only': 'FALSE'
Warning: Deprecated license indentifier 'Custom'. Please replace with an SPDX expression (https://spdx.org/licenses/)
-> Index already loaded, loading skipped
Detected missing dependencies, updating workspace...
-> Env: win32ada (gpr ext) sets 'Release' to 'PRJ_BUILD'
-> Env: msys2 appends 'C:\Users\nxp87720\.cache\alire\msys64\mingw64\lib' to 'LIBRARY_PATH'
-> Env: win32ada (gpr ext) sets 'Win64' to 'PRJ_TARGET'
-> Env: msys2 appends 'C:\Users\nxp87720\.cache\alire\msys64\mingw64\bin' to 'PATH'
-> Env: msys2 appends 'C:\Users\nxp87720\.cache\alire\msys64\usr\bin' to 'PATH'
-> Env: msys2 appends 'C:\Users\nxp87720\.cache\alire\msys64\usr\local\bin' to 'PATH'
-> Env: itec (env) prepends 'C:\build\alire/alire/build/:C:\build\alire/Data/General/image/:C:\build\alire/Data/General/image/win64/:C:\build\alire/Data/General/image/win64/pylon:C:\build\alire/Data/General/image/win64/spinnaker:C:\build\alire/Data/Applic/Phicom:C:\build\alire/out/bin' to 'PATH'
-> Env: crates appends 'C:\build\alire\Source' to 'GPR_PROJECT_PATH'
-> Env: crates appends 'C:\build\alire\alire\cache\dependencies\win32ada_21.0.0_67cd45b8' to 'GPR_PROJECT_PATH'
-> Env: crates appends 'C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c' to 'GPR_PROJECT_PATH'
-> Env: win32ada (gpr ext) sets 'Win64' to 'TARGET'
-> Env: Alire sets 'True' to 'ALIRE'
-> Env: msys2 appends 'C:\Users\nxp87720\.cache\alire\msys64\mingw64\include' to 'C_INCLUDE_PATH'
-> Skipping checkout of already available make=4.3.0
-> Skipping checkout of already available win32ada=21.0.0
-> Skipping checkout of already available zlib=1.2.11
-> About to deploy zlib_ada=1.3.0
-> Downloading file: https://sourceforge.net/projects/zlib-ada/files/zlib-ada/1.3/zlib-ada-1.3.tar.gz
-> Spawning: ["curl", "https://sourceforge.net/projects/zlib-ada/files/zlib-ada/1.3/zlib-ada-1.3.tar.gz", "--location", "--progress-bar", "--output", "C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c\zlib-ada-1.3.tar.gz"]
################################################################################################################# 100.0%################################################################################################################# 100.0%################################################################################################################# 100.0%
-> Verifying integrity...
-> Deploying source archive zlib-ada-1.3.tar.gz into C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c...
-> Spawning: ["tar", "--force-local", "-x", "-f", "C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c\zlib-ada-1.3.tar.gz"] > GNAT-TEMP-000003.TMP
stderr: Command ["tar", "--force-local", "-x", "-f", "C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c\zlib-ada-1.3.tar.gz"] exited with code 1 and output: tar.exe: Option --force-local is not supported\nUsage:\n  List:    tar.exe -tf <archive-filename>\n  Extract: tar.exe -xf <archive-filename>\n  Create:  tar.exe -cf <archive-filename> [filenames...]\n  Help:    tar.exe --help
-> Spawning: ["tar", "-x", "-f", "C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c\zlib-ada-1.3.tar.gz"] > GNAT-TEMP-000004.TMP
stderr: ALIRE.CHECKED_ERROR
**stderr: Unexpected contents where a single directory was expected:** C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c
stderr: raised ALIRE.CHECKED_ERROR : alire-stored-error:2
[C:\Program Files\Alire\bin\alr.exe]
Semantic_Versioning.Basic.At_Least at alire-origins-deployers-source_archive.adb:184
Semantic_Versioning.Basic.At_Least at alire-origins-deployers-source_archive.adb:280
Semantic_Versioning.Basic.At_Least at alire-origins-deployers-source_archive.adb:104
Semantic_Versioning.Basic.At_Least at alire-origins-deployers.adb:77
Semantic_Versioning.Basic.At_Least at alire-origins-deployers.adb:96
Semantic_Versioning.Basic.At_Least at alire-workspace.adb:162
Semantic_Versioning.Basic.At_Least at alire-workspace.adb:96
Semantic_Versioning.Basic.At_Least at alire-roots.adb:329
Semantic_Versioning.Basic.At_Least at alr-commands.adb:476
Semantic_Versioning.Basic.At_Least at alr-commands-printenv.adb:27
Semantic_Versioning.Basic.At_Least at alr-commands.adb:795
Semantic_Versioning.Basic.At_Least at alr-commands.adb:765
Alr.Main at alr-main.adb:28
Main at b__alr-main.adb:1880
__tmainCRTStartup at crtexe.c:339
mainCRTStartup at crtexe.c:223
[C:\WINDOWS\System32\KERNEL32.DLL]
0x7ffb87547032
[C:\WINDOWS\SYSTEM32\ntdll.dll]
0x7ffb88cbd23f

stderr: Generating Outcome_Failure with message: Deployment of source archive zlib-ada-1.3.tar.gz at https://sourceforge.net/projects/zlib-ada/files/zlib-ada/1.3/zlib-ada-1.3.tar.gz with hash sha512:e1677e3caa1fa963073b11bfba28f90e4ecd3032c1615792ad61a9860b25c73f5ef8ad062277ce29bc2ce7af08f45995161760baf4e60b79d194986fa2839977 to C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c failed
stderr: Generating Outcome_Failure with call stack:
stderr: raised AAA.DEBUG.STACK_TRACE.DEBUG_EXCEPTION : aaa-debug.adb:12
[C:\Program Files\Alire\bin\alr.exe]
Semantic_Versioning.Basic.At_Least at aaa-debug.adb:12
Semantic_Versioning.Basic.At_Least at alire.adb:155
Semantic_Versioning.Basic.At_Least at alire-origins-deployers.adb:84
Semantic_Versioning.Basic.At_Least at alire-origins-deployers.adb:96
Semantic_Versioning.Basic.At_Least at alire-workspace.adb:162
Semantic_Versioning.Basic.At_Least at alire-workspace.adb:96
Semantic_Versioning.Basic.At_Least at alire-roots.adb:329
Semantic_Versioning.Basic.At_Least at alr-commands.adb:476
Semantic_Versioning.Basic.At_Least at alr-commands-printenv.adb:27
Semantic_Versioning.Basic.At_Least at alr-commands.adb:795
Semantic_Versioning.Basic.At_Least at alr-commands.adb:765
Alr.Main at alr-main.adb:28
Main at b__alr-main.adb:1880
__tmainCRTStartup at crtexe.c:339
mainCRTStartup at crtexe.c:223
[C:\WINDOWS\System32\KERNEL32.DLL]
0x7ffb87547032
[C:\WINDOWS\SYSTEM32\ntdll.dll]
0x7ffb88cbd23f

stderr: Deployment of source archive zlib-ada-1.3.tar.gz at https://sourceforge.net/projects/zlib-ada/files/zlib-ada/1.3/zlib-ada-1.3.tar.gz with hash sha512:e1677e3caa1fa963073b11bfba28f90e4ecd3032c1615792ad61a9860b25c73f5ef8ad062277ce29bc2ce7af08f45995161760baf4e60b79d194986fa2839977 to C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c failed
ERROR: Deployment of source archive zlib-ada-1.3.tar.gz at https://sourceforge.net/projects/zlib-ada/files/zlib-ada/1.3/zlib-ada-1.3.tar.gz with hash sha512:e1677e3caa1fa963073b11bfba28f90e4ecd3032c1615792ad61a9860b25c73f5ef8ad062277ce29bc2ce7af08f45995161760baf4e60b79d194986fa2839977 to C:\build\alire\alire\cache\dependencies\zlib_ada_1.3.0_e1677e3c failed

**Comment by mosteo** [comment]
Indeed, your diagnosis is correct. Thanks for raising the issue.
