### ISSUE TITLE
Win32Ada crate: preprocessor required

### ISSUE THREAD

**Issue by Patschkowski** [alire-project/alire#695]
Hi

I have a very simple project trying to use the win32ada crate and I can not build it because the win32ada uses preprocessor stuff. Is this a problem of the crate or do one need to turn on specific options somewhere to compile projects depending on this crate? And if so, how do I do it?

[test_me.zip](https://github.com/alire-project/alire/files/6035710/test_me.zip)

Kind regards,
felix

**Comment by Fabien-Chouteau** [comment]
Hello @Patschkowski,

It could be that we need a `post-fetch` action to build and install the lib.
For the moment as a workaround it seems like you can add `-gnateDTARGET=Win64` in you Ada compiler switches.

Regards,
