### ISSUE TITLE
Build modes

### ISSUE THREAD

**Issue by onox** [alire-project/alire#707]
Would it be possible to build a whole tree of crates with a certain mode? Like `alr build --release` or `alr build --debug`?

Perhaps `alr build` could support a few modes, like release, develop, debug, coverage, profiling?

Some of the modes could enable/disable style checks and/or contract checks.

**Comment by Fabien-Chouteau** [comment]
Hello @onox,

Right now the question of build mode is highly project specific, there is no standard way to specify that.
