### ISSUE TITLE
Alire crashes if called outside of home(sub)directory

### ISSUE THREAD

**Issue by MarcusE1W** [alire-project/alire#708]
Hi.

If I call alire `alr` anywhere outside of my home folders it just crashes. So it works in normal use, but e.g.
```
cd /
alr -d
```
crashes with
```
✘  ~  cd /
 /  alr
ERROR: alire-os_lib-subprocess.adb:280 access check failed
ERROR: alr encountered an unexpected error, re-run with -d for details.
 ✘  /  alr -d
stderr: CONSTRAINT_ERROR
stderr: alire-os_lib-subprocess.adb:280 access check failed
stderr: raised CONSTRAINT_ERROR : alire-os_lib-subprocess.adb:280 access check failed
Call stack traceback locations:
0xaaaae605bd98 0xaaaae605a2e8 0xaaaae619f8d0 0xaaaae619f430 0xaaaae6352e9c 0xaaaae605dc6c 0xaaaae605e368 0xaaaae5e1f378 0xaaaae5e23484 0xffffaab4f08c 0xaaaae5e1f1e4

ERROR: alire-os_lib-subprocess.adb:280 access check failed
ERROR: alr encountered an unexpected error, re-run with -d for details.
```

I appreciate that it is not very useful to do this in first place, but alire should probably still not just crash ?

OS: Armbian (Ubuntu ARM) bullseye

**Comment by Fabien-Chouteau** [comment]
Hello @MarcusE1W 

Alire should definitely not crash. Can you tell use which version are you using?

**Comment by MarcusE1W** [comment]
I knew there was something I wanted to add:
```
✘  ~  alr version
Alr version: 1.1.0-dev
Alire Library version: 1.1.0-dev
alr status is (outside) (0 releases indexed) (loaded in 0.011s)
config folder is /home/mmw/.config
source folder is /home/mmw/.config/alire
interaction flags are: force:FALSE not-interactive:FALSE
alr root is empty
alr root detection has settled on path: /home/mmw
alr is finding 0 GPR project files
alr session state is [OUTSIDE]
alr compiled on [2021-03-03 15:17:11] with GNAT version [9.3.0]
platform fingerprint: Linux Bits_64 Ubuntu
platform properties: UBUNTU LINUX NATIVE SYSTEM BITS_64
community index required branch: stable-1.0
```

**Comment by mosteo** [comment]
#703 should have fixed precisely this case. @MarcusE1W, are you using the latest master code?

**Comment by MarcusE1W** [comment]
I think I compiled about a week ago.
Let me creat a new alire from today’s code and we see

Edit: actually it says in the version info. Master code from 3rd March

**Comment by MarcusE1W** [comment]
Ok, I have rebuild alire from today’s master and this error is fixed.
Sorry for the confusion, I was not expecting this to be fixed exactly in the last few days.

**Comment by mosteo** [comment]
No problem, just coincidence that I hit the same bug at the same time. Thanks for taking the time to report!
