### ISSUE TITLE
Download dependencies with alr install

### ISSUE THREAD

**Issue by onox** [alire-project/alire#725]
A command like `install` could download dependencies.

Optional:
It would be even better to store everything as 1 archive file (zip, tgz, etc.) per dependency (instead of having tens/hundreds of files per dependency). This would give benefits like:

- Less disk space for large projects with many dependencies
- You can commit the dependencies (the archives) to version control so you don't need an internet connection when switching branches with different (versions of) dependencies or when building your project (think of having an Alire project on a LAN) and you can still build your project 5 years from now when a developer of a dependency of one of your dependencies decided to remove/unpublish it (google "left-pad" :smile:).

(It's basically Yarn 2's [Plug'n'Play](https://yarnpkg.com/features/pnp/) feature)

**Comment by mosteo** [comment]
Could this be an option to `get`? `alr get --dependencies`. Just as now `alr get --only` does the complementary.

I'm not sure I fully grasp the other points. Reading the Yarn 2 PnP, it seems more integrated in the sense that: would these archives be automatically used in place of remote dependencies?

We have some plans for a possible `alr install` (#482, #625) that might do some of these things. I guess I need a more explicit use case: is it getting the dependencies for archival purposes? Is it a way to reuse them across local crates?

**Comment by onox** [comment]
> Could this be an option to get? alr get --dependencies.

I think it could be an option to `get`. Most package managers have a separate command for this though. Poetry and Yarn/NPM uses `install`. Cargo uses `fetch` (it also automatically fetches dependencies during `build` of course).

> would these archives be automatically used in place of remote dependencies?

Do you mean things like this?

```toml
[origin]
url = "git+https://github.com/example-user/example-project"
commit = "ec8b267bb8b777c6887059059924d823e9443439"
```

I guess it would download a .zip of the specified commit. The user then `git add` it so that it will always be available to anyone who does a checkout of the current branch in the project's git repo. Usually the dependency would be downloaded when the user runs `alr with` and removed when the user runs `alr with --del`. If the user runs `alr build` or some other command and Alire notices that the dependency doesn't exist, it would need to download it (current behavior).

> We have some plans for a possible `alr install`

Cargo uses the `install` command to download, build, and install binaries and examples to some folder, based on some environment variable, config value, or pre-defined folder like `$HOME/.cargo`, so that they become globally accesible to the system. I don't know what Yarn does, but NPM had a `--global` option to add a package to a global workspace (which I think is very ugly). I think separating the tasks of installing binaries and fetching dependencies is cleaner.

**Comment by mosteo** [comment]
I find using "install" to download something that's in essence a tarball of sources to be used manually counterintuitive. 

So `cargo fetch` only makes sense in the context of a crate. `alr get` is the opposite, and that's not what you are requesting anyway as I see from your last description. I guess we could settle for fetch too, but I'd prefer something that conveys the idea of dependencies. I'm not inspired right now.

I don't think we want ever to touch anything global with alr. At most, what cargo does is what I had in mind, per config, and the user can add the $config/bin folder to its path if wanted. A separate issue is the reuse of large dependencies across crates. This could be perhaps done with `alr with --shared` instead of install, but anyway these are still ideas for discussion.

**Comment by onox** [comment]
> I find using "install" to download something that's in essence a tarball of sources to be used manually counterintuitive.

I agree.

> and the user can add the $config/bin folder to its path if wanted

So that is some folder that could be in `$PATH` if I understand you correctly? What if the user wants to install some game? Do you intend for alr to support a usecase like `alr install eagle_lander`? (instead of requiring the user to do `alr get -b` + `cd` + `alr run`) or would alr require the project to bundle it with AppImage/Flatpak/snap/deb/rpm? That would be a bit cumbersome for small projects.

**Comment by mosteo** [comment]
I see `alr get` staying as a way to retrieve a crate in its own sandbox, to experiment with it or to build its executables. `alr install` would essentially be the equivalent of `cargo install`, in which you want to deploy something in a known shared location (but still not in the path by default).
