### ISSUE TITLE
zipada build failures

### ISSUE THREAD

**Issue by RajaSrinivasan** [alire-project/alire#745]
This may not be the right forum to report issues with crates in alire. But I have an issue with zipada. Is there an easy way to go from alire to the website related to the crate - zipada in this case:

gprbuild -d -PC:\Users\RajaS\Projects\zipada_56.0.1_bec2ed6c\zipada.gpr -p
Setup
   [mkdir]        object directory for project ZipAda
Compile
   [Ada]          zipada.adb
   [Ada]          unzipada.adb
   [Ada]          comp_zip.adb
   [Ada]          find_zip.adb
   [Ada]          rezip.adb
   [Ada]          zip_dir_list.adb
   [Ada]          demo_csv_into_zip.adb
   [Ada]          demo_zip.adb
   [Ada]          demo_unzip.adb
   [Ada]          bunzip.adb
   [Ada]          lzhuf.adb
unzipada.adb:243:27: warning: condition is always True
   [Ada]          lzma_dec.adb
   [Ada]          lzma_enc.adb
   [Ada]          bwt_demo.adb
bzip2-decoding.ads:60:18: not subtype conformant with declaration at bunzip.adb:22
bzip2-decoding.ads:60:18: formal subprograms are not subtype conformant (RM 6.3.1 (17/3))
bzip2-decoding.ads:62:18: not subtype conformant with declaration at bunzip.adb:39
bzip2-decoding.ads:62:18: formal subprograms are not subtype conformant (RM 6.3.1 (17/3))
lzh.ads:40:18: not subtype conformant with declaration at lzhuf.adb:52
lzh.ads:40:18: formal subprograms are not subtype conformant (RM 6.3.1 (17/3))
lzma-decoding.ads:39:17: not subtype conformant with declaration at lzma_dec.adb:20
lzma-decoding.ads:39:17: formal subprograms are not subtype conformant (RM 6.3.1 (17/3))
lzma-decoding.ads:41:18: not subtype conformant with declaration at lzma_dec.adb:27
lzma-decoding.ads:41:18: formal subprograms are not subtype conformant (RM 6.3.1 (17/3))

   compilation of bunzip.adb failed
   compilation of lzhuf.adb failed
   compilation of lzma_dec.adb failed

gprbuild: *** compilation phase failed

**Comment by mosteo** [comment]
Hello @RajaSrinivasan, 

Yes, this is the proper place to report an issue with a crate. As for the website, you can see all information about a crate with `alr show`. I see in this case there's no information about it.

I think this is the one though: https://github.com/zertovitch/zip-ada

As for the errors themselves, which compiler version are you using?

**Comment by RajaSrinivasan** [comment]
GNAT Studio Community 2020 (20200427) hosted on x86_64-pc-mingw32
GNAT Community 2020 (20200429-93) targetting x86_64-pc-mingw32
SPARK Community 2020 (20200429)

**Comment by RajaSrinivasan** [comment]
When I clone https://github.com/zertovitch/zip-ada

The builds are successful

**Comment by mosteo** [comment]
> The builds are successful

My guess then is that the version in alire is older and lacking the fixes in the repo. I'll check and make a new release.

**Comment by mosteo** [comment]
Should be fixed after https://github.com/alire-project/alire-index/pull/285
