### ISSUE TITLE
Cross build fails, bad parameter to ar command

### ISSUE THREAD

**Issue by pmunts** [alire-project/alire#770]
I routinely do cross-builds with `gprbuild` by simply copying an appropriate `.cgpr` file for the cross-toolchain to the project directory.  When I tried this with `alr build`, the compilations succeed but gprlib fails, apparently passing an invalid parameter to the cross-toolchain `ar` command.

[build.log](https://github.com/alire-project/alire/files/6765445/build.log)

The build process fails at line 5186 in build.log.

**Comment by mosteo** [comment]
Hello, @pmunts. Unfortunately I have no experience about your issue. Maybe @Fabien-Chouteau is able to help.

FYI, in the near future we expect to offer compilers (both native and cross-target) through Alire.

**Comment by Fabien-Chouteau** [comment]
@pmunts you are not supposed to copy the .cgpr files around. The only thing you should have to do is change the `for Target use "";` attribute in the `.gpr` file.

**Comment by pmunts** [comment]
The reason I have to copy .cgpr files around is because in the cross-toolchain world, gprbuild is often unable to determine which toolchain to use otherwise.  For example, cross-toolchains for the BeagleBone and Raspberry Pi 2 boards both have the same ARMv7 compiler triplet designator: "arm-linux-gnueabihf".  Their instruction set architectures are very similar but not identical, so I have to maintain two separate cross-toolchains, each customized for the particular processor core (cortex-a8 and neon-vfpv3 for the BeagleBone and cortex-a7 and neon-vfpv4 for the Raspberry Pi 2).

Furthermore, with custom toolchains, gprbuild can't find the cross-toolchain .cgpr files anyway, unless you hack stuff into /usr/lib or pass a lot of extraneous flags to gprbuild.  It is far simpler to just copy the proper cross-toolchain .cgpr file to default.gpr in the project directory.  Without default.cgpr present, I get a native build.  With default.cgpr, I get a cross-build.  It just works!  (Using gprbuild from the command line.  With gprbuild run by alr build, it **doesn't** work...)

**Comment by mosteo** [comment]
@Fabien-Chouteau , in regard to the new bundled compilers, and in view of what @pmunts says in his previous post: I am using a crate per target, which right now means we have `gnat_riscv` and `gnat_arm`. But maybe we will need more granularity? Or are these compilers able to emit for various targets depending on the project file in use?

**Comment by Fabien-Chouteau** [comment]
> so I have to maintain two separate cross-toolchains, each customized for the particular processor core (cortex-a8 and neon-vfpv3 for the BeagleBone and cortex-a7 and neon-vfpv4 for the Raspberry Pi 2).

In that case I recommend installing both compiler in separate directories and using the PATH env variable to control which one yo use.

> Furthermore, with custom toolchains, gprbuild can't find the cross-toolchain .cgpr files anyway, unless you hack stuff into /usr/lib or pass a lot of extraneous flags to gprbuild. It is far simpler to just copy the proper cross-toolchain .cgpr file to default.gpr in the project directory.

Where do you get your gprbuild and toolchains from?

> Without default.cgpr present, I get a native build. 

Are you using the `for Target use "X";` attribute in your project file?

**Comment by pmunts** [comment]
I am using the Debian Buster native `gprbuild`.

For embedded ARM Linux targets, I use cross-toolchains I built myself, either using Crosstool-NC, or Linaro `abe`.  Neither of these include `gprbuild`.

You can examine one of my typical project directories at: [https://github.com/pmunts/libsimpleio/tree/master/ada/programs](https://github.com/pmunts/libsimpleio/tree/master/ada/programs).

I don't include `for Target use` in the project file `default.gpr` because these programs can be build for any arbitrary Linux system.

To build `test_dac` as a native program, I just do `gprbuild -p test_dac`.

To build `test_dac ` for the Raspberry Pi 1, I copy `/usr/local/gcc-arm-linux-gnueabihf-muntsos-RaspberryPi1-crosstool/share/gpr/arm-linux-gnueabihf.cgpr` to `./default.cgpr` and just do `gprbuild -p test_dac`.  It just works!

The whole purpose of a `.cgpr` file is to tell `gprbuild` where to find the pieces of the toolchain and how to use them.  It seems redundant to me to try to bandaid the build procedure by stuffing target specific things into `PATH` or the project file when `gprbuild` is perfectly happy to learn everything it needs from `default.gpr` and `default.cgpr`.

**Comment by pmunts** [comment]
Never mind.  I fixed my problem by regenerating all of my `.cgpr` files using `gprconfig` from GNAT Community 2021.  Copying one of my custom cross-toolchain `.cgpr` files to `default.cgpr` now results in a successful cross-build.

Running `strace` on `alr build` revealed some things that needed to be updated and/or fixed in the `.cgpr` files.

**Comment by mosteo** [comment]
Closing then.
