### ISSUE TITLE
Invalid reference to `alr list` in Getting Started document

### ISSUE THREAD

**Issue by mgrojo** [alire-project/alire#772]
In `doc/getting-started.md`, which I presume is the source of https://alire.ada.dev/docs/#finding-available-projects, there is an incorrect reference to a no longer valid command v1.0: `alr list`.

According to PR #671, it was removed in v1.0.

**Comment by mosteo** [comment]
Thanks for the report, Manuel. Fixed in https://github.com/alire-project/alire/pull/773.
