### ISSUE TITLE
config.toml and indexes/ in two different places

### ISSUE THREAD

**Issue by pmunts** [alire-project/alire#786]
On Debian 10 (Buster) Linux, the alr command seems to put config.toml and indexes/ in ~/.config/ sometimes and ~/.config/alire/ othertimes.

I can't reproduce this consistently, but it happens occasionally on all my development machines, ranging from Debian on a real machine, in WSL1, and in a ChromeOS Crostini VM.  I am using a local index checkout for testing my own crates, and I generally notice this issue when suddenly the crates I am testing are missing, because alr has switched where it is looking for indexes/.

**Comment by mosteo** [comment]
I suspect this will depend on `XDG_CONFIG_HOME` being defined. 

This is still a bug because, when defined, the alire config path should be `$XDG_CONFIG_HOME/alire` and not just `$XDG_CONFIG_HOME`, as we are using now.

**Comment by mosteo** [comment]
@pmunts, would you be so kind if time allows, to test #816 and see if it fixes your issue?
