### ISSUE TITLE
v1.1.0-rc1 build failure with FSF GNAT 7.5.0

### ISSUE THREAD

**Issue by 1ma** [alire-project/alire#790]
```
$ gprbuild -P alr_env.gpr
   ...
   [Ada]          alire-config.adb
   [Ada]          alire-utils-tables.adb
   [Ada]          alire-solver.adb
alire-solver.adb:274:45: prefix of "Image" attribute must be a type
alire-solver.adb:288:45: prefix of "Image" attribute must be a type

   compilation of alire-solver.adb failed

gprbuild: *** compilation phase failed

$ gnat --version
GNAT 7.5.0
Copyright (C) 1996-2017, Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The readme states that Alire needs an Ada 2012 compiler, and clarifies that in practice this means FSF GCC 7.2 onwards. Ubuntu 18.04 ships with FSF GCC 7.5.0 and its toolchain fails to build v1.1.0-rc1. It successfully builds Alire v1.0.1 though.

I've also tested FSF GCC 9.3.0 (Ubuntu 20.04) and GCC 10.3.0 (Ubuntu 21.04) and these build v1.1.0-rc1 fine. I guess it's either a case of tweaking these two `Trace.Debug` statements from `alire-solver.adb` or the readme.

**Comment by mosteo** [comment]
Thanks for the report, Marcel. Although the fix is simple in this case, the intention is to support the latest stable OS releases (Debian, Ubuntu, etc) onwards, so I'll tweak the readme too.
