### ISSUE TITLE
Report paths for toolchains

### ISSUE THREAD

**Issue by pyjarrett** [alire-project/alire#800]
## Problem

Paths to toolchains need to be added to `$PATH` for some integrations (e.g. Ada Visual Studio Code plugin).

## Possible solution

Maybe a `--paths` or `--show` option for `alr toolchain` which would list the path to the `bin/` of the toolchain.

**Comment by Fabien-Chouteau** [comment]
If you run `alr printenv` all the paths to the toolchain should be there.
