### ISSUE TITLE
v1.1.0-rc1 alr toolchain looses sight of external GNAT after evaluating alr printenv

### ISSUE THREAD

**Issue by 1ma** [alire-project/alire#802]
```
root@c738c7d30f61:~/radatracer# alr toolchain --select
-- selected gnat_native and external gprbuild

root@c738c7d30f61:~/radatracer# alr toolchain
CRATE         VERSION  STATUS    NOTES                        
gprbuild      2019.0.0 Default   Detected at /usr/bin/gprbuild
gnat_native   10.3.0-1 Default                                
gnat_external 9.3.0    Available Detected at /usr/bin/gnat    

root@c738c7d30f61:~/radatracer# eval `alr printenv`

root@c738c7d30f61:~/radatracer# alr toolchain
CRATE         VERSION  STATUS    NOTES                                                                   
gprbuild      2019.0.0 Default   Detected at /usr/bin/gprbuild                                           
gnat_native   10.3.0-1 Default                                                                           
gnat_external 10.3.0   Available Detected at (...)cache/dependencies/gnat_native_10.3.0_8b7c5dcd/bin/gnat
```

I understand why this is happening, but gnat_external should probably still be 9.3.0 from /usr/bin/gnat
GPRBuild must be having the same problem.

**Comment by mosteo** [comment]
Ha, interesting. This one is going to be a head scratcher to solve, I can feel it.

**Comment by Fabien-Chouteau** [comment]
`gnat-external` means "any compiler in PATH" so when you eval `alr printenv` it's normal that the new detected compiler is the one from Alire. I don't see how we can do differently here, or even if we should do anything differently.

**Comment by mosteo** [comment]
I was thinking that we can disable detection for compilers that we ourselves have deployed, so at least they don't appear twice as native and external.

**Comment by Fabien-Chouteau** [comment]
gprbuild will use what is first on PATH so if PATH is changed there's not much to do AFAICS.
