### ISSUE TITLE
[Request] Name bin release packages with architecture

### ISSUE THREAD

**Issue by MarcusE1W** [alire-project/alire#817]
Hi.

Thanks for the great tool. This is really a good help, also/especially for beginner like me.

Is it possible to mark the binary release packages with the architecture they support ? Like AMD64 or X86_64 or so?
I am using an ARM device and there is always this moment where you think, maybe this will work. Especially with Appimage packages. It's just a small thing so super low prio.

Even better would be if packages for aarch64 could be provided, but in fairness compiling from source with the instructions of the README works fine and does not take long. I appreciate that there are probably not that many ARM users.

**Comment by mosteo** [comment]
Thanks for the suggestion, it makes sense to me too.
