### ISSUE TITLE
Newby question: using alire to build Emacs's ada-mode

### ISSUE THREAD

**Issue by bk322** [alire-project/alire#843]
Is it possible to use alire to build Emacs's ada-mode?
I've installed ada-mode via ELPA, and it says I need to build it.

So I went to
```bash
cd ~/.emacs.d/elpa/ada-mode-7.1.8
./build.sh
```
but it complains that I need to provide it `gnatcoll`, `gnatcoll_sqlite`, `gnatcoll_xref`.

I figured out I can fetch these with alire as:
```bash
alr init --bin myproj
cd myproj
alr with gnatcoll gnatcoll_sqlite gnatcoll_xref
```
but how do I tell ada-mode's `build.sh` about these?
I see that these are found under `myproj/alire/cache/dependencies/`, and I know there is `GPR_PROJECT_PATH` environment variable, I can probably list these manually, but that can't be right.

**Comment by mosteo** [comment]
Once you have your dependencies, you can see the environment with `alr printenv`, and you can apply it with e.g. `source <(alr printenv)`.

**Comment by mosteo** [comment]
I'm closing this one. @bk322 , if you don't succeed, I think the https://github.com/alire-project/alire/discussions feature is better for this kind of question which isn't exactly an issue (in principle).
