### ISSUE TITLE
Saturate elapsed build time

### ISSUE THREAD

**Issue by jquorning** [alire-project/alire#868]
I have been playing with `alr test --full` lately. Several times a Constraint_Error occurred when the computer sleeps during building. The problem occurs in `air-testing-markdown.adb:75` and probably in `alr-testing-console.adb` otherwise. Both places the elapsed build times are converted to a fix point type (called CS) for formatting. The range of CS is ok, but the conversion should be saturated/clamped.

I can make a PR solving the problem, but I would like to know if I should duplicate then code in the two packages or if a common conversion should be introduced in `air-testing`, `alr-util` or elsewhere.

**Comment by mosteo** [comment]
The CS trick was out of deadline pressures, so better get rid of it. I think you can now use `Stopwatch.Image` that uses proper Duration IO. Although you could take a peek at the implementation to see if this saturation/clamping might be also a problem there. Thanks!
