### ISSUE TITLE
Meaning of the `licenses` field in alire.toml files

### ISSUE THREAD

**Issue by onox** [alire-project/alire#874]
I see some crates like the gnat_* crates have a `licenses` field like this:

`licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"`

Sorry for yet another question about licenses :roll_eyes:, but what does the `licenses` field exactly indicate? Does it indicate the license of code that ends up in a lib/bin (like in this case the RTS) or does it include tools (like in this case the compiler itself) as well? If the former, the `WITH` exception in the SPDX expression above is rather pointless, but I guess the latter is meant.

I'm asking because I would like to build an `alr` command that checks the license compatibility of a set of crates. Basically something similar to what this `cargo` plugin does: https://embarkstudios.github.io/cargo-deny/checks/licenses/index.html

**Comment by mosteo** [comment]
I have no say on the particular crates you mention but my idea has always been that eventually you're able to check that you're using compatible licenses.

**Comment by Fabien-Chouteau** [comment]
The `licenses` field has to be a valid SPDX expression as defined [here](https://spdx.github.io/spdx-spec/SPDX-license-expressions/), that specify the license of the source code. How does that then translate to the produced binary will depend on the licenses themselves I guess.

Alire uses my [SPDX parser](https://github.com/Fabien-Chouteau/spdx_ada/blob/main/src/spdx.ads). It checks for the validity of the expression but no representation tree is built from it yet. So I think that would be the first step.
