### ISSUE TITLE
simple_components=4.42.0: Download not available any longer

### ISSUE THREAD

**Issue by jquorning** [alire-project/alire#879]
@mosteo 
-- begin mail from Dmitry Kazakov

On 2021-10-13 15:53, Jesper Quorning wrote:
> The simple components source archive 4.42 is not available. Is that temporary or permanent?
> The reason for asking is because it is referenced by the alire crate simple_components=4.42.0 [1].

The historic versions are kept at sourceforge:
https://sourceforge.net/projects/simplecomponentsforada/files/releases/
4.42 is there.

-- end mail

**Comment by mosteo** [comment]
OK, thanks for the heads-up.

**Comment by mosteo** [comment]
Fixed by https://github.com/alire-project/alire-index/pull/380
