### ISSUE TITLE
Alire assumes that wget is available during Gnatcoll crate build

### ISSUE THREAD

**Issue by kevlar700** [alire-project/alire#890]
alr does not seem to check if wget is installed and attempts to continue after execution fails. Some breakage appears to occur as the build needs to start fresh once wget is installed, to succeed.

I'm not sure if this is the right place to raise this. Xmlada-22 has built on this machine without wget outside of alr.

The issue occurs during
 "Running post fetch actions for xmlada=22.0.0..."

wget http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=Head" -o config.guess

p.s. I'm not sure what config guess is used for, but is https better/required here?

**Comment by Fabien-Chouteau** [comment]
Hi @kevlar700 I am changing the XMLAda manifest to not rely on wget anymore: https://github.com/alire-project/alire-index/pull/403
