### ISSUE TITLE
OpenBSD make does not support -- syntax like GNU make

### ISSUE THREAD

**Issue by kevlar700** [alire-project/alire#898]
On OpenBSD, when I run 
alr get aws

I get looking for external crate: make... Make: unknown option -- -

If OpenBSDs make is otherwise compatible?

"https://man.openbsd.org/make"

Then it may be that a simple flag change is required.

Otherwise OpenBSD ships make with base and GNU make is installed at /usr/local/bin/gmake

Perhaps alr could try gmake, if make fails. I am not sure what the other BSDs do or provide in base but OpenBSD avoids GPL'd code.

**Comment by kevlar700** [comment]
Looks like the aws build requires gmake anyway

**Comment by Fabien-Chouteau** [comment]
I would not expect AWS to work on OpenBSB just like that anyway.
