### ISSUE TITLE
alr toolchain --select does not use --install-dir

### ISSUE THREAD

**Issue by onox** [alire-project/alire#905]
Because of quotas I want to install the toolchains not in $HOME. I could manually install the toolchains with `alr toolchain --install-dir=some/folder -i gnat_native` (and a similar command for `gprbuild`), but subsequently running `alr toolchain` shows the toolchains being detected as `gnat_external` instead of `gnat_native`.

It may be easier for users who want to go through the selection wizard and/or be helpful that alr knows that the toolchain is `gnat_native` if some `--upgrade` option is added in the future.

**Comment by onox** [comment]
Related, when I do `alr get` to install some crate, I get:

```
debug: Toolchain environment: tool not in solution nor defined by the user: gnat
debug: Not redoing detection of externals for crate gnat_external
debug: Not redoing detection of externals for crate gnat
debug: Not redoing detection of externals for crate gprbuild
debug: Going back to folder: /some/path/to/cwd
debug: ---8<--- Exception dump begin ---8<---
debug: CONSTRAINT_ERROR
debug: Not installed: gprbuild=22.0.1
debug: raised CONSTRAINT_ERROR : Not installed: gprbuild=22.0.1
```

Running `alr build -vd` in the crate folder shows:

```
detail: Spawning: ["git", "branch"] > GNAT-TEMP-000002.TMP
detail: Using default value for configuration 'update-manually-only': 'FALSE'
detail: Index already loaded, loading skipped
detail: Detected missing dependency sources, updating workspace...
detail: Spawning: ["gnat", "--version"] > GNAT-TEMP-000003.TMP
detail: Spawning: ["gnat", "--version"] > GNAT-TEMP-000004.TMP
detail: Spawning: ["gprbuild", "--version"] > GNAT-TEMP-000005.TMP
detail: Looking for system package: gprbuild
detail: Spawning: ["dnf", "-y", "list", "gprbuild"] > GNAT-TEMP-000006.TMP
stderr: CONSTRAINT_ERROR                    
stderr: Not installed: gprbuild=22.0.1
stderr: raised CONSTRAINT_ERROR : Not installed: gprbuild=22.0.1
```

`alr toolchain` seems to detect GNAT and gprbuild:

```
CRATE         VERSION STATUS    NOTES                                                                   
gprbuild      22.0.0  Available Detected at (...)some/path/toolchain/gprbuild_22.0.1_24dfc1b5/bin/gprbuild
gnat_external 11.2.0  Available Detected at (...)some/path/toolchain/gnat_native_11.2.3_d255cfb3/bin/gnat
```

and `gprbuild --version` shows: `GPRBUILD 22.0.0 (2021-11-09) (x86_64-pc-linux-gnu)`

**Comment by Fabien-Chouteau** [comment]
The `alr toolchain --install-dir` option is really just here for people that want to use the Alire provided toolchains but outside of an Alire workflow. To be honest, I am not sure it was a great idea in the first place.

For what you want do, the solution IMO is to change the location of the Alire config dir. Either with the `ALR_CONFIG` env variable:
```console
$ export ALR_CONFIG=/tmp/alire_config
$ alr toolchain
```
or with the command line option:
```console
$ alr --config=/tmp/alire_config/ toolchain
```
But you have to pass this option every time you run `alr`.
