### ISSUE TITLE
Question: When or if can I remote obsolete releases?

### ISSUE THREAD

**Issue by pmunts** [alire-project/alire#907]
When (or if) is it appropriate to remove old and/or obsolete releases from the index repository?

**Comment by Fabien-Chouteau** [comment]
Never. Even if the release is obsolete people may still have projects that depend on it, so removing it will break their builds.
See https://alire.ada.dev/docs/#release-immutability

**Comment by mosteo** [comment]
Similar advice can be found at the semver site, here: https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version
