### ISSUE TITLE
Alire checks manifest files of all releases in index for no reason

### ISSUE THREAD

**Issue by onox** [alire-project/alire#910]
When running commands like `alr clean` or `alr run -s` (probably other commands as well), Alire seems to parse every single .toml file in the index. This adds like over half a second of startup latency to `alr run`. Why are these files parsed at all?

**Comment by mosteo** [comment]
Essentially, anything that involves dependencies (like building before running) currently requires the index to be loaded in full to ensure that dependencies are properly in place. 

There are several evident optimizations that we could make. A general one would be to only load dependencies on demand: #381 (and also only load the required crates recursively). Another one is, if we have a lockfile and there are no dependencies, do not load anything. Also we could rely on the lockfile to check that dependencies are in place, although this has collateral implications that make it not trivial.

But in essence it is a matter of time/priority for this to become a target for optimization.
