### ISSUE TITLE
Msys2 install on Windows may require update after first install

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#918]
See e.g. https://github.com/alire-project/alire-index/pull/421#issuecomment-1018710084

It seems we should do that just after installation to ensure the freshest libraries are available.

**Comment by Fabien-Chouteau** [comment]
It seems strange that a fresh install doesn't have the latest libraries.

**Comment by mosteo** [comment]
Indeed. I'm running tests about this but that seems to be the case. It's actually requested in the install instructions: https://www.msys2.org/ steps 5/6.

**Comment by mosteo** [comment]
Fixed by #923, closing.
