### ISSUE TITLE
Add `-gnatW8` as a default option

### ISSUE THREAD

**Issue by reznikmm** [alire-project/alire#919]
Today UTF-8 is "a default" encoding for source files almost everywhere. GNAT compiler has stuck with brackets encoding as default for non-ASCII characters. Alire creates project skeletons with `for Default_Switches ("Ada") use ...`

I propose to add `-gnatW8` to this compiler option list.

**Comment by mosteo** [comment]
I'm in favor of all things Unicode. If this doesn't have any side-effects I say let's go for it. I have read at comp.lang.ada though that GNAT doesn't play entirely nice with such files for some obscure reasons that I frankly didn't understand at the time. Time to review that...

**Comment by Fabien-Chouteau** [comment]
This would now require a change in the build profile system: https://github.com/alire-project/alire/blob/master/src/alire/alire-utils-switches.adb

But I don't know in which category this should go...

**Comment by Fabien-Chouteau** [comment]
And documented here: https://github.com/alire-project/alire/blob/9076580925feebea95f9c4379b2b779410ef3cfe/src/alire/alire-utils-switches-knowledge.adb#L48

**Comment by Fabien-Chouteau** [comment]
@reznikmm I am looking at this issue. What are the consequences of the `-gnatW8` switch. Can you provide an example to try it out?

**Comment by reznikmm** [comment]
This switch make compiler work as Standard requires (See [ARM 2.1 16/3](http://www.ada-auth.org/standards/rm12_w_tc1/html/RM-2-1.html)):
> An Ada implementation shall accept Ada source code in UTF-8 encoding

So you can write this:
```ada
with Ada.Wide_Wide_Text_IO;

procedure Main is
   R : Float := 4.0;
   π : constant := 3.1415926;
   
   Area : Float := π * R**2;
begin
   Ada.Wide_Wide_Text_IO.Put ("πr²=");
   Ada.Wide_Wide_Text_IO.Put (Area'Wide_Wide_Image);
   Ada.Wide_Wide_Text_IO.New_Line;
end Main;
```

And get output:

    πr²= 5.02655E+01

Without this switch compiler complains:
```
main.adb:5:05: error: illegal character
main.adb:7:21: error: illegal character
```
Because by default GNAT use a [custom encoding](https://docs.adacore.com/gnat_ugn-docs/html/gnat_ugn/gnat_ugn/the_gnat_compilation_model.html#wide-character-encodings)  (where `π` should be represented by a sequence of 8 characters - `["03C0"]`).

This switch also affects I/O encoding. For example:

```ada
with Ada.Wide_Wide_Text_IO;

procedure Main is
begin
   Ada.Wide_Wide_Text_IO.Put (Wide_Wide_Character'Val (16#03C0#));
   Ada.Wide_Wide_Text_IO.New_Line;
end Main;
```

This program will print `["03C0"]` without switch, but with `-gnatW8` it prints `π` as expected. This because `-gnatW8` implies `-W8` switch for `gnatbind`.

**Comment by Fabien-Chouteau** [comment]
Thanks @reznikmm,

Do you think we need an `source_encoding` category in the build profile system? It doesn't fit with the other categories.

**Comment by Fabien-Chouteau** [comment]
We can also say that it's up to each project to add this switch if needed.

**Comment by reznikmm** [comment]
I would add this switch unconditionally. I see no practical usage of
encoding other than utf8. Also there is no harm from this switch for
projects where plain ASCII is used.

**Comment by Fabien-Chouteau** [comment]
see #972

**Comment by reznikmm** [comment]
After reading #972 I would state current status as this:

**It's impossible to use non-ASCII characters in (the source code of) alire crates currently.**

<details><summary>Proof</summary>

1. Suppose `A` crate author uses UTF-8 to store non-ASCII characters in his crate and specified `-gnatW8` 
   in its project. Alire accepts and compiles this without error, as expected:

   ```ada
   package Utf8 is
      Text : constant Wide_Wide_String := "πr²";
      pragma Compile_Time_Warning (Text'Length /= 3, "Bad encoding");
   end Utf8;
   ```

   A dependent crate `D` by default won't work, because `Text'Length = 5` with default switches
   (`-gnatW8` from crate `A` is ignored during `D` compilation).
   Compilation of crate `D` would work if `D` includes `-gnatW8` in its compiler option, but
   
    * It's hard to find that `D` need `-gnatW8`. To do this the author of `D` should inspect each
       dependency and sub-dependency.
    * If a dependency or sub-dependency uses an encoding different from UTF-8 (bracket
       encoding, for example), then there is no solution at all.

2. If `A` uses non-ASCII characters with non-UTF-8 encoding (like default bracket encoding),
    then `D` can't use UTF-8 and `-gnatW8` option. Any dependency of `D` should not use
   `-gnatW8`, but this is out of control of `D` author.

</details> 

Now, we should choose one of
* disable any non-ASCII characters in all crates
* ensure that all crates those have non-ASCII characters uses the same encoding
  * for brackets encoding this means - any crates shouldn't use `-gnatW8`
  * for UTF-8 encoding this means - ideally all crates should use `-gnatW8` even if they don't contain non-ASCII characters. It looks it's hard to ensure right now, so we can try a bit weaker requirements If a crate use non-ASCII characters then it should use `-gnatW8` and any dependent crates should use `-gnatW8` too.

After we agree on any of these choice, I hope, it won't be hard to implement corresponding checks on alire CI.

I vote for UTF-8. If you want, as a first step I could find all crates with non-ASCII characters and see if they have `-gnatW8`.

**Comment by mosteo** [comment]
Interesting analysis, Maxim. 

I don't think we can turn our backs to UTF-8, but this is a topic where I'm insufficiently experienced.

Could we unconditionally apply `-gnatW8` on the command-line and override any project files? Once we fix any failing crates, would we be clean to move forward?

Also, not sure if this bit of info about `-gnatW` in the [docs](https://docs.adacore.com/gnat_ugn-docs/html/gnat_ugn/gnat_ugn/building_executable_programs_with_gnat.html#character-set-control): 

> 8 | UTF-8 encoding (brackets encoding also recognized)

affects your comments about brackets? (My guess is you're well aware of this, so no.)

**Comment by reznikmm** [comment]
Indeed, I've missed the point that brackets coding is always accepted. Perhaps, because in my understanding this is a standard violation.

So, if we apply `-gnatW8` to a project then we can encounter incompatibility just in one case:
* ASCII character - works fine :heavy_check_mark:
* non-ASCII character represented in bracket encoding - works fine too, as you pointed. (But violates the standard) :heavy_check_mark:
* non-ASCII Latin-1 characters :red_square: 
  * could cause a compilation error if characters compose invalid utf-8 sequence (like `"Ð"`)
  * but also could combine in a valid utf-8 sequence (like `"Ð¤"`, encoding of "Ф"). I guess the probability is about 0%.

An example of this incompatibility (a legal Ada program stored in Latin-1 encoding):
```ada
procedure Main is
   S : constant String := "Ö";
begin
   null;
end Main;
```

And required fix is converting it into UTF-8 and add `-gnatW8` to compiler switches.
Once we fix all failing crates, we could force `-gnatW8` for all crates and ask crate authors to keep sources in UTF-8 encoding.

PS @pmderodat - invitation to the discussion.

**Comment by Fabien-Chouteau** [comment]
Based on Max's analysis I think it's OK to use enable this switch in the crate configuration. I re-opened #972
