### ISSUE TITLE
Rework the notes/comments situation

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#92]
To clarify the textual information we provide about releases in the index, I advance this idea (from #90):

General properties, not overridable by specific releases:
- description (as it's now, mandatory short one liner)
- long-description (free text, multi line, optional)

Release specific release notes:
- notes (free text, multi line, optional)

**Comment by pmderodat** [comment]
The short/long descriptions duality looks worthwhile, but I’m not clear about release-specific notes: do we expect project descriptions to duplicate upstream release notes?

**Comment by mosteo** [comment]
No, my idea was to be able to store any free-form specific information that applies only to a single release, in the context of alire.
