### ISSUE TITLE
Detecting platform and architecture and executing code based on this information

### ISSUE THREAD

**Issue by ethindp** [alire-project/alire#935]
So I don't know if this is a gprbuild or alire question, so I thought I'd throw this in here.

I'm working with crypto and wanting to generate a sequence of secure random bytes for PKC. On Linux/Unix platforms, this is as simple as something like:

```ada
with Interfaces; use Interfaces;
subtype Byte     is Unsigned_8;
type Random_Byte_Seq is array (0 .. 32) of Byte;
function Gen_Random_Key returns Random_Byte_Seq is
  with Ada.Streams.Stream_IO; use Ada.Streams.Stream_IO;
   Random_File: File_Type;
   Crypto_Key: Byte_seq := (Others => 0);
begin
   Open (File => Random_File,
                               Mode => In_File,
                               Name => "/dev/urandom");
for i in 1 .. 32 loop
      Byte'Read (Stream(Random_File), Crypto_Key(i));
   end loop;
   Close (Random_File);
   return Crypto_Key;
end Gen_Random_Bytes;
```
But on Windows, one must use a function sequence like [CryptAcquireContextA](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptacquirecontexta) -> [CryptGenRandom](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptgenrandom) -> [CryptReleaseContext](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptreleasecontext). So, how do I tell my code to do either of these operations, depending on OS? I could use an instruction like RDRAND but I don't want to tie my code to any one architecture.

**Comment by ethindp** [comment]
Edited my comment to fix a typo.

**Comment by mosteo** [comment]
Given that you'll have to compile different executables for the different OSes, you should at compilation time select the proper implementation for the OS. You can check for example how Alire does it for its OS-dependent code. We have a common spec in [`alire-platforms-current.ads`](https://github.com/alire-project/alire/blob/master/src/alire/alire-platforms-current.ads) with OS-specific bodies in `alire-platforms-current__*.adb`. The bodies are selected in the [`alire.gpr`](https://github.com/alire-project/alire/blob/42a39ccde76998ed7c8451660b923b54c369d3e3/alire.gpr#L31) project file. Classifying the files in separate folders is not really necessary if you give unique names to the bodies.

As this is a general Ada question, I'm closing this issue.
