### ISSUE TITLE
Alire fails to find dependency of dependency

### ISSUE THREAD

**Issue by TamaMcGlinn** [alire-project/alire#937]
I have a project (adabots_examples) which has a single direct dependency (adabots). However, in a new version of adabots, it now needs aaa. After adding that to adabots using `alr with aaa`, [publishing to this branch for the reproducer's convenience](https://github.com/TamaMcGlinn/alire-index/tree/experimental_adabots), and updating adabots_examples to require the new version (1.1.0), I see that adabots_examples has not picked up the new indirect dependency.

```
$ git clone git@github.com:TamaMcGlinn/adabots_examples -b experimental
Cloning into 'adabots_examples'...

$ cd adabots_examples/
$ alr build
No dependency solution found, updating workspace...
Dependencies automatically updated as follows:                     

   + adabots 1.1.0    (new)         
   + aws     21.0.0   (new,indirect)
   + gnat    2021.0.0 (new,indirect)
   + make    4.3.0    (new,indirect)
   + xmlada  21.0.0   (new,indirect)

(you can cntrl-C here, no need to wait for the build)
```

If I go into alire/cache/dependencies/adabots and do `alr update` in there, it sees that aaa is missing and clones it into adabots_examples/alire/cache/dependencies/adabots_1.1.0_974b587b/alire/cache/dependencies. Any ideas how to get the toplevel project to see that it needs aaa through the new adabots release?

**Comment by mosteo** [comment]
This should indeed work. One thing I note is that there is no dependency on `aaa` in https://github.com/TamaMcGlinn/alire-index/blob/experimental_adabots/index/ad/adabots/adabots-1.1.0.toml but according to your explanation there should be?

If you want to make tests more quickly without going through the whole publishing round, you can use your WIP `adabots` version through a pin in `adabots_examples`. Dependencies should propagate the same way.

**Comment by TamaMcGlinn** [comment]
Thanks, that was the issue.
