### ISSUE TITLE
Querying gprbuild external is very slow on Msys2

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#962]
~This is unexpected, very slow, and in any case we must look at how we could speed up things with `pacman` (may be we're doing an online refresh).~

We hit this problem whenever we run the gprbuild external detection, which is whenever there is a configured toolchain other than `None`.

**Comment by Fabien-Chouteau** [comment]
I just checked and I don't think that the command we use with pacman do online updates, only `pacman -Sy` does.

**Comment by Fabien-Chouteau** [comment]
I am also asking the msys2 people if there are faster ways to get the info we need.

**Comment by mosteo** [comment]
This one https://github.com/msys2/MSYS2-packages/issues/2949 seems to be relevant, as perhaps https://github.com/msys2/MSYS2-packages/issues/2560

Edit: I see it was created in response to Fabien probing, nice.
