### ISSUE TITLE
How to analyze Alire projects with LibAdaLang?

### ISSUE THREAD

**Issue by pjljvandelaar** [alire-project/alire#971]
Dear Alire developers,

I have some projects that are analyzed with LibAdaLang (and my own library)
See e.g. https://github.com/TNO/Rejuvenation-Ada/tree/main/workshop/tests

When I move these projects to alire, I have problems analyzing them with LibAdaLang.
How could I fix this?
Can I get somewhere what the GPR_PROJECT_PATH is (as concluded by Alire from the `alire.toml` file)?

Thanks in advance for your answer!

Pierre

**Comment by mosteo** [comment]
`alr printenv` will tell you the environment in use during `alr` runs. Also, in the master branch soon to become version `1.2`, you can use `alr exec -- <script/exec>` to run under the same environment. Will this help you?

**Comment by pjljvandelaar** [comment]
From within a test I seem unable to change global settings permanently

```
with Interfaces.C;                use Interfaces.C;

procedure Main is
   Invocation_Exception : exception;

   procedure Execute_Command (Command : String);
   procedure Execute_Command (Command : String) is
      function Sys (Arg : char_array) return Integer;
      pragma Import (C, Sys, "system");

      Ret_Val : Integer;
   begin
      Ret_Val := Sys (To_C (Command));
      if Ret_Val /= 0 then
         raise Invocation_Exception
           with Ret_Val'Image & " for '" & Command & "'";
      end if;
   end Execute_Command;
   
begin
   Execute_Command ("set TEST=True && set TEST");
   Execute_Command ("set TEST=False && set TEST");
   
   Execute_Command ("set TEST=True");
   Execute_Command ("set TEST");
   Execute_Command ("set TEST=False");
   Execute_Command ("set Test");   
end Main;
```

Results in 
```
TEST=True 
TEST=False 
Environment variable TEST not defined

raised MAIN.INVOCATION_EXCEPTION :  1 for 'set TEST'
```
so the commands work, but the impact is not a permanent change!

**Comment by Fabien-Chouteau** [comment]
Hi @pjljvandelaar ,

I am not sure to understand what you want to achieve here.
The environment variables do not propagate to the parent process.

**Comment by pjljvandelaar** [comment]
Hi @Fabien-Chouteau,

I have a test suite that has a number of test cases.
Each test case verifies behaviour related to the analysis of a project (using libadalang and GNATColl).
The analysed project is NOT identical in all test cases.
So I have a number of different projects.
These projects are recently converted to alire and currently the test cases fail to parse them all correctly in a single test suite run.

For the test suite to pass in a single run, I have to provide the appropriate environment to each test case.
So far, I have tried but was unable to achieve this goal.

Does it clarify what I want to achieve?

Pierre

**Comment by Fabien-Chouteau** [comment]
Indeed, thanks Pierre.

Instead of trying to set a correct environment, maybe you should use spawn `alr exec` to run the test cases.

**Comment by pjljvandelaar** [comment]
Hi @Fabien-Chouteau 

As far as I understood: `alr exec` executes a program.
How can I use it to run a single test case?

Since not all ada projects are in alire yet, 
I recently added a test case to analyse a non-alire project as well - `alr exec` will definitely not work in that case!

Any idea how to change the settings / environment variables for such a test-case,
since currently the settings / environment variables are taken from my own alire project....

Greetings,
   Pierre

**Comment by pjljvandelaar** [comment]
Hi all,

Based on your feedback I was able to solve the problem:
I can get the proper setting using `alr printenv`.
With Ada.Environment_variables I can ensure the proper setting for the analyzed project.

So I close this issue.


Greetings,
   Pierre
