### ISSUE TITLE
Select source style checks

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#98]
No style is enforced now. To homogenize contributions, we could enforce a set of style checks.

**Comment by mosteo** [comment]
@pmderodat, you mentioned -gnatyg, which I see is the own GNAT compiler styles. Would that be overkill? Is that used in all adacore projects?

I see that @Fabien-Chouteau uses "-gnaty", "-gnatyM120", "-gnatyO" in ADL's microbit.

-gnatyO I have used in the past and I think it's a good idea.

For the line length, 79 is a bit less than I use, but I guess I could live with that. I rarely go over 100ish myself.

I like those:
-gnatyC (comments, single space)
-gnatyD (Mixed case)
-gnatyI (no in mode)
-gnatyk (lowercase reserved)
-gnatyl (layout)
-gnatyn (standard entities)
-gnatyO (no missing overriding)
-gnatyr (consistent use of identifiers)
-gnatyt (token spacing)

and line length either 80 or 100.

**Comment by pmderodat** [comment]
As discussed live: let’s aim for `-gnatyg`. :-) Fabien started to work on this: see #115

**Comment by mosteo** [comment]
Fixed in 9bf892c
